import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import fc from "fast-check";
import { describe, expect, it } from "vitest";

import { parseExpression } from "../src/core/parser.js";
import type { ClauseKind, Node, ParseError } from "../src/core/parser.js";
import { extractManifests } from "../src/extractors/index.js";
// The generator core (src/generator/) is implemented; these value imports
// resolve at runtime. The assertions below pin the xunit/pytest emitter
// contract the implementation must satisfy.
import { emitSuite, planTestCases } from "../src/generator/index.js";
import type {
	EmittedFile,
	EmitterFramework,
	PlannedCase,
	PlannedSuite,
} from "../src/generator/index.js";
import type {
	ContractClause,
	ContractsFile,
	ManifestsFile,
	PredicatesFile,
	VersaillesContext,
	WorkspaceConfig,
} from "../src/loader/workspace.js";

/**
 * xUnit and pytest emitters (ADR-0008/0009, build-spec §9.4) — regression
 * battery for the complete v1 emitter matrix.
 *
 * emitSuite(suite, framework) dispatches across vitest | xunit | pytest
 * (src/generator/index.ts, ADR-0009). ADR-0009 pins the v1 matrix C#→xUnit
 * (`*.Tests.cs`) and Python→pytest (`test_*.py`); config.schema.json accepts
 * `testFramework: "xunit" | "pytest"` and src/cli/handlers/generate.ts routes
 * `context.config.testFramework` straight into emitSuite. This file freezes
 * the emitters' fixed behavior so regressions fail here. The suite IR is
 * shared and framework-agnostic (ADR-0008); only the rendering differs. The
 * vitest emitter (src/generator/emitters/vitest.ts) is the template — every
 * decision below mirrors its existing semantics.
 *
 * ── Fixed-behavior contract (what the xunit/pytest emitters MUST render) ───
 *
 * File shapes (per component, mirroring vitest's per-component files):
 *   xunit:  <generatedDir>/<Component>.Tests.cs
 *   pytest: <generatedDir>/test_<Component>.py
 *
 * Header (deterministic, no timestamps — ADR-0002):
 *   xunit:  `// Auto-generated by the Versailles deterministic generator core.`
 *           `// Do not edit — regenerate with \`versailles generate\`.`
 *           `// traces: "ClauseId", "ClauseId", ...`   (clause ids
 *           JSON.stringify-escaped and joined with ", " — §9.3)
 *   pytest: same three lines with `#` comment markers.
 *
 * Imports (the modulePaths analog — Center W4; mirrors vitest's
 * `modulePaths[component] ?? "../../src/<Component>.js"`):
 *   xunit:  `using System;` + `using Xunit;` +
 *           `using <modulePaths[component] ?? "Versailles.Components.<Component>">;`
 *   pytest: `import pytest` +
 *           `from <modulePaths[component] ?? "components.<Component>"> import <Component>`
 *
 * Naming:
 *   xunit class: `public class <Component>Tests`
 *   method name: the FULL case id with every non [A-Za-z0-9_] char replaced
 *                by `_` (e.g. `AccountService.withdraw.boundary-0` →
 *                `public void AccountService_withdraw_boundary_0()`), so names
 *                are unique per file and never collide.
 *   pytest fn:   `def test_<id with non [A-Za-z0-9_] → _>():`
 *   case comment above each method: `// <case.id> — <case.description>`
 *                (xunit) / `# <case.id> — <case.description>` (pytest).
 *
 * Case rendering (per case, never hardcoded — ADR-0007):
 *   reject + "throws":
 *     xunit:  `Assert.Throws<Exception>(() => <Component>.<operation>(<args>));`
 *     pytest: `with pytest.raises(Exception):` / `    <Component>.<operation>(<args>)`
 *   reject + "returns":
 *     xunit:  `Assert.Null(<Component>.<operation>(<args>));`
 *     pytest: `assert <Component>.<operation>(<args>) is None`
 *   accept (no assertions):
 *     xunit:  `var result = <Component>.<operation>(<args>);` + `Assert.NotNull(result);`
 *     pytest: `result = <Component>.<operation>(<args>)` + `assert result is not None`
 *   accept (with assertions — Center W2, mirror vitest's MATCHER map):
 *     xunit:  Assert.NotNull(result) + per AssertionDescriptor:
 *             >= → `Assert.True(result.<subject> >= <literal>)`
 *             >  → `Assert.True(result.<subject> > <literal>)`
 *             <= → `Assert.True(result.<subject> <= <literal>)`
 *             <  → `Assert.True(result.<subject> < <literal>)`
 *             == → `Assert.Equal(<literal>, result.<subject>)`
 *             != → `Assert.NotEqual(<literal>, result.<subject>)`
 *     pytest: `assert result is not None` + `assert result.<subject> <op> <literal>`
 *   <args> is a single object mirroring vitest's object literal — ALL case
 *   inputs (params + captured pre-state fields) in Object.entries order:
 *     xunit:  `new { amount = 9 }`, `new { amount = 55, balance = 50 }`
 *     pytest: `{"amount": 9}`, `{"amount": 55, "balance": 50}` (null → `None`)
 *   Partition cases ([Theory]/[InlineData], parametrize):
 *     xunit:  `[Theory]` + `[InlineData(<value>)]` per case; method declares
 *             the input keys as parameters (e.g. `(string newStatus)`); the
 *             body builds the object from the named params (`new { newStatus }`).
 *     pytest: `@pytest.mark.parametrize("<key>", [<value>])` per case;
 *             `def test_...( <key> )`; body builds the dict
 *             (`{"newStatus": newStatus}`).
 *
 * Dispatch (src/generator/index.ts + ir.ts):
 *   - emitSuite(suite, "xunit" | "pytest", options) dispatches instead of
 *     throwing; EmitterFramework widens to "vitest" | "xunit" | "pytest".
 *   - An UNKNOWN framework string still throws at the seam (the ADR-0008/0009
 *     rejection policy — config.schema.json rejects non-matrix values too).
 *   - Identifier safety (Center W1): component/operation names flow into
 *     class/function/file names and calls — the emitters must refuse
 *     non-identifier names (mirror vitest's assertIdentifier), never emitting
 *     a breakout file.
 *   - Determinism (ADR-0002): same suite in → byte-identical content out.
 */

const ACCOUNT = "AccountService";
const CUSTOMER = "CustomerService";

/** v1 emitter framework matrix (ADR-0009) — the EmitterFramework widening. */
const V1_EMITTER_FRAMEWORKS: EmitterFramework[] = ["vitest", "xunit", "pytest"];

function contractsFixture(): ContractsFile {
	return {
		version: "1.0",
		contracts: {
			[ACCOUNT]: {
				invariants: [{ id: "AccountService.inv0", expr: "balance >= 0" }],
				operations: {
					withdraw: {
						id: "AccountService.withdraw",
						params: [{ name: "amount", type: "number" }],
						preconditions: [
							{
								id: "AccountService.withdraw.pre0",
								expr: "amount >= 10",
							},
							{
								id: "AccountService.withdraw.pre1",
								expr: "amount <= 100",
							},
						],
						postconditions: [
							{
								id: "AccountService.withdraw.post0",
								expr: "old(balance) - amount == balance",
							},
							{
								id: "AccountService.withdraw.post1",
								expr: "old(balance) >= balance",
							},
						],
						effects: [{ field: "balance", kind: "mutate" }],
						sourceHash: "withdraw-hash",
					},
					setStatus: {
						id: "AccountService.setStatus",
						params: [{ name: "newStatus", type: "string" }],
						preconditions: [
							{
								id: "AccountService.setStatus.pre0",
								expr: 'newStatus in ["ACTIVE", "FROZEN"]',
							},
						],
						postconditions: [
							{
								id: "AccountService.setStatus.post0",
								expr: "status == newStatus",
							},
						],
						effects: [{ field: "status", kind: "mutate" }],
						sourceHash: "setstatus-hash",
					},
				},
			},
			[CUSTOMER]: {
				invariants: [],
				operations: {
					upgrade: {
						id: "CustomerService.upgrade",
						params: [{ name: "newTier", type: "enum<GOLD,SILVER>" }],
						preconditions: [
							{
								id: "CustomerService.upgrade.pre0",
								expr: "newTier != null",
							},
						],
						postconditions: [],
						effects: [],
						sourceHash: "upgrade-hash",
					},
				},
			},
		},
	};
}

function manifestsFixture(): ManifestsFile {
	return {
		version: "1.0",
		manifests: {
			[ACCOUNT]: {
				sourceHash: "man-account",
				fields: { balance: "number", status: "string" },
			},
			[CUSTOMER]: { sourceHash: "man-customer", fields: {} },
		},
	};
}

function predicatesFixture(): PredicatesFile {
	return { version: "1.0", predicates: {} };
}

function makeConfig(rejectionIdiom?: "throws" | "returns"): WorkspaceConfig {
	const config: WorkspaceConfig = {
		grammarVersion: "1.0",
		schemaVersion: "1.0",
		sourceRoots: ["src/**/*.ts"],
		language: "typescript",
		testFramework: "vitest",
		generatedDir: ".versailles/generated",
		staleness: { blockOnStale: false },
	};
	if (rejectionIdiom !== undefined) {
		config.rejection = { idiom: rejectionIdiom };
	}
	return config;
}

/**
 * Parses every fixture expr with the real parser so the context carries real
 * ASTs in parsedContracts (the shape the loader produces, build-spec §6).
 * Throws only on a fixture-authoring error — never a generator behaviour.
 */
function parseAll(contracts: ContractsFile): Record<string, Node> {
	const parsed: Record<string, Node> = {};
	const walk = (clauses: ContractClause[], kind: ClauseKind): void => {
		for (const clause of clauses) {
			const result = parseExpression(clause.expr, kind, clause.id);
			if (!result.ok) {
				throw new Error(
					`fixture parse failed for ${clause.id}: ${JSON.stringify(result.errors)}`,
				);
			}
			parsed[clause.id] = result.ast;
		}
	};
	for (const component of Object.values(contracts.contracts)) {
		walk(component.invariants ?? [], "invariants");
		for (const operation of Object.values(component.operations ?? {})) {
			walk(operation.preconditions ?? [], "preconditions");
			walk(operation.postconditions ?? [], "postconditions");
		}
	}
	return parsed;
}

/**
 * Builds a fully-loaded, isValid VersaillesContext in memory (no files, no
 * loader), mirroring the fixture approach in tests/generator.test.ts. With no
 * rejection argument the config carries NO rejection block — the ADR-0007
 * default (throws).
 */
function makeContext(rejectionIdiom?: "throws" | "returns"): VersaillesContext {
	const contracts = contractsFixture();
	return {
		config: makeConfig(rejectionIdiom),
		contracts,
		manifests: manifestsFixture(),
		predicates: predicatesFixture(),
		parsedContracts: parseAll(contracts),
		parseErrors: [],
		validationErrors: [],
		validationWarnings: [],
		isValid: true,
	};
}

function allCases(suite: PlannedSuite): PlannedCaseLike[] {
	return [
		...suite.operations.flatMap((group) => group.cases),
		...suite.invariantCases,
	];
}

/** Minimal structural subset of PlannedCase used by the helpers below. */
type PlannedCaseLike = {
	id: string;
	inputs: Record<string, unknown>;
	expects: { outcome: "accept" | "reject"; rejectionIdiom?: string };
};

function rejectCases(suite: PlannedSuite): PlannedCaseLike[] {
	return allCases(suite).filter((case_) => case_.expects.outcome === "reject");
}

describe("emitSuite — xunit emitter (§9.4, ADR-0008/0009)", () => {
	it("renders per-component *.Tests.cs files with a test class per component and a namespace import", () => {
		const suite = planTestCases(makeContext());
		const files = emitSuite(suite, "xunit" as never);

		const account = files.find((file) =>
			file.path.endsWith("AccountService.Tests.cs"),
		);
		const customer = files.find((file) =>
			file.path.endsWith("CustomerService.Tests.cs"),
		);
		expect(account).toBeDefined();
		expect(customer).toBeDefined();
		expect(account?.path.startsWith(".versailles/generated/")).toBe(true);

		// Class per component, mirroring vitest's per-component files.
		expect(account?.content).toContain("public class AccountServiceTests");
		expect(customer?.content).toContain("public class CustomerServiceTests");

		// A valid xUnit C# file: using directives + [Fact] attributes.
		expect(account?.content).toContain("using System;");
		expect(account?.content).toContain("using Xunit;");
		expect(account?.content).toContain(
			"using Versailles.Components.AccountService;",
		);
		expect(account?.content).toContain("[Fact]");

		// Violation/precondition/postcondition + invariant cases render [Fact].
		expect(account?.content).toContain("Assert.Throws<Exception>(");
		expect(account?.content).toContain(
			"public void AccountService_withdraw_invariant_0()",
		);

		// Traceability comment per file (§9.3).
		expect(account?.content).toContain("// traces:");
		expect(
			account?.content
				.split("\n")
				.some((line) =>
					/AccountService\.(inv0|withdraw\.|setStatus\.)/.test(line),
				),
		).toBe(true);
	});

	it("renders [Fact] + Assert.Throws<Exception> for reject cases — throws idiom from the case (ADR-0007)", () => {
		const suite = planTestCases(makeContext());
		const files = emitSuite(suite, "xunit" as never);
		const account = files.find((file) =>
			file.path.endsWith("AccountService.Tests.cs"),
		);
		expect(account).toBeDefined();

		// Boundary reject (amount=9 falsifies amount >= 10).
		expect(account?.content).toContain(
			"Assert.Throws<Exception>(() => AccountService.withdraw(new { amount = 9 }));",
		);
		// Boundary reject (amount=101 falsifies amount <= 100).
		expect(account?.content).toContain(
			"Assert.Throws<Exception>(() => AccountService.withdraw(new { amount = 101 }));",
		);
		// Expected-rejection: postconditions hold, invariant violated.
		expect(account?.content).toContain(
			"Assert.Throws<Exception>(() => AccountService.withdraw(new { amount = 51, balance = 50 }));",
		);
		// Accept cases are NOT wrapped in Assert.Throws.
		expect(account?.content).not.toContain(
			"Assert.Throws<Exception>(() => AccountService.withdraw(new { amount = 10 }));",
		);
	});

	it("renders [Theory] + [InlineData] for equivalence-partition cases", () => {
		const suite = planTestCases(makeContext());
		const files = emitSuite(suite, "xunit" as never);
		const account = files.find((file) =>
			file.path.endsWith("AccountService.Tests.cs"),
		);
		expect(account).toBeDefined();

		expect(account?.content).toContain("[Theory]");
		expect(account?.content).toContain('[InlineData("ACTIVE")]');
		expect(account?.content).toContain('[InlineData("FROZEN")]');
		// The outside-set partition value renders as its own InlineData row.
		expect(account?.content).toContain('[InlineData("INVALID")]');
		// Theory methods declare the input keys as parameters.
		expect(account?.content).toContain(
			"public void AccountService_setStatus_partition_0(string newStatus)",
		);
		// The reject partition case keeps the throws idiom inside the body.
		expect(account?.content).toContain(
			"Assert.Throws<Exception>(() => AccountService.setStatus(new { newStatus }));",
		);
	});

	it("calls the component operation with the configured inputs in operation scope", () => {
		const suite = planTestCases(makeContext());
		const files = emitSuite(suite, "xunit" as never);
		const account = files.find((file) =>
			file.path.endsWith("AccountService.Tests.cs"),
		);
		expect(account).toBeDefined();

		// Boundary accept case calls the component method with the input value.
		expect(account?.content).toContain(
			"var result = AccountService.withdraw(new { amount = 10 });",
		);
		// Postcondition case passes captured pre-state alongside params
		// (mirrors vitest's single object literal).
		expect(account?.content).toContain(
			"var result = AccountService.withdraw(new { amount = 55, balance = 50 });",
		);
		// The method name derives from the case id — never the case-id tail as
		// a method (Center B1 mirror).
		expect(account?.content).not.toContain("withdraw.boundary-0(");
	});

	it("renders Assert.Null for the returns rejection idiom when configured (ADR-0007)", () => {
		const suite = planTestCases(makeContext("returns"));
		const files = emitSuite(suite, "xunit" as never);
		const account = files.find((file) =>
			file.path.endsWith("AccountService.Tests.cs"),
		);
		expect(account).toBeDefined();
		const rejectCase = rejectCases(suite).find(
			(case_) => case_.inputs.amount === 9,
		);
		expect(rejectCase).toBeDefined();
		expect(rejectCase?.expects.rejectionIdiom).toBe("returns");
		expect(account?.content).toContain(
			"Assert.Null(AccountService.withdraw(new { amount = 9 }));",
		);
		expect(account?.content).not.toContain("Assert.Throws<Exception>(");
	});

	it("renders real invariant assertions on the subject field — not just Assert.NotNull (Center W2)", () => {
		const suite = planTestCases(makeContext());
		const files = emitSuite(suite, "xunit" as never);
		const account = files.find((file) =>
			file.path.endsWith("AccountService.Tests.cs"),
		);
		expect(account).toBeDefined();
		const inv = suite.invariantCases.find(
			(case_) => case_.kind === "invariant",
		);
		expect(inv).toBeDefined();

		// Scope to the invariant case's own rendered method block.
		const start = account?.content.indexOf(
			"public void AccountService_withdraw_invariant_0()",
		);
		expect(start).toBeGreaterThan(-1);
		const end = account?.content.indexOf("\n\n", start);
		const block = account?.content.slice(start, end);

		// The invariant's subject field (balance) is asserted with a real
		// matcher — the degenerate bare-accept render alone would fail this.
		expect(block).toContain("Assert.NotNull(result)");
		expect(block).toContain("Assert.True(result.balance >= 0)");
	});
});

describe("emitSuite — pytest emitter (§9.4, ADR-0008/0009)", () => {
	it("renders per-component test_*.py files with def test_*() functions and a module import", () => {
		const suite = planTestCases(makeContext());
		const files = emitSuite(suite, "pytest" as never);

		const account = files.find((file) =>
			file.path.endsWith("test_AccountService.py"),
		);
		const customer = files.find((file) =>
			file.path.endsWith("test_CustomerService.py"),
		);
		expect(account).toBeDefined();
		expect(customer).toBeDefined();
		expect(account?.path.startsWith(".versailles/generated/")).toBe(true);

		expect(account?.content).toContain("import pytest");
		expect(account?.content).toContain(
			"from components.AccountService import AccountService",
		);
		expect(account?.content).toContain(
			"def test_AccountService_withdraw_boundary_0():",
		);
		expect(account?.content).toContain(
			"def test_AccountService_withdraw_invariant_0():",
		);

		// Traceability comment per file (§9.3) — Python comment marker.
		expect(account?.content).toContain("# traces:");
		expect(
			account?.content
				.split("\n")
				.some((line) =>
					/AccountService\.(inv0|withdraw\.|setStatus\.)/.test(line),
				),
		).toBe(true);
	});

	it("renders pytest.raises(Exception) for the throws rejection idiom (ADR-0007)", () => {
		const suite = planTestCases(makeContext());
		const files = emitSuite(suite, "pytest" as never);
		const account = files.find((file) =>
			file.path.endsWith("test_AccountService.py"),
		);
		expect(account).toBeDefined();

		expect(account?.content).toContain("with pytest.raises(Exception):");
		expect(account?.content).toContain(
			'AccountService.withdraw({"amount": 9})',
		);
		expect(account?.content).toContain(
			'AccountService.withdraw({"amount": 101})',
		);
		expect(account?.content).toContain(
			'AccountService.withdraw({"amount": 51, "balance": 50})',
		);
		// Accept cases are rendered as result assignments — never wrapped in
		// pytest.raises (the reject rendering has no `result =`).
		expect(account?.content).toContain(
			'result = AccountService.withdraw({"amount": 10})',
		);
	});

	it("renders @pytest.mark.parametrize for equivalence-partition cases", () => {
		const suite = planTestCases(makeContext());
		const files = emitSuite(suite, "pytest" as never);
		const account = files.find((file) =>
			file.path.endsWith("test_AccountService.py"),
		);
		expect(account).toBeDefined();

		expect(account?.content).toContain(
			'@pytest.mark.parametrize("newStatus", ["ACTIVE"])',
		);
		expect(account?.content).toContain(
			'@pytest.mark.parametrize("newStatus", ["FROZEN"])',
		);
		// The outside-set partition value is its own parametrized row.
		expect(account?.content).toContain(
			'@pytest.mark.parametrize("newStatus", ["INVALID"])',
		);
		expect(account?.content).toContain(
			"def test_AccountService_setStatus_partition_0(newStatus):",
		);
		// The body builds the dict from the named param (and keeps the throws
		// idiom for the reject partition row).
		expect(account?.content).toContain(
			'AccountService.setStatus({"newStatus": newStatus})',
		);
	});

	it("calls the component operation with the configured inputs (dict literal)", () => {
		const suite = planTestCases(makeContext());
		const files = emitSuite(suite, "pytest" as never);
		const account = files.find((file) =>
			file.path.endsWith("test_AccountService.py"),
		);
		expect(account).toBeDefined();

		expect(account?.content).toContain(
			'result = AccountService.withdraw({"amount": 10})',
		);
		expect(account?.content).toContain(
			'result = AccountService.withdraw({"amount": 55, "balance": 50})',
		);
		// The function name derives from the case id — never the case-id tail.
		expect(account?.content).not.toContain("withdraw.boundary-0(");
	});

	it("renders assert ... is None for the returns rejection idiom when configured (ADR-0007)", () => {
		const suite = planTestCases(makeContext("returns"));
		const files = emitSuite(suite, "pytest" as never);
		const account = files.find((file) =>
			file.path.endsWith("test_AccountService.py"),
		);
		expect(account).toBeDefined();
		const rejectCase = rejectCases(suite).find(
			(case_) => case_.inputs.amount === 9,
		);
		expect(rejectCase).toBeDefined();
		expect(rejectCase?.expects.rejectionIdiom).toBe("returns");
		expect(account?.content).toContain(
			'assert AccountService.withdraw({"amount": 9}) is None',
		);
		expect(account?.content).not.toContain("pytest.raises(");
	});

	it("renders real assert-based invariant assertions — never a bare pass (Center W2)", () => {
		const suite = planTestCases(makeContext());
		const files = emitSuite(suite, "pytest" as never);
		const account = files.find((file) =>
			file.path.endsWith("test_AccountService.py"),
		);
		expect(account).toBeDefined();
		const inv = suite.invariantCases.find(
			(case_) => case_.kind === "invariant",
		);
		expect(inv).toBeDefined();

		// Scope to the invariant case's own rendered function block.
		const start = account?.content.indexOf(
			"def test_AccountService_withdraw_invariant_0():",
		);
		expect(start).toBeGreaterThan(-1);
		const end = account?.content.indexOf("\n\n", start);
		const block = account?.content.slice(start, end);

		// The invariant's subject field is asserted with a real assert — a
		// degenerate `pass` (or bare accept) render would fail this.
		expect(block).toContain("assert result is not None");
		expect(block).toContain("assert result.balance >= 0");
		expect(block).not.toContain("pass");
	});
});

describe("emitSuite — framework dispatch and type widening (§9.4, ADR-0008/0009)", () => {
	it("dispatches xunit and pytest instead of throwing", () => {
		const suite = planTestCases(makeContext());
		const xunitFiles = emitSuite(suite, "xunit" as never);
		const pytestFiles = emitSuite(suite, "pytest" as never);

		expect(xunitFiles.length).toBeGreaterThan(0);
		expect(pytestFiles.length).toBeGreaterThan(0);
		for (const file of xunitFiles) {
			expect(file.path.endsWith(".Tests.cs")).toBe(true);
		}
		for (const file of pytestFiles) {
			expect(file.path.endsWith(".py")).toBe(true);
		}
	});

	it("widens the emitter framework type to the full v1 matrix (vitest | xunit | pytest)", () => {
		// The const above typechecks ONLY once EmitterFramework in
		// src/generator/ir.ts widens from "vitest" to the ADR-0009 matrix.
		expect(V1_EMITTER_FRAMEWORKS).toEqual(["vitest", "xunit", "pytest"]);
	});

	it("routes config.testFramework values through the seam to the matching emitter (generate.ts wiring)", () => {
		// src/cli/handlers/generate.ts passes context.config.testFramework
		// straight into emitSuite — the ADR-0009 config values must route to
		// the matching emitter with no CLI-side mapping.
		const config = makeConfig();
		config.testFramework = "xunit";
		const xunitFiles = emitSuite(
			planTestCases(makeContext()),
			config.testFramework as never,
		);
		expect(xunitFiles.some((file) => file.path.endsWith(".Tests.cs"))).toBe(
			true,
		);

		config.testFramework = "pytest";
		const pytestFiles = emitSuite(
			planTestCases(makeContext()),
			config.testFramework as never,
		);
		expect(
			pytestFiles.some((file) => file.path.endsWith("test_AccountService.py")),
		).toBe(true);
	});

	it("still throws for an unknown framework string at the seam", () => {
		const suite = planTestCases(makeContext());
		// The seam rejects unknown framework strings instead of silently
		// producing nothing (config.schema.json rejects them too).
		expect(() => emitSuite(suite, "jest" as never)).toThrow();
		expect(() => emitSuite(suite, "mocha" as never)).toThrow();
	});
});

describe("emitSuite — determinism for xunit and pytest (ADR-0002)", () => {
	it("same suite → byte-identical xunit output across two calls", () => {
		const suite = planTestCases(makeContext());

		const first = emitSuite(suite, "xunit" as never);
		const second = emitSuite(suite, "xunit" as never);
		expect(second).toEqual(first);
		expect(second.map((file) => file.content)).toEqual(
			first.map((file) => file.content),
		);
	});

	it("same suite → byte-identical pytest output across two calls", () => {
		const suite = planTestCases(makeContext());

		const first = emitSuite(suite, "pytest" as never);
		const second = emitSuite(suite, "pytest" as never);
		expect(second).toEqual(first);
		expect(second.map((file) => file.content)).toEqual(
			first.map((file) => file.content),
		);
	});

	it("property: same generated context → byte-identical xunit and pytest output (fast-check)", () => {
		fc.assert(
			fc.property(contextArb, (context) => {
				const suite = planTestCases(context);
				expect(emitSuite(suite, "xunit" as never)).toEqual(
					emitSuite(suite, "xunit" as never),
				);
				expect(emitSuite(suite, "pytest" as never)).toEqual(
					emitSuite(suite, "pytest" as never),
				);
			}),
			{ numRuns: 50 },
		);
	});
});

describe("emitSuite — identifier safety for xunit/pytest (Center W1)", () => {
	// A hostile name that would terminate a string/statement if it flowed raw
	// into an import, class name, method name, call, or file path.
	const HOSTILE = 'Evil";globalThis.PWNED=1;//';

	function hostileComponentSuite(component: string): PlannedSuite {
		return {
			clauseIds: [`${component}.inv0`],
			operations: [
				{
					component,
					operation: "withdraw",
					cases: [
						{
							id: `${component}.withdraw.boundary-0`,
							kind: "boundary",
							description: "boundary-1",
							inputs: { amount: 9 },
							expects: { outcome: "reject", rejectionIdiom: "throws" },
							traces: [`${component}.withdraw.pre0`],
						},
					],
				},
			],
			invariantCases: [],
		};
	}

	function hostileOperationSuite(operation: string): PlannedSuite {
		return {
			clauseIds: [`${ACCOUNT}.inv0`],
			operations: [
				{
					component: ACCOUNT,
					operation,
					cases: [
						{
							id: `${ACCOUNT}.${operation}.boundary-0`,
							kind: "boundary",
							description: "boundary-1",
							inputs: { amount: 9 },
							expects: { outcome: "reject", rejectionIdiom: "throws" },
							traces: [`${ACCOUNT}.${operation}.pre0`],
						},
					],
				},
			],
			invariantCases: [],
		};
	}

	/**
	 * Pins the emitter-level refusal: the emitter must throw on an unsafe
	 * identifier (mirror vitest's assertIdentifier) — and if that ever
	 * regresses, the returned files must be breakout-free: the hostile payload
	 * never reaches a file path or content.
	 */
	function assertRefuses(
		suite: PlannedSuite,
		framework: string,
		payload: string,
	): void {
		expect(() => emitSuite(suite, framework as never)).toThrow();
		let files: EmittedFile[] = [];
		try {
			files = emitSuite(suite, framework as never);
		} catch {
			return; // refused — nothing was emitted
		}
		for (const file of files) {
			expect(file.path).not.toContain(payload);
			expect(file.content).not.toContain(payload);
		}
	}

	it("xunit refuses a hostile component name — throws, never emits a breakout file", () => {
		assertRefuses(hostileComponentSuite(HOSTILE), "xunit", HOSTILE);
	});

	it("pytest refuses a hostile component name — throws, never emits a breakout file", () => {
		assertRefuses(hostileComponentSuite(HOSTILE), "pytest", HOSTILE);
	});

	it("xunit and pytest refuse a hostile operation name — throws, never emits a breakout file", () => {
		assertRefuses(hostileOperationSuite(HOSTILE), "xunit", HOSTILE);
		assertRefuses(hostileOperationSuite(HOSTILE), "pytest", HOSTILE);
	});
});

describe("emitSuite — output path and module path configuration (Center W4)", () => {
	it("xunit and pytest honor generatedDir and modulePaths options", () => {
		const suite = planTestCases(makeContext());

		const xunitFiles = emitSuite(suite, "xunit" as never, {
			generatedDir: "custom/generated",
			modulePaths: { AccountService: "MyApp.Services.Account" },
		});
		const account = xunitFiles.find((file) =>
			file.path.endsWith("AccountService.Tests.cs"),
		);
		expect(account).toBeDefined();
		expect(account?.path.startsWith("custom/generated/")).toBe(true);
		expect(account?.content).toContain("using MyApp.Services.Account;");
		expect(account?.content).not.toContain(
			"using Versailles.Components.AccountService;",
		);

		const pytestFiles = emitSuite(suite, "pytest" as never, {
			generatedDir: "custom/generated",
			modulePaths: { AccountService: "my_pkg.services" },
		});
		const accountPy = pytestFiles.find((file) =>
			file.path.endsWith("test_AccountService.py"),
		);
		expect(accountPy).toBeDefined();
		expect(accountPy?.path.startsWith("custom/generated/")).toBe(true);
		expect(accountPy?.content).toContain(
			"from my_pkg.services import AccountService",
		);
		expect(accountPy?.content).not.toContain(
			"from components.AccountService import AccountService",
		);
	});
});

// ── Center review W1/W2 regressions: pin the FIXED behavior (Red phase) ────
//
// W1 — sanitizeId collisions must never produce duplicate method/function
// names. Current: sanitizeId (src/generator/emitters/shared.ts) maps BOTH
// "Gen.check_out.boundary-0" and "Gen.check.out.boundary-0" →
// "Gen_check_out_boundary_0", so a suite carrying both ids renders duplicate
// `public void Gen_check_out_boundary_0()` methods (a C# compile error) and
// duplicate `def test_Gen_check_out_boundary_0():` functions (Python silent
// shadowing). FIXED: the emitters disambiguate — the first occurrence keeps
// the sanitized name; a later colliding id gets a deterministic numeric
// suffix — so every rendered method/function name is unique per file. The
// tests pin uniqueness + determinism (ADR-0002), not the exact suffix scheme.
//
// W2 — a zero-input accept case must render VALID C#. Current: an operation
// with zero inputs renders `var result = Gen.noop(new {  });` — an empty
// anonymous object literal is a C# compile error. FIXED: zero inputs render a
// zero-arg call `var result = Gen.noop();` (the emitter's call shape is always
// `<Component>.<operation>(<args>)`; no inputs means no arguments — `new Gen()`
// would invent a constructor invocation that does not match the method-call
// contract). pytest's zero-input dict literal `Gen.noop({})` is valid Python
// and needs no change — the W2 pin is xunit-only.

function collidingIdSuite(): PlannedSuite {
	return {
		clauseIds: ["Gen.check.pre0"],
		operations: [
			{
				component: "Gen",
				operation: "check",
				cases: [
					{
						id: "Gen.check_out.boundary-0",
						kind: "boundary",
						description: "collision A",
						inputs: { amount: 9 },
						expects: { outcome: "reject", rejectionIdiom: "throws" },
						traces: ["Gen.check.pre0"],
					},
				],
			},
			{
				component: "Gen",
				operation: "check",
				cases: [
					{
						id: "Gen.check.out.boundary-0",
						kind: "boundary",
						description: "collision B",
						inputs: { amount: 10 },
						expects: { outcome: "accept" },
						traces: ["Gen.check.pre0"],
					},
				],
			},
		],
		invariantCases: [],
	};
}

function zeroInputSuite(): PlannedSuite {
	return {
		clauseIds: ["Gen.noop.inv0"],
		operations: [
			{
				component: "Gen",
				operation: "noop",
				cases: [
					{
						id: "Gen.noop.boundary-0",
						kind: "boundary",
						description: "zero-input accept",
						inputs: {},
						expects: { outcome: "accept" },
						traces: ["Gen.noop.inv0"],
					},
				],
			},
		],
		invariantCases: [],
	};
}

describe("emitSuite — case-id sanitization collisions never duplicate method/function names (Center W1)", () => {
	it("xunit renders two DISTINCT method names for ids that sanitize to the same identifier — no duplicate public void lines", () => {
		const suite = collidingIdSuite();

		const first = emitSuite(suite, "xunit");
		const second = emitSuite(suite, "xunit");
		const gen = first.find((file) => file.path.endsWith("Gen.Tests.cs"));
		expect(gen).toBeDefined();

		// Every rendered method name is unique — the disambiguated second id
		// must differ from the first (today both are Gen_check_out_boundary_0).
		const methodNames = [
			...(gen?.content.matchAll(/public void (\w+)\(\)/g) ?? []),
		].map((match) => match[1]);
		expect(methodNames).toHaveLength(2);
		expect(new Set(methodNames).size).toBe(2);
		// The first occurrence keeps the base sanitized name (deterministic
		// disambiguation — later collisions get a numeric suffix).
		expect(methodNames[0]).toBe("Gen_check_out_boundary_0");

		// Disambiguation is deterministic (ADR-0002): two runs byte-identical.
		expect(second.map((file) => file.content)).toEqual(
			first.map((file) => file.content),
		);
	});

	it("pytest renders two DISTINCT def test_* function names for colliding ids — no silent shadowing", () => {
		const files = emitSuite(collidingIdSuite(), "pytest");
		const gen = files.find((file) => file.path.endsWith("test_Gen.py"));
		expect(gen).toBeDefined();

		const fnNames = [...(gen?.content.matchAll(/def (test_\w+)\(/g) ?? [])].map(
			(match) => match[1],
		);
		expect(fnNames).toHaveLength(2);
		expect(new Set(fnNames).size).toBe(2);
	});
});

describe("emitSuite — zero-input accept cases render valid xUnit (Center W2)", () => {
	it("a zero-input accept case emits `var result = Gen.noop();` — never an empty anonymous object literal", () => {
		const files = emitSuite(zeroInputSuite(), "xunit");
		const gen = files.find((file) => file.path.endsWith("Gen.Tests.cs"));
		expect(gen).toBeDefined();

		// The zero-arg call is valid C# — `new {  }` is a compile error.
		expect(gen?.content).toContain("var result = Gen.noop();");
		expect(gen?.content).not.toMatch(/new\s*\{\s*\}/);
	});
});

// ── Property-test fixture (determinism across generated contexts) ──────────

const COMPARE_OPS = fc.constantFrom(">=", ">", "<=", "<");
const BOUNDARY = fc.integer({ min: 0, max: 50 });
const MEMBERS = fc.uniqueArray(fc.constantFrom("A", "B", "C"), {
	minLength: 1,
	maxLength: 3,
});

function parseAst(
	expr: string,
	kind: "preconditions" | "postconditions" | "invariants",
	id: string,
): Node {
	const result = parseExpression(expr, kind, id);
	if (!result.ok) {
		throw new Error(
			`fixture parse failed for "${expr}": ${JSON.stringify(result.errors)}`,
		);
	}
	return result.ast;
}

/**
 * Builds a random but structurally valid, fully-loaded VersaillesContext
 * (isValid: true) whose withdraw operation carries two random numeric
 * comparison preconditions and one random in-clause precondition.
 */
function makeGeneratedContext(
	pre0: string,
	pre1: string,
	pre2: string,
): VersaillesContext {
	return {
		config: {
			grammarVersion: "1.0",
			schemaVersion: "1.0",
			sourceRoots: ["src/**/*.ts"],
			language: "typescript",
			testFramework: "vitest",
			generatedDir: ".versailles/generated",
			staleness: { blockOnStale: false },
		},
		contracts: {
			version: "1.0",
			contracts: {
				Gen: {
					invariants: [{ id: "Gen.inv0", expr: "balance >= 0" }],
					operations: {
						withdraw: {
							id: "Gen.withdraw",
							params: [
								{ name: "amount", type: "number" },
								{ name: "status", type: "string" },
							],
							preconditions: [
								{ id: "Gen.withdraw.pre0", expr: pre0 },
								{ id: "Gen.withdraw.pre1", expr: pre1 },
								{ id: "Gen.withdraw.pre2", expr: pre2 },
							],
							postconditions: [
								{
									id: "Gen.withdraw.post0",
									expr: "old(balance) - amount == balance",
								},
								{
									id: "Gen.withdraw.post1",
									expr: "old(balance) >= balance",
								},
							],
							effects: [{ field: "balance", kind: "mutate" }],
							sourceHash: "gen-hash",
						},
					},
				},
			},
		},
		manifests: {
			version: "1.0",
			manifests: {
				Gen: { sourceHash: "man-gen", fields: { balance: "number" } },
			},
		},
		predicates: { version: "1.0", predicates: {} },
		parsedContracts: {
			"Gen.withdraw.pre0": parseAst(pre0, "preconditions", "Gen.withdraw.pre0"),
			"Gen.withdraw.pre1": parseAst(pre1, "preconditions", "Gen.withdraw.pre1"),
			"Gen.withdraw.pre2": parseAst(pre2, "preconditions", "Gen.withdraw.pre2"),
			"Gen.withdraw.post0": parseAst(
				"old(balance) - amount == balance",
				"postconditions",
				"Gen.withdraw.post0",
			),
			"Gen.withdraw.post1": parseAst(
				"old(balance) >= balance",
				"postconditions",
				"Gen.withdraw.post1",
			),
			"Gen.inv0": parseAst("balance >= 0", "invariants", "Gen.inv0"),
		},
		parseErrors: [],
		validationErrors: [],
		validationWarnings: [],
		isValid: true,
	};
}

const contextArb: fc.Arbitrary<VersaillesContext> = fc
	.tuple(COMPARE_OPS, BOUNDARY, COMPARE_OPS, BOUNDARY, MEMBERS)
	.map(([op0, boundary0, op1, boundary1, members]) =>
		makeGeneratedContext(
			`amount ${op0} ${boundary0}`,
			`amount ${op1} ${boundary1}`,
			`status in [${members.map((member) => `"${member}"`).join(", ")}]`,
		),
	);

// ── Shape-aware vitest calls from manifest method metadata (VERSAILLES-20 F1) ─
//
// The vitest emitter always renders `Component.operation({...inputs})` — a
// static call with an options-object — which breaks against the most common TS
// shape: instance methods with positional params (e.g. `class Order {
// addItem(sku: string): void }` → `Order.addItem({ sku: "" })` →
// TypeError: Order.addItem is not a function). Void-returning operations also
// get a failing `expect(result).toBeDefined()`.
//
// FIXED (deterministic-generation.contract.yaml 2026-08-17, build-spec §9.4):
// emitters render calls from manifest method metadata — instance → `new
// <Component>().<op>(...positional params)`, static → `<Component>.<op>(...
// positional params)`, params in declared order, and void-return accept cases
// carry NO return-value assertion.
//
// The metadata seam is the emitSuite options object (mirroring the existing
// modulePaths option — both are per-component overrides threaded through the
// emitter seam; the planner/emitter boundary stays the framework-agnostic IR):
//
//   emitSuite(suite, "vitest", {
//     methods: { Order: { addItem: { static: false, params: ["sku"], returnType: "void" } } },
//   })
//
// The option is OPTIONAL: with no methods metadata the emitter keeps today's
// legacy options-object static call (backward compatible — existing pins in
// tests/generator.test.ts and the E test below stay green).

function singleOperationSuite(
	component: string,
	operation: string,
	cases: PlannedCase[],
): PlannedSuite {
	return {
		clauseIds: cases.flatMap((case_) => case_.traces),
		operations: [{ component, operation, cases }],
		invariantCases: [],
	};
}

/** The Phase 1 failure: `class Order { addItem(sku: string): void }`. */
function orderSuite(): PlannedSuite {
	return singleOperationSuite("Order", "addItem", [
		{
			id: "Order.addItem.boundary-0",
			kind: "boundary",
			description: "accept with a sku",
			inputs: { sku: "ABC" },
			expects: { outcome: "accept" },
			traces: ["Order.addItem.pre0"],
		},
		{
			id: "Order.addItem.boundary-1",
			kind: "boundary",
			description: "reject with an empty sku",
			inputs: { sku: "" },
			expects: { outcome: "reject", rejectionIdiom: "throws" },
			traces: ["Order.addItem.pre0"],
		},
	]);
}

const ORDER_METHODS = {
	Order: {
		addItem: { static: false, params: ["sku"], returnType: "void" },
	},
};

describe("emitSuite — shape-aware vitest calls from method metadata (VERSAILLES-20 F1, §9.4)", () => {
	it("renders an instance method as new Order().addItem(...) — positional params, never Order.addItem({ sku: ... })", () => {
		const files = emitSuite(orderSuite(), "vitest", {
			methods: ORDER_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// The accept case constructs the instance and passes the param
		// positionally — the exact Phase 1 failure shape.
		expect(order?.content).toContain('new Order().addItem("ABC")');
		// No static call on the instance method, for accept OR reject cases.
		expect(order?.content).not.toContain("Order.addItem(");
		// No options-object argument — positional params only.
		expect(order?.content).not.toContain('{ sku: "ABC" }');
		// Reject cases render the same shape-aware call inside the idiom.
		expect(order?.content).toContain(
			'expect(() => new Order().addItem("")).toThrow()',
		);
	});

	it("renders a static method as Component.op(...) with positional params — never an options object", () => {
		const suite = singleOperationSuite("Order", "staticOp", [
			{
				id: "Order.staticOp.boundary-0",
				kind: "boundary",
				description: "static accept",
				inputs: { n: 2 },
				expects: { outcome: "accept" },
				traces: ["Order.staticOp.pre0"],
			},
		]);
		const files = emitSuite(suite, "vitest", {
			methods: {
				Order: {
					staticOp: { static: true, params: ["n"], returnType: "number" },
				},
			},
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		expect(order?.content).toContain("Order.staticOp(2)");
		expect(order?.content).not.toContain("Order.staticOp({");
		expect(order?.content).not.toContain("{ n: 2 }");
	});

	it("passes params positionally in the DECLARED order, not the inputs-object order", () => {
		// The inputs object is deliberately reversed relative to the declared
		// params, so only metadata-driven ordering can render this call.
		const suite = singleOperationSuite("Cart", "setSubtotal", [
			{
				id: "Cart.setSubtotal.boundary-0",
				kind: "boundary",
				description: "accept with amount and label",
				inputs: { label: "gross", amount: 5 },
				expects: { outcome: "accept" },
				traces: ["Cart.setSubtotal.pre0"],
			},
		]);
		const files = emitSuite(suite, "vitest", {
			methods: {
				Cart: {
					setSubtotal: {
						static: false,
						params: ["amount", "label"],
						returnType: "number",
					},
				},
			},
		});
		const cart = files.find((file) => file.path.endsWith("Cart.test.ts"));
		expect(cart).toBeDefined();

		expect(cart?.content).toContain('new Cart().setSubtotal(5, "gross")');
		expect(cart?.content).not.toContain('new Cart().setSubtotal("gross", 5)');
		expect(cart?.content).not.toContain("setSubtotal({");
	});

	it("passes only the declared params — captured pre-call state never leaks into the call", () => {
		// Postcondition/invariant cases carry captured pre-state fields (e.g.
		// balance) inside inputs alongside the params; the call must take the
		// declared params only (metadata params: ["amount"]).
		const suite = singleOperationSuite("Ledger", "withdraw", [
			{
				id: "Ledger.withdraw.postcondition-satisfaction-0",
				kind: "postcondition-satisfaction",
				description: "accept with captured pre-state",
				inputs: { amount: 55, balance: 50 },
				expects: { outcome: "accept" },
				traces: ["Ledger.withdraw.post0"],
			},
		]);
		const files = emitSuite(suite, "vitest", {
			methods: {
				Ledger: {
					withdraw: {
						static: false,
						params: ["amount"],
						returnType: "number",
					},
				},
			},
		});
		const ledger = files.find((file) => file.path.endsWith("Ledger.test.ts"));
		expect(ledger).toBeDefined();

		expect(ledger?.content).toContain("new Ledger().withdraw(55)");
		// balance is pre-state, not a param — it must never appear as an arg.
		expect(ledger?.content).not.toContain("new Ledger().withdraw(55, 50)");
		// Non-void accept cases still assert the result (only void skips it).
		expect(ledger?.content).toContain("expect(result).toBeDefined()");
	});

	it("renders a void accept case WITHOUT a return-value assertion", () => {
		const files = emitSuite(orderSuite(), "vitest", {
			methods: ORDER_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// addItem returns void — the accept case must call it without
		// `expect(result).toBeDefined()` (which fails on undefined).
		expect(order?.content).not.toContain("expect(result)");
		// The call itself is still emitted (the accept case is not empty).
		expect(order?.content).toContain('new Order().addItem("ABC")');
	});

	it("keeps the legacy options-object static call when NO methods metadata is present (backward compatible)", () => {
		// No `methods` option → today's behavior stays: static component call
		// with an options-object and a toBeDefined assertion. Existing pins
		// (tests/generator.test.ts vitest describes) depend on this default.
		const files = emitSuite(orderSuite(), "vitest");
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		expect(order?.content).toContain('Order.addItem({ sku: "ABC" })');
		expect(order?.content).toContain("expect(result).toBeDefined()");
	});
});

// ── VERSAILLES-26: void-op accept/invariant cases assert INSTANCE state ─────
//
// E2E-gate finding: an invariant case on a void-returning operation renders
// `const result = new Order().addItem("initial"); expect(result.subtotal)...` —
// addItem returns void, so `result` is undefined at runtime → TypeError:
// Cannot read properties of undefined (reading 'subtotal'). The F1 voidAccept
// branch (src/generator/emitters/vitest.ts) correctly drops toBeDefined() for
// void accept cases WITHOUT assertions, but a void accept case WITH assertions
// (invariant cases) still binds `const result = ${call}` and renders
// `result.<field>` assertions on the void return value.
//
// FIXED (deterministic-generation.contract.yaml 2026-08-18, build-spec §9.4,
// VERSAILLES-26): accept/invariant cases on void-returning operations bind the
// component INSTANCE — `const instance = new <Component>(); instance.<op>(...);
// expect(instance.<field>)...` — never the void return value.

/** An invariant PlannedCase on a VOID-returning operation (subject: subtotal). */
function voidInvariantSuite(): PlannedSuite {
	return {
		clauseIds: ["Order.inv0"],
		operations: [],
		invariantCases: [
			{
				id: "Order.addItem.invariant-0",
				kind: "invariant",
				description:
					"call Order.addItem and assert invariant Order.inv0 still holds",
				inputs: { sku: "initial" },
				expects: {
					outcome: "accept",
					postconditions: ["Order.inv0"],
					assertions: [{ subject: "subtotal", op: ">=", literal: 0 }],
				},
				traces: ["Order.inv0"],
			},
		],
	};
}

const ORDER_VOID_METHODS = {
	Order: {
		addItem: { static: false, params: ["sku"], returnType: "void" },
	},
};

const ORDER_NONVOID_METHODS = {
	Order: {
		addItem: { static: false, params: ["sku"], returnType: "number" },
	},
};

describe("emitSuite — void-op accept/invariant cases assert INSTANCE state, never the void return value (VERSAILLES-26, §9.4)", () => {
	it("binds the INSTANCE and asserts instance.<field> for a void op's invariant case — never const result / result.<field>", () => {
		const files = emitSuite(voidInvariantSuite(), "vitest", {
			methods: ORDER_VOID_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// The void call is NOT bound to a result — the case binds the
		// component instance, calls the op on it, and asserts instance state
		// (subtotal is a component FIELD, not a return value).
		expect(order?.content).toContain("const instance = new Order();");
		expect(order?.content).toContain('instance.addItem("initial");');
		expect(order?.content).toContain(
			"expect(instance.subtotal).toBeGreaterThanOrEqual(0)",
		);

		// The runtime TypeError shape is forbidden on the void case.
		expect(order?.content).not.toContain("const result =");
		expect(order?.content).not.toContain("result.subtotal");
		expect(order?.content).not.toContain("expect(result)");
	});

	it("keeps const result = ...; expect(result).toBeDefined(); expect(result.<field>) for a NON-void op's invariant case — no regression", () => {
		const files = emitSuite(voidInvariantSuite(), "vitest", {
			methods: ORDER_NONVOID_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// returnType "number" — the return value is the assertion receiver.
		expect(order?.content).toContain(
			'const result = new Order().addItem("initial");',
		);
		expect(order?.content).toContain("expect(result).toBeDefined();");
		expect(order?.content).toContain(
			"expect(result.subtotal).toBeGreaterThanOrEqual(0)",
		);
		// The instance-binding form is void-only — a non-void op never uses it.
		expect(order?.content).not.toContain("const instance =");
		expect(order?.content).not.toContain("instance.addItem(");
	});

	it("keeps the bare call for a void op accept case WITHOUT assertions — no const result binding (F1 pin)", () => {
		const files = emitSuite(orderSuite(), "vitest", {
			methods: ORDER_VOID_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// The accept case (boundary-0, no assertions) stays a bare call.
		expect(order?.content).toContain('new Order().addItem("ABC");');
		expect(order?.content).not.toContain("const result =");
		expect(order?.content).not.toContain("expect(result)");
	});

	it("renders the configured rejection idiom wrapper for a void op's reject case — no result binding (guard)", () => {
		const files = emitSuite(orderSuite(), "vitest", {
			methods: ORDER_VOID_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// Reject cases on a void op stay the idiom around the shape-aware call.
		expect(order?.content).toContain(
			'expect(() => new Order().addItem("")).toThrow()',
		);
		// No result binding anywhere on the reject side.
		expect(order?.content).not.toContain("const result =");
		expect(order?.content).not.toContain("expect(result)");
	});

	it("keeps the legacy options-object static call with toBeDefined for an invariant case when NO methods metadata is present (backward compatible)", () => {
		const files = emitSuite(voidInvariantSuite(), "vitest");
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// No methods metadata → the historical render stays byte-identical:
		// static options-object call + toBeDefined + result.<field> assertion.
		expect(order?.content).toContain('Order.addItem({ sku: "initial" })');
		expect(order?.content).toContain("expect(result).toBeDefined();");
		expect(order?.content).toContain(
			"expect(result.subtotal).toBeGreaterThanOrEqual(0)",
		);
		// The instance-binding form is metadata-driven only — never the legacy
		// default (a legacy void op must NOT silently change shape).
		expect(order?.content).not.toContain("const instance =");
		expect(order?.content).not.toContain("instance.addItem(");
	});
});

// ── VERSAILLES-146: a postcondition-satisfaction case WITH assertions on a
// void INSTANCE op renders the instance binding + real matcher ───────────────
//
// V-146 root cause is the PLANNER: planTestCases sets
// `expects: { outcome: "accept", postconditions: postIds }` for the
// postcondition-satisfaction case but never `expects.assertions`, so the
// emitter renders a bare `new <Component>().<op>(...)` call with NO assertion.
// The FIXED planner must derive renderable AssertionDescriptors from the
// postconditions (resolving old(field) + arithmetic against the captured
// pre-state and valid params). The emitter side ALREADY renders real matchers
// for void instance ops with assertions (the V-26 branch at vitest.ts
// L239-254) — this pin freezes that contract so the fix cannot regress it: a
// postcondition-satisfaction case carrying assertions must render
// `const instance = new <Component>(); instance.<op>(...);
// expect(instance.<field>).toEqual(...)` — never a bare call, never a
// `const result` binding on a void return value.

/** A postcondition-satisfaction PlannedCase WITH assertions on a VOID instance op. */
function voidPostconditionSuite(): PlannedSuite {
	return {
		clauseIds: ["Order.addItem.post0"],
		operations: [
			{
				component: "Order",
				operation: "addItem",
				cases: [
					{
						id: "Order.addItem.postcondition-satisfaction-0",
						kind: "postcondition-satisfaction",
						description:
							"valid input asserting postconditions Order.addItem.post0",
						inputs: { sku: "initial", price: 1, balance: 50 },
						expects: {
							outcome: "accept",
							postconditions: ["Order.addItem.post0"],
							// The V-146 planner output: old(balance) + price
							// resolved against the captured pre-state (50) and
							// the valid param (1) → literal 51.
							assertions: [{ subject: "balance", op: "==", literal: 51 }],
						},
						traces: ["Order.addItem.post0"],
					},
				],
			},
		],
		invariantCases: [],
	};
}

const ORDER_VOID_POSTCONDITION_METHODS = {
	Order: {
		addItem: { static: false, params: ["sku", "price"], returnType: "void" },
	},
};

describe("emitSuite — a postcondition-satisfaction case WITH assertions on a void INSTANCE op renders the instance binding + real matcher (VERSAILLES-146, §9.4)", () => {
	it("binds the INSTANCE, calls the op on it, and asserts instance.<field> with a real matcher — never a bare call, never result.<field> on a void return", () => {
		const files = emitSuite(voidPostconditionSuite(), "vitest", {
			methods: ORDER_VOID_POSTCONDITION_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// The V-26 void-with-assertions render — the V-146 fix's target shape:
		// const instance = new Order(); instance.addItem("initial", 1);
		// expect(instance.balance).toEqual(51). The bare-call render
		// (`new Order().addItem("initial", 1);` — today's V-146 output) has
		// NO assertion and must never be emitted for a case WITH assertions.
		expect(order?.content).toContain("const instance = new Order();");
		expect(order?.content).toContain('instance.addItem("initial", 1);');
		expect(order?.content).toContain("expect(instance.balance).toEqual(51)");

		// A void call's return value is undefined — result.<field> would throw
		// TypeError at runtime; the void-with-assertions path must not bind it.
		expect(order?.content).not.toContain("const result =");
		expect(order?.content).not.toContain("result.balance");
		expect(order?.content).not.toContain("expect(result)");
	});
});

/** Real Order source for the V-26 E2E runnability pin — addItem mutates state and returns void. */
const V26_ORDER_SOURCE = `export class Order {
	subtotal = 0;
	addItem(sku: string): void {
		this.subtotal = sku.length * 10;
	}
}
`;

describe("emitSuite — a generated suite for a void-op invariant case RUNS (VERSAILLES-26 E2E runnability gate)", () => {
	it("executes the emitted void-op invariant test with bun's test runner — no TypeError on the void return value", async () => {
		const root = await mkdtemp(join(tmpdir(), "versailles-v26-"));
		try {
			await writeFile(join(root, "order.ts"), `${V26_ORDER_SOURCE}\n`, "utf8");

			const files = emitSuite(voidInvariantSuite(), "vitest", {
				generatedDir: ".",
				modulePaths: { Order: "./order" },
				methods: ORDER_VOID_METHODS,
			});
			const order = files.find((file) => file.path.endsWith("Order.test.ts"));
			expect(order).toBeDefined();
			await writeFile(
				join(root, "Order.test.ts"),
				order?.content ?? "",
				"utf8",
			);

			// Run the generated suite with bun's test runner (which intercepts
			// the vitest import). Today the emitted `const result = new
			// Order().addItem(...); expect(result.subtotal)...` throws
			// TypeError: undefined is not an object — the E2E-gate finding —
			// so the run exits 1 (Red). The FIXED instance-bound render must
			// exit 0.
			const run = spawnSync("bun", ["test", "Order.test.ts"], {
				cwd: root,
				encoding: "utf8",
			});
			expect(
				run.status,
				`generated void-op invariant suite did not run clean:\n${run.stdout}\n${run.stderr}`,
			).toBe(0);
		} finally {
			await rm(root, { recursive: true, force: true });
		}
	});
});

// ── W1 (Center review finding): STATIC void ops with assertions must NOT
// bind an instance or assert instance.<field> ───────────────────────────────
// deterministic-generation.contract.yaml (2026-08-18) extends the V-26
// instance-binding carve-out with the static variant: a STATIC void-returning
// operation has no instance state to assert — `new <Component>()` is a
// completely different object that the static call never touches. The FIXED
// render is the bare static call `<Component>.<op>(...);` with NO instance
// binding and NO instance.<field> assertion. Today the emitter binds the
// instance anyway (the misleading `const instance = new Order();` +
// `expect(instance.subtotal)...` shape) — a false-green/false-red test whose
// assertion is silently meaningless.
//
// Non-void static ops are untouched by this carve-out: their return value is
// the assertion receiver (const result + toBeDefined + result.<field>), and
// instance void ops keep the V-26 instance-bound render (pinned above).

/** An invariant PlannedCase on a STATIC VOID-returning operation (subject: subtotal). */
function staticVoidInvariantSuite(): PlannedSuite {
	return {
		clauseIds: ["Order.inv0"],
		operations: [],
		invariantCases: [
			{
				id: "Order.reset.invariant-0",
				kind: "invariant",
				description:
					"call Order.reset and assert invariant Order.inv0 still holds",
				inputs: {},
				expects: {
					outcome: "accept",
					postconditions: ["Order.inv0"],
					assertions: [{ subject: "subtotal", op: ">=", literal: 0 }],
				},
				traces: ["Order.inv0"],
			},
		],
	};
}

const ORDER_STATIC_VOID_METHODS = {
	Order: {
		reset: { static: true, params: [], returnType: "void" },
	},
};

const ORDER_STATIC_NONVOID_METHODS = {
	Order: {
		reset: { static: true, params: [], returnType: "number" },
	},
};

describe("emitSuite — STATIC void-op invariant cases emit the bare static call, never an instance assertion (W1, deterministic-generation.contract.yaml)", () => {
	it("emits ONLY the bare static call for a static void op's invariant case — no const instance binding, no expect(instance.<field>) (Red today: binds the instance and asserts instance.subtotal)", () => {
		const files = emitSuite(staticVoidInvariantSuite(), "vitest", {
			methods: ORDER_STATIC_VOID_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// THE fix: the static void call is emitted bare — a static call has
		// no instance state to assert, so no `const instance = new Order();`
		// and no `expect(instance.<field>)` in the emitted surface.
		expect(order?.content).toContain("Order.reset();");
		expect(order?.content).not.toContain("const instance = new Order();");
		expect(order?.content).not.toContain("expect(instance.subtotal)");
		expect(order?.content).not.toContain("const result =");
	});

	it("keeps the result-bound render for a STATIC NON-void op's invariant case — const result + toBeDefined + result.<field>, never an instance binding (non-regression)", () => {
		const files = emitSuite(staticVoidInvariantSuite(), "vitest", {
			methods: ORDER_STATIC_NONVOID_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// returnType "number" — the return value is the assertion receiver,
		// exactly like the instance non-void pin (V-26): const result, then
		// toBeDefined, then result.<field>. The static call shape stays.
		expect(order?.content).toContain("const result = Order.reset();");
		expect(order?.content).toContain("expect(result).toBeDefined();");
		expect(order?.content).toContain(
			"expect(result.subtotal).toBeGreaterThanOrEqual(0)",
		);
		// The instance-binding form is void-only — a non-void op never uses it.
		expect(order?.content).not.toContain("const instance =");
		expect(order?.content).not.toContain("instance.reset(");
	});
});

/**
 * Real Order source for the W1 E2E runnability pin. subtotal starts at -5 —
 * DELIBERATELY violating the "subtotal >= 0" invariant on a fresh instance.
 * The current misleading render (`const instance = new Order(); Order.reset();
 * expect(instance.subtotal)...`) FAILS at runtime: the fresh instance's
 * subtotal (-5) is untouched by the static call, so the assertion is a false
 * red. The FIXED bare-call render (`Order.reset();`) asserts nothing about a
 * fresh instance and runs green.
 */
const W1_ORDER_SOURCE = `export class Order {
	subtotal = -5;
	static reset(): void {
		// Static/global reset — never touches a particular instance.
	}
}
`;

describe("emitSuite — a generated STATIC void-op invariant suite RUNS (W1 E2E runnability gate)", () => {
	it("executes the emitted static void-op invariant test with the REAL vitest runner — exit 0 (Red today: the misleading instance assertion fails on a fresh instance)", async () => {
		const root = await mkdtemp(join(tmpdir(), "versailles-w1-"));
		try {
			await writeFile(join(root, "order.ts"), `${W1_ORDER_SOURCE}\n`, "utf8");

			const files = emitSuite(staticVoidInvariantSuite(), "vitest", {
				generatedDir: ".",
				modulePaths: { Order: "./order" },
				methods: ORDER_STATIC_VOID_METHODS,
			});
			const order = files.find((file) => file.path.endsWith("Order.test.ts"));
			expect(order).toBeDefined();
			await writeFile(
				join(root, "Order.test.ts"),
				order?.content ?? "",
				"utf8",
			);

			// The REAL vitest runner (vitest.mjs under process.execPath) —
			// the established V-27 command. Today the emitted
			// `expect(instance.subtotal).toBeGreaterThanOrEqual(0)` fails
			// (-5 >= 0 is false) → exit 1 (Red). The FIXED bare static call
			// must exit 0.
			const vitestBin = join(
				dirname(fileURLToPath(import.meta.url)),
				"..",
				"node_modules",
				"vitest",
				"vitest.mjs",
			);
			const run = spawnSync(process.execPath, [vitestBin, "run"], {
				cwd: root,
				encoding: "utf8",
			});
			expect(
				run.status,
				`generated static void-op invariant suite did not run clean:\n${run.stdout}\n${run.stderr}`,
			).toBe(0);
		} finally {
			await rm(root, { recursive: true, force: true });
		}
	});
});

/**
 * VERSAILLES-24 module-path resolvability (deterministic-generation.contract.yaml
 * §9.4, build-spec §9.4): an emitted import specifier derived from a manifest
 * sourcePath must RESOLVE to the real source file from the generated file's
 * directory — not merely share an extension or suffix. The deriveModulePaths
 * seam (src/cli/handlers/generate.ts) computes
 * relative(<root>/<generatedDir>, join(<root>, sourcePath)); this test mirrors
 * that logic against a REAL nested temp-dir layout and proves the specifier
 * resolves to the file that exists on disk. The sourcePath comes from the REAL
 * extractor — the buggy side pre-fix (source-root-relative "models/order.ts"
 * instead of project-root-relative "src/models/order.ts") — so the
 * resolvability assertion is Red today: the derived specifier
 * "../../order.ts" resolves to <root>/order.ts, which does not exist.
 */

// Real nested source layout: <root>/src/models/order.ts (project root = root;
// source root = root/src, the directory the "src/**/*.ts" glob expands to).
const V24_ORDER_SOURCE = `export class Order {
	id: number;
	items: OrderItem[];
}

export class OrderItem {
	sku: string;
	qty: number;
}
`;

describe("emitSuite — module paths derived from project-root-relative sourcePath resolve to real files (VERSAILLES-24)", () => {
	it("derives a specifier via the deriveModulePaths seam that resolves to the REAL nested source file on disk", async () => {
		const root = await mkdtemp(join(tmpdir(), "versailles-v24-"));
		try {
			await mkdir(join(root, "src", "models"), { recursive: true });
			const sourceFile = join(root, "src", "models", "order.ts");
			await writeFile(sourceFile, `${V24_ORDER_SOURCE}\n`, "utf8");

			// Real extraction with the project root: a covered entry's
			// sourcePath must be project-root-relative ("src/models/order.ts"),
			// never source-root-relative ("models/order.ts") — Red today.
			const { manifests } = extractManifests([join(root, "src")], root);
			expect(manifests.Order.sourcePath).toBe("src/models/order.ts");

			// Mirror deriveModulePaths (src/cli/handlers/generate.ts): the
			// specifier is node:path relative from <root>/<generatedDir> to
			// join(<root>, sourcePath), POSIX separators, explicit ./ prefix
			// when the target is not in a parent directory.
			const generatedDir = ".versailles/generated";
			const from = join(root, generatedDir);
			const to = join(root, manifests.Order.sourcePath);
			let specifier = relative(from, to).split(sep).join("/");
			if (!specifier.startsWith(".")) specifier = `./${specifier}`;

			// POSIX separators on any platform (C).
			expect(specifier).not.toContain("\\");

			// Emit via the modulePaths seam (mirrors generate's emitSuite
			// options) and assert the specifier appears in the import line.
			const files = emitSuite(orderSuite(), "vitest", {
				generatedDir,
				modulePaths: { Order: specifier },
			});
			const order = files.find(
				(file) => file.path === `${generatedDir}/Order.test.ts`,
			);
			expect(order).toBeDefined();
			expect(order?.content).toContain(`import { Order } from "${specifier}";`);

			// RESOLVABILITY: resolve the emitted specifier against the
			// generated file's directory — the result must be the real source
			// file that exists on disk. With today's source-root-relative
			// sourcePath the specifier is "../../order.ts" and resolves to
			// <root>/order.ts, which does not exist — Red.
			const generatedFile = join(root, `${generatedDir}/Order.test.ts`);
			const resolved = resolve(dirname(generatedFile), specifier);
			expect(resolved).toBe(sourceFile);
			expect(existsSync(resolved)).toBe(true);
		} finally {
			await rm(root, { recursive: true, force: true });
		}
	});
});

// ── VERSAILLES-27: an operation group with ZERO planned cases emits NO describe ─
//
// E2E re-run finding: the V-25 skip path (UNPLANNABLE_OPERATION) keeps the
// warned operation's group in the suite with an EMPTY cases array (planner.ts
// keeps the group so the component file still renders and the coverage gap
// stays mapped in coverage.json), but the vitest emitter renders
// `describe("<op>", () => { });` UNCONDITIONALLY for every operation group —
// an empty suite. Vitest 3.2.7 (and 4.1.10) hard-fails empty describes:
// `Error: No test found in suite setSubtotal` → the whole file fails, exit 1.
// All other cases pass; only the empty describe fails the file.
//
// FIXED (deterministic-generation.contract.yaml 2026-08-18, build-spec §9.4,
// VERSAILLES-27): the emitter emits NO describe block for an operation whose
// planned case list is empty — the operation is fully skipped by the planner,
// so an empty suite is never rendered (the trace header already records the
// operation's clause ids, §9.3). Sibling operations WITH cases render
// byte-identically (D), and the invariant describe stays guarded on
// `length > 0` exactly as today (B).

const V27_EMPTY_OP = "setSubtotal";
const V27_SIBLING_OP = "setTotal";

/**
 * A V-25-shaped suite at the emitter seam: the skipped operation's group
 * survives planning with ZERO cases (planner.ts keeps the group), alongside a
 * sibling operation with a real case. Mirror of the methodsMissingOpFixture
 * suite in tests/generator-unplannable-operation.test.ts (which pins the
 * PLANNED side — this fixture pins the EMITTED side).
 */
function emptyOperationGroupSuite(): PlannedSuite {
	return {
		clauseIds: [`Order.${V27_EMPTY_OP}.pre0`, `Order.${V27_SIBLING_OP}.pre0`],
		operations: [
			{ component: "Order", operation: V27_EMPTY_OP, cases: [] },
			{
				component: "Order",
				operation: V27_SIBLING_OP,
				cases: [
					{
						id: `Order.${V27_SIBLING_OP}.boundary-0`,
						kind: "boundary",
						description: "accept with an amount",
						inputs: { amount: 25 },
						expects: { outcome: "accept" },
						traces: [`Order.${V27_SIBLING_OP}.pre0`],
					},
				],
			},
		],
		invariantCases: [],
	};
}

/** Method metadata for the sibling op only — the skipped op has no source method (V-25). */
const V27_METHODS = {
	Order: {
		setTotal: { static: false, params: ["amount"], returnType: "number" },
	},
};

describe("emitSuite — an operation group with ZERO planned cases emits NO describe block for it (VERSAILLES-27, §9.1)", () => {
	it('emits NO describe block for the empty-case operation — no empty suite, no it.skip placeholder (Red today: the emitter renders describe("setSubtotal", () => {});)', () => {
		const files = emitSuite(emptyOperationGroupSuite(), "vitest", {
			methods: V27_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// THE fix: the skipped operation leaves NO describe in the file — the
		// planner fully skipped it, so an empty suite is never rendered.
		expect(order?.content).not.toContain('describe("setSubtotal", () => {');
		// The pinned form is NO describe block (not the it.skip alternative):
		// the skipped operation contributes NOTHING to the emitted surface.
		expect(order?.content).not.toContain("it.skip(");

		// The sibling operation WITH cases still emits its describe, unchanged.
		expect(order?.content).toContain('describe("setTotal", () => {');
	});

	it("keeps the sibling operation's describe WITH cases byte-identical — only the empty group is omitted (non-regression D)", () => {
		const files = emitSuite(emptyOperationGroupSuite(), "vitest", {
			methods: V27_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();

		// The with-cases sibling renders exactly the established F1 shape:
		// shape-aware instance call + toBeDefined, byte-identical to the same
		// case rendered in any existing suite (the empty group's presence must
		// not perturb the sibling's render).
		expect(order?.content).toContain('describe("setTotal", () => {');
		expect(order?.content).toContain(
			'it("Order.setTotal.boundary-0 — accept with an amount", () => {',
		);
		expect(order?.content).toContain(
			"const result = new Order().setTotal(25);",
		);
		expect(order?.content).toContain("expect(result).toBeDefined();");
	});

	it("keeps the invariant describe guarded on length > 0 — empty invariantCases renders no invariants describe, non-empty still does (pin B)", () => {
		// Empty invariantCases (the V-27 suite) → no `describe("Order invariants")`.
		const files = emitSuite(emptyOperationGroupSuite(), "vitest", {
			methods: V27_METHODS,
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();
		expect(order?.content).not.toContain('describe("Order invariants"');

		// Non-empty invariantCases → the invariants describe STILL emits (the
		// existing V-26 guard at vitest.ts:144 stays — this is not a
		// blanket "skip empty describes" change).
		const withInvariants = emitSuite(voidInvariantSuite(), "vitest", {
			methods: ORDER_VOID_METHODS,
		});
		const order2 = withInvariants.find((file) =>
			file.path.endsWith("Order.test.ts"),
		);
		expect(order2).toBeDefined();
		expect(order2?.content).toContain('describe("Order invariants", () => {');
	});
});

/**
 * Real Order source for the V-27 E2E runnability pin. setSubtotal does NOT
 * exist in source (the V-25 shape: the staged op is missing from the source
 * method metadata) — the generated file must not reference it at all.
 */
const V27_ORDER_SOURCE = `export class Order {
	setTotal(amount: number): number {
		return amount * 2;
	}
}
`;

describe("emitSuite — a generated suite containing an EMPTY operation group RUNS GREEN under the real vitest runner (VERSAILLES-27 E2E runnability gate)", () => {
	it("executes the emitted file (empty op group + sibling with a real case) with the REAL vitest runner — exit 0, never 'No test found in suite' (Red today: vitest 3.2.7 hard-fails the empty describe)", async () => {
		const root = await mkdtemp(join(tmpdir(), "versailles-v27-"));
		try {
			await writeFile(join(root, "order.ts"), `${V27_ORDER_SOURCE}\n`, "utf8");

			const files = emitSuite(emptyOperationGroupSuite(), "vitest", {
				generatedDir: ".",
				modulePaths: { Order: "./order" },
				methods: V27_METHODS,
			});
			const order = files.find((file) => file.path.endsWith("Order.test.ts"));
			expect(order).toBeDefined();
			await writeFile(
				join(root, "Order.test.ts"),
				order?.content ?? "",
				"utf8",
			);

			// The REAL vitest runner (vitest.mjs under process.execPath).
			// bun's own test-runner shim TOLERATES empty describes, so `bun
			// test` cannot reproduce the V-27 failure; the established command
			// (package.json "test": "vitest run") must run the generated file
			// green — no --passWithNoTests, no manual edits.
			const vitestBin = join(
				dirname(fileURLToPath(import.meta.url)),
				"..",
				"node_modules",
				"vitest",
				"vitest.mjs",
			);
			const run = spawnSync(process.execPath, [vitestBin, "run"], {
				cwd: root,
				encoding: "utf8",
			});
			expect(
				run.status,
				`generated suite with an empty op group did not run clean:\n${run.stdout}\n${run.stderr}`,
			).toBe(0);
			// The reported hard-fail shape is gone — no empty-suite rejection.
			expect(run.stdout + run.stderr).not.toContain("No test found in suite");
		} finally {
			await rm(root, { recursive: true, force: true });
		}
	});
});

// B1 root cause: the vitest emitter's instance-binding branch constructs a
// FRESH `const instance = new Order();` but never seeds the planner's
// captured pre-call state (inputs.balance = 50) onto it before the operation
// runs — so the postcondition assertion reads the constructor's default
// state (balance = 1) instead of the captured pre-state, and every emitted
// postcondition-satisfaction case fails at runtime (got 1, expected 51).
describe("emitSuite — postcondition-satisfaction seeds captured pre-state onto the bound instance (B1)", () => {
	it("emits an instance.balance = 50 seed line BEFORE the instance.addItem call in the rendered postcondition-satisfaction test", () => {
		const suite: PlannedSuite = {
			clauseIds: ["Order.post0"],
			operations: [
				{
					component: "Order",
					operation: "addItem",
					cases: [
						{
							id: "Order.addItem.postcondition-satisfaction-0",
							kind: "postcondition-satisfaction",
							description: "valid input asserting postconditions Order.post0",
							inputs: { sku: "initial", price: 1, balance: 50 },
							expects: {
								outcome: "accept",
								postconditions: ["Order.post0"],
								assertions: [{ subject: "balance", op: "==", literal: 51 }],
							},
							traces: ["Order.post0"],
						},
					],
				},
			],
			invariantCases: [],
		};
		const files = emitSuite(suite, "vitest", {
			methods: {
				Order: {
					addItem: {
						static: false,
						params: ["sku", "price"],
						returnType: "void",
					},
				},
			},
		});
		const order = files.find((file) => file.path.endsWith("Order.test.ts"));
		expect(order).toBeDefined();
		const content = order?.content ?? "";
		// The REQUIRED render seeds the captured pre-state onto the fresh
		// instance before the call, so the postcondition assertion observes
		// balance transition 50 → 51 rather than the constructor's default.
		expect(content).toContain("instance.balance = 50;");
		expect(content.indexOf("instance.balance = 50;")).toBeLessThan(
			content.indexOf('instance.addItem("initial", 1);'),
		);
	});

	it("executes the emitted postcondition-satisfaction test with the REAL vitest runner — exit 0 (Red today: fresh instance starts at balance 0, not the captured pre-state 50)", async () => {
		const root = await mkdtemp(join(tmpdir(), "versailles-b1-"));
		try {
			await writeFile(
				join(root, "order.ts"),
				`export class Order {
	private balance = 0;
	addItem(sku: string, price: number): void {
		if (sku === "") throw new Error("sku must not be empty");
		this.balance += price;
	}
}
`,
				"utf8",
			);

			const suite: PlannedSuite = {
				clauseIds: ["Order.post0"],
				operations: [
					{
						component: "Order",
						operation: "addItem",
						cases: [
							{
								id: "Order.addItem.postcondition-satisfaction-0",
								kind: "postcondition-satisfaction",
								description: "valid input asserting postconditions Order.post0",
								inputs: { sku: "initial", price: 1, balance: 50 },
								expects: {
									outcome: "accept",
									postconditions: ["Order.post0"],
									assertions: [{ subject: "balance", op: "==", literal: 51 }],
								},
								traces: ["Order.post0"],
							},
						],
					},
				],
				invariantCases: [],
			};
			const files = emitSuite(suite, "vitest", {
				generatedDir: ".",
				modulePaths: { Order: "./order" },
				methods: {
					Order: {
						addItem: {
							static: false,
							params: ["sku", "price"],
							returnType: "void",
						},
					},
				},
			});
			const order = files.find((file) => file.path.endsWith("Order.test.ts"));
			expect(order).toBeDefined();
			await writeFile(
				join(root, "Order.test.ts"),
				order?.content ?? "",
				"utf8",
			);

			// B1: the assertion literal derives from fabricated pre-state;
			// without seeding, generated suite is red at runtime.
			const vitestBin = join(
				dirname(fileURLToPath(import.meta.url)),
				"..",
				"node_modules",
				"vitest",
				"vitest.mjs",
			);
			const run = spawnSync(process.execPath, [vitestBin, "run"], {
				cwd: root,
				encoding: "utf8",
			});
			expect(
				run.status,
				`generated postcondition-satisfaction suite did not run clean:\n${run.stdout}\n${run.stderr}`,
			).toBe(0);
		} finally {
			await rm(root, { recursive: true, force: true });
		}
	});
});

/**
 * V-148 isolation context: OrderService.addItem(sku, price) with ONE numeric
 * precondition (`price >= 1`) and no postconditions/invariants, so §9.1 plans
 * ONLY the three boundary cases — the minimal shape that reproduces the
 * boundary-path input-isolation bug end to end (contract → plan → emit → run).
 */
function makeV148IsolationContext(): VersaillesContext {
	const contracts: ContractsFile = {
		version: "1.0",
		contracts: {
			OrderService: {
				invariants: [],
				operations: {
					addItem: {
						id: "OrderService.addItem",
						params: [
							{ name: "sku", type: "string" },
							{ name: "price", type: "number" },
						],
						preconditions: [
							{ id: "OrderService.addItem.pre0", expr: "price >= 1" },
						],
						postconditions: [],
						effects: [],
						sourceHash: "additem-v148-hash",
					},
				},
			},
		},
	};
	return {
		config: makeConfig(),
		contracts,
		manifests: {
			version: "1.0",
			manifests: {
				OrderService: { sourceHash: "man-order-v148", fields: {} },
			},
		},
		predicates: predicatesFixture(),
		parsedContracts: parseAll(contracts),
		parseErrors: [],
		validationErrors: [],
		validationWarnings: [],
		isValid: true,
	};
}

// V-148 root cause: planBoundaryCases builds each case's inputs from the
// TARGET param alone (`{ [shape.variable]: item.value }`), so the emitter
// renders `addItem(undefined, <price>)` — every sibling param is undefined.
// The fixture below DEREFERENCES sku (`sku.trim()`) BEFORE guarding price on
// purpose: a loose `sku === ""` comparison silently tolerates undefined
// (evaluates false, no crash), which would let today's broken emission run
// green by accident. The early dereference forces the missing sibling into
// the WRONG failure mode — a raw TypeError before the guarded price clause is
// ever reached — so this gate can only turn green once the planner emits full
// input objects and every boundary case exercises its INTENDED clause.
describe("emitted suite — boundary/partition cases run green against a real component (VERSAILLES-148)", () => {
	it("executes the emitted boundary-case tests with the REAL vitest runner — exit 0 (Red today: undefined siblings crash via TypeError before reaching the guarded clause)", async () => {
		const root = await mkdtemp(join(tmpdir(), "versailles-v148-"));
		try {
			await writeFile(
				join(root, "order.ts"),
				`export class OrderService {
	private balance = 0;
	addItem(sku: string, price: number): void {
		if (sku.trim() === "") throw new Error("sku must not be empty");
		if (!(price >= 1)) throw new Error("price must be positive");
		this.balance += price;
	}
}
`,
				"utf8",
			);

			const suite = planTestCases(makeV148IsolationContext());
			const files = emitSuite(suite, "vitest", {
				generatedDir: ".",
				modulePaths: { OrderService: "./order" },
				methods: {
					OrderService: {
						addItem: {
							static: false,
							params: ["sku", "price"],
							returnType: "void",
						},
					},
				},
			});
			const order = files.find((file) =>
				file.path.endsWith("OrderService.test.ts"),
			);
			expect(order).toBeDefined();
			await writeFile(
				join(root, "OrderService.test.ts"),
				order?.content ?? "",
				"utf8",
			);

			// The REAL vitest runner (same harness as the V-27/B1 E2E gates):
			// bun's own test-runner shim is more forgiving than the established
			// `vitest run` command, so it cannot stand in here.
			const vitestBin = join(
				dirname(fileURLToPath(import.meta.url)),
				"..",
				"node_modules",
				"vitest",
				"vitest.mjs",
			);
			const run = spawnSync(process.execPath, [vitestBin, "run"], {
				cwd: root,
				encoding: "utf8",
			});
			expect(
				run.status,
				`emitted boundary-case suite did not run clean:\n${run.stdout}\n${run.stderr}`,
			).toBe(0);
			// The runner SUMMARY must independently show zero failures — the
			// gate pins the observable output, not just the exit code.
			expect(run.stdout).not.toMatch(/\d+ failed/);
		} finally {
			await rm(root, { recursive: true, force: true });
		}
	});
});
