import { spawnSync } from "node:child_process";
import { mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { parseExpression } from "../packages/core/src/core/parser.js";
import type { ClauseKind, Node } from "../packages/core/src/core/parser.js";
import type {
	ContractClause,
	ContractsFile,
	ManifestsFile,
	PredicatesFile,
	VersaillesContext,
	WorkspaceConfig,
} from "../packages/core/src/loader/workspace.js";
import { renderClausePredicate } from "../packages/engine/src/generator/codegen.js";
import {
	emitSuite,
	planPropertyBlocks,
	planTestCases,
} from "../packages/engine/src/generator/index.js";
import type {
	ArbitrarySpec,
	EmitOptions,
	PlannedCase,
	PlannedSuite,
	PropertyClause,
	PropertyDescriptor,
	PropertyPlan,
} from "../packages/engine/src/generator/index.js";
import { derivePropertySeed } from "../packages/engine/src/generator/seed.js";

/**
 * Seeded PBT emission — the vitest property-block emitter (ADR-0017 Phase 5,
 * build-spec §9.6 + deterministic-generation.contract.yaml `emit_case` /
 * `plan_property_blocks`). Pinned against the PBT IR shipped in Phase 3
 * (ir.ts: PropertyOutcome / ArbitrarySpec / PropertyClause / PropertyDescriptor
 * / PropertyPlan), the seed helper (seed.ts: derivePropertySeed), the strategy
 * selector (Phase 4), and the property-block planner (Phase 4: planPropertyBlocks
 * in planner.ts).
 *
 * ── THE CHUNK-6 RE-PIN (three integration gaps the old pin missed) ──────────
 *
 * The ORIGINAL Chunk 6 pin rendered property blocks with a broken layout that
 * made the committed example (`examples/order-service`) produce BROKEN
 * generated tests. This re-pin is the corrected contract; the emitter is Red
 * against it until the implementer lands the fixes.
 *
 *   GAP 1 — CALL SHAPE. The old layout hardcoded the legacy STATIC
 *   options-object call `<Component>.<op>({ <params> })`. The manifest declares
 *   `OrderService.addItem` as an INSTANCE method with positional params, so the
 *   emitted `OrderService.addItem({ sku, price })` is a TypeError at runtime —
 *   and the contract's `must_not` (deterministic-generation.contract.yaml)
 *   forbids an options-object argument list where positional params are
 *   declared. The property-block call is now SHAPE-AWARE from the SAME manifest
 *   `methods` metadata the concrete cases use (renderCall, VERSAILLES-20 F1,
 *   build-spec §9.4): instance → `new <Component>().<op>(<positional>)`,
 *   static → `<Component>.<op>(<positional>)`, params in declared order. The
 *   property block must reuse renderCall's callee computation (or an
 *   equivalent) — the args come from the callback param names (descriptor
 *   params), not from a case inputs object.
 *
 *   GAP 2 — PREDICATE RESOLUTION. A predicateCall oracle (e.g.
 *   `isPositive(price)`) emits a bare reference that is never imported →
 *   ReferenceError in the generated test. The emitter now imports every
 *   registered predicate a component's property clauses reference, via the new
 *   EmitOptions.predicates map (predicate name → module import specifier),
 *   threaded through the emitter seam exactly like modulePaths / methods. The
 *   generate handler derives the specifier from contracts.json's
 *   predicates[].source: a `<Module>.<function>` sourceRef (e.g.
 *   `"OrderService.isPositive"`) resolves to the module path used for that
 *   component; a path-like source resolves verbatim.
 *
 *   GAP 3 — VALID-REGION FILTERING + ORACLE ASSERTION. The old layout embedded
 *   the clause predicate as a DEAD const (never asserted) and the arbitraries
 *   generated inputs OUTSIDE the valid region (fc.string() includes "",
 *   fc.integer() includes ≤0), so the property called the op with invalid
 *   inputs and the call threw. The redesign (build-spec §9.6 "Valid-space
 *   filters via codegen'd clause predicates" + "the property asserts the clause
 *   holds"):
 *     - every satisfies/invariant-preserving block FILTERS its arbitrary chain
 *       with the codegen'd oracle: `<arb>.filter(<oracle>)` (fast-check idiom;
 *       the pinned valid regions — non-empty strings, positive ints — are
 *       large, so filter sparsity warnings never fire),
 *     - every satisfies/invariant-preserving block ASSERTS its own clause after
 *       the call: `expect(<oracle>(<params>)).toBe(true)`.
 *
 * ── The pinned emitted layout (exact bytes the implementer MUST produce) ────
 *
 * File header — the v1 concrete header is preserved byte-for-byte; predicate
 * imports land immediately after the component import, one line per referenced
 * predicate, before the fast-check import:
 *
 * ```ts
 * // Auto-generated by the Versailles deterministic generator core.
 * // Do not edit — regenerate with `versailles generate`.
 * // traces: "OrderService.inv0", "OrderService.addItem.pre0", ...
 * import { describe, expect, it } from "vitest";
 *
 * import { OrderService } from "../../src/OrderService.js";
 * import { isPositive } from "../../src/OrderService.js";
 * import fc from "fast-check";
 * ```
 *
 * Property blocks render INSIDE the operation's describe, AFTER that
 * operation's concrete cases, in plan.descriptors order. One block per
 * descriptor, sharing the concrete case's traceability-comment convention
 * (§9.3 — a tab-indented `// traces: <JSON-stringified ids>` line above the
 * it). The oracle consts are HOISTED to the it-body level (indent 2) so the
 * SAME codegen'd arrow function fills both the arbitrary `.filter(...)` and the
 * in-callback assertion — never a dead const, never duplicated code.
 *
 * Satisfies — INSTANCE operation, void return, string `!= ""` clause (the
 * committed example's exact shape; the sibling `isPositive(price)` precondition
 * guards price in BOTH blocks — see the guard-set rule below):
 *
 * ```ts
 * 	// traces: "OrderService.addItem.pre0"
 * 	it("OrderService.addItem.property-satisfies-0", () => {
 * 		const sku = fc.string();
 * 		const price = fc.integer();
 * 		const OrderService_addItem_pre0 = (sku) => sku !== "";
 * 		const OrderService_addItem_pre1 = (price) => isPositive(price);
 * 		const prop = fc.property(sku.filter(OrderService_addItem_pre0), price.filter(OrderService_addItem_pre1), (sku, price) => {
 * 			new OrderService().addItem(sku, price);
 * 			expect(OrderService_addItem_pre0(sku)).toBe(true);
 * 		});
 * 		fc.assert(prop, { seed: 101, numRuns: 100 });
 * 	});
 * ```
 *
 * Satisfies — STATIC operation (all arbitrary kinds, enum/boolean/string/
 * list-default/optional-default):
 *
 * ```ts
 * 	// traces: "AccountService.setStatus.pre0"
 * 	it("AccountService.setStatus.property-satisfies-0", () => {
 * 		const newStatus = fc.constantFrom("ACTIVE", "FROZEN");
 * 		const notify = fc.boolean();
 * 		const reason = fc.string();
 * 		const tags = fc.constant([]);
 * 		const memo = fc.constant(0);
 * 		const AccountService_setStatus_pre0 = (newStatus) => newStatus === "ACTIVE" || newStatus === "FROZEN";
 * 		const prop = fc.property(newStatus.filter(AccountService_setStatus_pre0), notify, reason, tags, memo, (newStatus, notify, reason, tags, memo) => {
 * 			AccountService.setStatus(newStatus, notify, reason, tags, memo);
 * 			expect(AccountService_setStatus_pre0(newStatus)).toBe(true);
 * 		});
 * 		fc.assert(prop, { seed: -987654321, numRuns: 100 });
 * 	});
 * ```
 *
 * Invariant-preserving — the oracle references a MANIFEST FIELD (balance), not
 * a callback param, so the block binds the component INSTANCE inside the
 * callback and the assertion passes the field on the bound instance:
 *
 * ```ts
 * 	// traces: "AccountService.inv0"
 * 	it("AccountService.withdraw.property-invariant-preserving-0", () => {
 * 		const amount = fc.integer({ min: 10, max: 100 });
 * 		const AccountService_withdraw_pre0 = (amount) => amount >= 10 && amount <= 100;
 * 		const AccountService_inv0 = (balance) => balance >= 0;
 * 		const prop = fc.property(amount.filter(AccountService_withdraw_pre0), (amount) => {
 * 			const instance = new AccountService();
 * 			instance.withdraw(amount);
 * 			expect(AccountService_inv0(instance.balance)).toBe(true);
 * 		});
 * 		fc.assert(prop, { seed: 555, numRuns: 100 });
 * 	});
 * ```
 *
 * Rejects — NO oracle consts (the clause is not embedded as dead code), NO
 * filter; the block asserts the descriptor's configured rejection idiom
 * (ADR-0007): "throws" → `expect(() => <call>).toThrow()`,
 * "returns" → `expect(<call>).toBeNull()`:
 *
 * ```ts
 * 	// traces: "AccountService.withdraw.pre0"
 * 	it("AccountService.withdraw.property-rejects-0", () => {
 * 		const amount = fc.integer({ min: 0, max: 9 });
 * 		const prop = fc.property(amount, (amount) => {
 * 			expect(() => new AccountService().withdraw(amount)).toThrow();
 * 		});
 * 		fc.assert(prop, { seed: 42, numRuns: 100 });
 * 	});
 * ```
 *
 * ── The emitter rules these pins fix (facts the implementer needs) ──────────
 *
 * - Call shape (GAP 1): the property block reads methods?.[component]?.[operation]
 *   exactly like renderCall (vitest.ts): meta.static → `<Component>.<op>(...)`,
 *   else → `new <Component>().<op>(...)`. The positional args are the
 *   descriptor params in order (the callback param names — descriptor.params
 *   mirrors operation.params declared order, which the manifest metadata also
 *   carries). With NO methods metadata (legacy) the historical options-object
 *   call `<Component>.<op>({ <params> })` is preserved byte-identically — the
 *   filter + oracle assertion still render (one backward-compat pin below).
 * - Guard set (GAP 3): for a satisfies/invariant-preserving block, the FILTER
 *   oracles are the clause oracles of EVERY satisfies + invariant-preserving
 *   descriptor for the SAME (component, operation), in plan order — the
 *   "satisfy invariants + all other preconditions" rule. Each callback param
 *   referenced by a guard oracle gets `.filter(<first guard oracle referencing
 *   it>)` on its arbitrary. The block EMBEDS exactly the guard oracles it uses
 *   (its filters + its own asserted clause) — never a dead const. The
 *   oracle's referenced params are its codegen'd arrow-function parameter list
 *   (codegen.ts output is byte-pinned `(<params>) => <expr>`; split at the
 *   first `) => `, split params on ", ").
 * - Oracle assertion (GAP 3): `expect(<oracle>(<params>)).toBe(true)` where
 *   each oracle parameter is passed the callback value when it is a callback
 *   param, else `<instance>.<param>` (a manifest field) — the instance binding
 *   (`const instance = new <Component>(); instance.<op>(...);`) is emitted when
 *   any asserted oracle parameter is a field. Satisfies/invariant blocks render
 *   the BARE call (no `const result =` — void-safe; the clause IS the check).
 * - Predicate imports (GAP 2): for each component file, `import { <name> } from
 *   "<specifier>"` for every predicate whose name appears in the component's
 *   property clause code strings, ordered by first appearance across the
 *   component's descriptors in plan order, placed after the component import
 *   and before `import fc from "fast-check"`. Evidence from the committed
 *   example: contracts.json predicates.isPositive.source = "OrderService.isPositive"
 *   (a `<Module>.<function>` sourceRef) and manifests.json OrderService.sourcePath
 *   = "src/OrderService.ts" — the predicate is CO-LOCATED with the component,
 *   so the specifier is the component's module path (`../../src/OrderService.js`
 *   with the default prefix; the pipeline's modulePaths override may carry the
 *   `.ts` extension). The predicates map is a NEW optional EmitOptions field;
 *   xunit/pytest ignore it.
 * - Per-param arbitraries (ArbitrarySpec → fc call): kind "number" + bounds →
 *   `fc.integer({ min, max })`; kind "number" (no bounds) → `fc.integer()`;
 *   kind "enum" → `fc.constantFrom(<members>)`; kind "string" → `fc.string()`;
 *   kind "boolean" → `fc.boolean()`; default present (list<X>/optional<X>) →
 *   `fc.constant(<default>)`.
 * - fc.assert options render `{ seed: <seed literal>, numRuns: <propertyNumRuns> }`
 *   with a space after the comma; seed via String(descriptor.seed) (int32, may
 *   be negative), numRuns via String (default 100 when the option is absent).
 * - Rejection idiom (ADR-0007) comes from the descriptor's `rejectionIdiom`
 *   field, exactly like the concrete cases read case_.expects.rejectionIdiom.
 */

// ── Fixture: a concrete suite + a property plan (hand-built, mirroring what
// planTestCases + planPropertyBlocks produce for the same contracts). ─────────

const ACCOUNT = "AccountService";
const CUSTOMER = "CustomerService";
const ORDER = "OrderService";

/**
 * Manifest method metadata threaded through the emitter seam exactly like the
 * generate handler's deriveMethods (VERSAILLES-20 F1). The committed example's
 * addItem is an INSTANCE void method with positional params [sku, price];
 * AccountService.withdraw is an INSTANCE void method; AccountService.setStatus
 * is STATIC; CustomerService.upgrade is INSTANCE.
 */
const PBT_METHODS: EmitOptions["methods"] = {
	[ACCOUNT]: {
		withdraw: { static: false, params: ["amount"], returnType: "void" },
		setStatus: {
			static: true,
			params: ["newStatus", "notify", "reason", "tags", "memo"],
			returnType: "boolean",
		},
	},
	[CUSTOMER]: {
		upgrade: { static: false, params: ["newTier"], returnType: "string" },
	},
	[ORDER]: {
		addItem: { static: false, params: ["sku", "price"], returnType: "void" },
	},
};

/**
 * The registered-predicate import table (predicate name → module import
 * specifier) threaded through the emitter seam. Derived from contracts.json's
 * predicates map by the generate handler: `"isPositive": { "source":
 * "OrderService.isPositive" }` + the OrderService manifest sourcePath
 * "src/OrderService.ts" → the predicate is co-located with the component, so
 * the specifier is the component's module path (the default-prefix form in
 * this fixture, since no modulePaths override is passed).
 */
const PBT_PREDICATES: Record<string, string> = {
	isPositive: "../../src/OrderService.js",
};

/** A concrete PlannedSuite (the Phase-1/2 output shape, hand-built). */
function pbtSuite(): PlannedSuite {
	return {
		clauseIds: [
			`${ACCOUNT}.inv0`,
			`${ACCOUNT}.withdraw.pre0`,
			`${ACCOUNT}.withdraw.post0`,
			`${ACCOUNT}.setStatus.pre0`,
			`${CUSTOMER}.upgrade.pre0`,
			`${ORDER}.addItem.pre0`,
			`${ORDER}.addItem.pre1`,
		],
		operations: [
			{
				component: ACCOUNT,
				operation: "withdraw",
				cases: [
					{
						id: `${ACCOUNT}.withdraw.boundary-0`,
						kind: "boundary",
						description: "reject amount below the lower bound",
						inputs: { amount: 9 },
						expects: { outcome: "reject", rejectionIdiom: "throws" },
						traces: [`${ACCOUNT}.withdraw.pre0`],
					},
					{
						id: `${ACCOUNT}.withdraw.boundary-1`,
						kind: "boundary",
						description: "accept an in-range amount",
						inputs: { amount: 50 },
						expects: { outcome: "accept" },
						traces: [`${ACCOUNT}.withdraw.pre0`],
					},
				],
			},
			{
				component: ACCOUNT,
				operation: "setStatus",
				cases: [
					{
						id: `${ACCOUNT}.setStatus.boundary-0`,
						kind: "boundary",
						description: "accept an allowed status",
						inputs: { newStatus: "ACTIVE" },
						expects: { outcome: "accept" },
						traces: [`${ACCOUNT}.setStatus.pre0`],
					},
				],
			},
			{
				component: CUSTOMER,
				operation: "upgrade",
				cases: [
					{
						id: `${CUSTOMER}.upgrade.boundary-0`,
						kind: "boundary",
						description: "accept an allowed tier",
						inputs: { newTier: "GOLD" },
						expects: { outcome: "accept" },
						traces: [`${CUSTOMER}.upgrade.pre0`],
					},
				],
			},
			{
				// The committed example's exact operation: an INSTANCE void
				// method with positional params, two precondition clauses
				// (`sku != ""` and the registered-predicate call
				// `isPositive(price)`).
				component: ORDER,
				operation: "addItem",
				cases: [
					{
						id: `${ORDER}.addItem.precondition-violation-0`,
						kind: "precondition-violation",
						description: `violates ${ORDER}.addItem.pre0`,
						inputs: { sku: "", price: 1 },
						expects: { outcome: "reject", rejectionIdiom: "throws" },
						traces: [`${ORDER}.addItem.pre0`],
					},
					{
						id: `${ORDER}.addItem.precondition-violation-1`,
						kind: "precondition-violation",
						description: `violates ${ORDER}.addItem.pre1 (predicate isPositive falsified via price)`,
						inputs: { sku: "initial", price: -1 },
						expects: { outcome: "reject", rejectionIdiom: "throws" },
						traces: [`${ORDER}.addItem.pre1`],
					},
				],
			},
		],
		invariantCases: [
			{
				id: `${ACCOUNT}.withdraw.invariant-0`,
				kind: "invariant",
				description: "balance stays non-negative after withdraw",
				inputs: { amount: 50, balance: 50 },
				expects: { outcome: "accept" },
				traces: [`${ACCOUNT}.inv0`],
			},
		],
	};
}

/**
 * The property plan the implementer's emitter must render. Order mirrors the
 * planner's deterministic per-operation traversal (preconditions satisfies →
 * invariants invariant-preserving → expected-rejection rejects, per operation
 * in component order), ending with the OrderService.addItem clauses — the two
 * satisfies descriptors that make the committed example work (their guard set
 * spans BOTH preconditions, so the op never receives an invalid sibling).
 */
function pbtPlan(): PropertyPlan {
	return {
		descriptors: [
			{
				// Compound precondition `amount >= 10 and amount <= 100` → the
				// codegen'd oracle + compound-aware numeric bounds.
				id: `${ACCOUNT}.withdraw.property-satisfies-0`,
				component: ACCOUNT,
				operation: "withdraw",
				params: [
					{
						param: "amount",
						typeRef: "number",
						kind: "number",
						bounds: { min: 10, max: 100 },
					},
				],
				clauses: [
					{
						clauseId: `${ACCOUNT}.withdraw.pre0`,
						code: "(amount) => amount >= 10 && amount <= 100",
					},
				],
				outcome: "satisfies",
				traces: [`${ACCOUNT}.withdraw.pre0`],
				seed: 123456789,
			},
			{
				// Invariant-preserving: the oracle references the manifest
				// FIELD balance (not a callback param) → the block binds the
				// instance and asserts instance.balance via the oracle.
				id: `${ACCOUNT}.withdraw.property-invariant-preserving-0`,
				component: ACCOUNT,
				operation: "withdraw",
				params: [
					{
						param: "amount",
						typeRef: "number",
						kind: "number",
						bounds: { min: 10, max: 100 },
					},
				],
				clauses: [
					{
						clauseId: `${ACCOUNT}.inv0`,
						code: "(balance) => balance >= 0",
					},
				],
				outcome: "invariant-preserving",
				traces: [`${ACCOUNT}.inv0`],
				seed: 555,
			},
			{
				// Expected-rejection with the DEFAULT idiom (throws). The
				// clause oracle is NOT embedded (no dead consts in rejects).
				id: `${ACCOUNT}.withdraw.property-rejects-0`,
				component: ACCOUNT,
				operation: "withdraw",
				params: [
					{
						param: "amount",
						typeRef: "number",
						kind: "number",
						bounds: { min: 0, max: 9 },
					},
				],
				clauses: [
					{
						clauseId: `${ACCOUNT}.withdraw.pre0`,
						code: "(amount) => amount >= 10",
					},
				],
				outcome: "rejects",
				rejectionIdiom: "throws",
				traces: [`${ACCOUNT}.withdraw.pre0`],
				seed: 42,
			},
			{
				// Satisfies over enum + boolean + string + list + optional
				// params — every ArbitrarySpec kind in one STATIC block.
				// Negative int32 seed.
				id: `${ACCOUNT}.setStatus.property-satisfies-0`,
				component: ACCOUNT,
				operation: "setStatus",
				params: [
					{
						param: "newStatus",
						typeRef: "enum<ACTIVE,FROZEN>",
						kind: "enum",
						members: ["ACTIVE", "FROZEN"],
					},
					{ param: "notify", typeRef: "boolean", kind: "boolean" },
					{ param: "reason", typeRef: "string", kind: "string" },
					{
						param: "tags",
						typeRef: "list<string>",
						kind: "string",
						default: [],
					},
					{
						param: "memo",
						typeRef: "optional<number>",
						kind: "number",
						default: 0,
					},
				],
				clauses: [
					{
						clauseId: `${ACCOUNT}.setStatus.pre0`,
						code: '(newStatus) => newStatus === "ACTIVE" || newStatus === "FROZEN"',
					},
				],
				outcome: "satisfies",
				traces: [`${ACCOUNT}.setStatus.pre0`],
				seed: -987654321,
			},
			{
				// Expected-rejection with the CONFIGURED returns idiom.
				id: `${CUSTOMER}.upgrade.property-rejects-0`,
				component: CUSTOMER,
				operation: "upgrade",
				params: [
					{
						param: "newTier",
						typeRef: "enum<GOLD,SILVER>",
						kind: "enum",
						members: ["GOLD", "SILVER"],
					},
				],
				clauses: [
					{
						clauseId: `${CUSTOMER}.upgrade.pre0`,
						code: "(newTier) => newTier !== null",
					},
				],
				outcome: "rejects",
				rejectionIdiom: "returns",
				traces: [`${CUSTOMER}.upgrade.pre0`],
				seed: 7,
			},
			{
				// The committed example's `sku != ""` clause — an INSTANCE void
				// op with TWO precondition clauses. The guard set spans BOTH
				// satisfies oracles (pre0 guards sku, pre1 guards price), so
				// the block's filters keep the call inside the full valid
				// region.
				id: `${ORDER}.addItem.property-satisfies-0`,
				component: ORDER,
				operation: "addItem",
				params: [
					{ param: "sku", typeRef: "string", kind: "string" },
					{ param: "price", typeRef: "number", kind: "number" },
				],
				clauses: [
					{
						clauseId: `${ORDER}.addItem.pre0`,
						code: '(sku) => sku !== ""',
					},
				],
				outcome: "satisfies",
				traces: [`${ORDER}.addItem.pre0`],
				seed: 101,
			},
			{
				// The committed example's predicateCall clause — the predicate
				// import at file top + the oracle asserting via the imported
				// predicate.
				id: `${ORDER}.addItem.property-satisfies-1`,
				component: ORDER,
				operation: "addItem",
				params: [
					{ param: "sku", typeRef: "string", kind: "string" },
					{ param: "price", typeRef: "number", kind: "number" },
				],
				clauses: [
					{
						clauseId: `${ORDER}.addItem.pre1`,
						code: "(price) => isPositive(price)",
					},
				],
				outcome: "satisfies",
				traces: [`${ORDER}.addItem.pre1`],
				seed: 202,
			},
		],
		strategies: {},
		warnings: [],
	};
}

/** The full emitSuite options the enabled=true pins pass (the pipeline shape). */
function pbtOptions(overrides: Partial<EmitOptions> = {}): EmitOptions {
	return {
		methods: PBT_METHODS,
		predicates: PBT_PREDICATES,
		propertyPlan: pbtPlan(),
		propertyNumRuns: 100,
		...overrides,
	};
}

function emitPbt(overrides: Partial<EmitOptions> = {}) {
	return emitSuite(pbtSuite(), "vitest", pbtOptions(overrides));
}

function accountFile(files: ReturnType<typeof emitSuite>) {
	return files.find((file) => file.path.endsWith("AccountService.test.ts"));
}

function customerFile(files: ReturnType<typeof emitSuite>) {
	return files.find((file) => file.path.endsWith("CustomerService.test.ts"));
}

function orderFile(files: ReturnType<typeof emitSuite>) {
	return files.find((file) => file.path.endsWith("OrderService.test.ts"));
}

describe("emitSuite vitest — property-block emitter (ADR-0017 §9.6, deterministic-generation.contract.yaml)", () => {
	it("enabled=false backward-compat pin: no propertyPlan (or empty plan) → byte-identical to today's concrete-case output — no fast-check import, no fc.assert blocks", () => {
		const suite = pbtSuite();
		// The v1 baseline from today's emitter (pure function of the suite).
		const baseline = emitSuite(suite, "vitest");
		expect(baseline.length).toBeGreaterThan(0);
		// No plan → byte-identical (the emitter ignores the absent plan).
		expect(emitSuite(suite, "vitest", {})).toEqual(baseline);
		// Empty plan → byte-identical (no descriptors ⇒ no property blocks).
		const emptyPlan: PropertyPlan = {
			descriptors: [],
			strategies: {},
			warnings: [],
		};
		expect(emitSuite(suite, "vitest", { propertyPlan: emptyPlan })).toEqual(
			baseline,
		);
		expect(
			emitSuite(suite, "vitest", {
				propertyPlan: emptyPlan,
				propertyNumRuns: 100,
			}),
		).toEqual(baseline);
		// The pinned invariant: disabled output has no PBT surface at all.
		for (const file of baseline) {
			expect(file.content).not.toContain("fast-check");
			expect(file.content).not.toContain("fc.assert");
			expect(file.content).not.toContain("fc.");
		}
	});

	it("pins the emit seam type: EmitOptions carries the property plan, numRuns, methods, and the predicate import map", () => {
		// Typecheck-only pin (mirrors V1_EMITTER_FRAMEWORKS in
		// tests/emitters.test.ts): this const compiles only once EmitOptions
		// gains propertyPlan + propertyNumRuns + predicates (the ir.ts seam
		// change — predicates is the GAP-2 predicate-resolution seam).
		const options: EmitOptions = {
			propertyPlan: { descriptors: [], strategies: {}, warnings: [] },
			propertyNumRuns: 100,
			methods: PBT_METHODS,
			predicates: PBT_PREDICATES,
		};
		expect(options.propertyNumRuns).toBe(100);
		expect(options.propertyPlan?.descriptors).toEqual([]);
		expect(options.predicates?.isPositive).toBe("../../src/OrderService.js");
		expect(options.methods?.OrderService?.addItem).toEqual({
			static: false,
			params: ["sku", "price"],
			returnType: "void",
		});
	});

	it("enabled=true: renders the fast-check import and an fc.assert block for a compound descriptor", () => {
		const files = emitPbt();
		const account = accountFile(files);
		expect(account).toBeDefined();
		// The fast-check import appears in the header, after the component import.
		expect(account?.content).toContain('import fc from "fast-check";');
		// The compound satisfies descriptor renders an fc.assert block.
		expect(account?.content).toContain(
			'it("AccountService.withdraw.property-satisfies-0", () => {',
		);
		expect(account?.content).toContain(
			"fc.assert(prop, { seed: 123456789, numRuns: 100 });",
		);
		// The concrete cases remain present (additive, never replacing).
		expect(account?.content).toContain(
			'it("AccountService.withdraw.boundary-0 — reject amount below the lower bound"',
		);
	});

	it("renders the seed literal and numRuns exactly in the fc.assert options — default 100, configured override, negative int32 seed", () => {
		// Config override: propertyNumRuns 250 threads into every block.
		const files = emitPbt({ propertyNumRuns: 250 });
		const account = accountFile(files);
		const customer = customerFile(files);
		const order = orderFile(files);
		expect(account?.content).toContain(
			"fc.assert(prop, { seed: 123456789, numRuns: 250 });",
		);
		expect(account?.content).toContain(
			"fc.assert(prop, { seed: 555, numRuns: 250 });",
		);
		expect(account?.content).toContain(
			"fc.assert(prop, { seed: 42, numRuns: 250 });",
		);
		expect(account?.content).toContain(
			"fc.assert(prop, { seed: -987654321, numRuns: 250 });",
		);
		expect(customer?.content).toContain(
			"fc.assert(prop, { seed: 7, numRuns: 250 });",
		);
		expect(order?.content).toContain(
			"fc.assert(prop, { seed: 101, numRuns: 250 });",
		);
		expect(order?.content).toContain(
			"fc.assert(prop, { seed: 202, numRuns: 250 });",
		);

		// Default 100 when propertyNumRuns is absent (build-spec §9.6).
		const defaulted = emitPbt({ propertyNumRuns: undefined });
		const accountDefaulted = accountFile(defaulted);
		expect(accountDefaulted?.content).toContain(
			"fc.assert(prop, { seed: 123456789, numRuns: 100 });",
		);
	});

	it("renders per-kind arbitraries: fc.integer bounds, fc.integer() unbounded, fc.constantFrom, fc.string, fc.boolean, fc.constant([]) list default, fc.constant(0) optional default", () => {
		const files = emitPbt();
		const account = accountFile(files);
		const order = orderFile(files);
		expect(account).toBeDefined();
		expect(order).toBeDefined();

		// number with bounds → fc.integer({ min, max })
		expect(account?.content).toContain(
			"const amount = fc.integer({ min: 10, max: 100 });",
		);
		// number without bounds (the predicateCall clause's param) → fc.integer()
		expect(order?.content).toContain("const price = fc.integer();");
		// enum → fc.constantFrom over the members
		expect(account?.content).toContain(
			'const newStatus = fc.constantFrom("ACTIVE", "FROZEN");',
		);
		// boolean → fc.boolean()
		expect(account?.content).toContain("const notify = fc.boolean();");
		// string → fc.string()
		expect(account?.content).toContain("const reason = fc.string();");
		expect(order?.content).toContain("const sku = fc.string();");
		// list<X> default [] → the deterministic constant arbitrary
		expect(account?.content).toContain("const tags = fc.constant([]);");
		// optional<number> default 0 → the deterministic constant arbitrary
		expect(account?.content).toContain("const memo = fc.constant(0);");
	});

	it("embeds the codegen'd clause predicates verbatim at the it-body level — the exact PropertyClause.code arrow-function source fills the const", () => {
		const files = emitPbt();
		const account = accountFile(files);
		const order = orderFile(files);
		expect(account).toBeDefined();
		expect(order).toBeDefined();

		// Oracle consts are HOISTED to the it-body level (indent 2, one tab
		// outside the fc.property callback) so the same const fills both the
		// arbitrary filter and the in-callback assertion.
		expect(account?.content).toContain(
			"\t\tconst AccountService_withdraw_pre0 = (amount) => amount >= 10 && amount <= 100;",
		);
		expect(account?.content).toContain(
			'\t\tconst AccountService_setStatus_pre0 = (newStatus) => newStatus === "ACTIVE" || newStatus === "FROZEN";',
		);
		expect(account?.content).toContain(
			"\t\tconst AccountService_inv0 = (balance) => balance >= 0;",
		);
		expect(order?.content).toContain(
			'\t\tconst OrderService_addItem_pre0 = (sku) => sku !== "";',
		);
		expect(order?.content).toContain(
			"\t\tconst OrderService_addItem_pre1 = (price) => isPositive(price);",
		);
		// The codegen'd source string itself appears verbatim (no mangling).
		expect(account?.content).toContain(
			"(amount) => amount >= 10 && amount <= 100",
		);
		// The oracle consts are HOISTED, never embedded inside the callback at
		// indent 3 — the hoisting is what lets the same const fill both the
		// arbitrary filter and the in-callback assertion.
		expect(account?.content).not.toContain(
			"\t\t\tconst AccountService_withdraw_pre0",
		);
		expect(order?.content).not.toContain(
			"\t\t\tconst OrderService_addItem_pre1",
		);
	});

	it("GAP-2 pin: imports every predicate a component's property clauses reference — predicate import at file top, after the component import, before the fast-check import", () => {
		const files = emitPbt();
		const account = accountFile(files);
		const customer = customerFile(files);
		const order = orderFile(files);
		expect(order).toBeDefined();

		// The predicate import lands between the component import and fc.
		expect(order?.content).toContain(
			'import { isPositive } from "../../src/OrderService.js";',
		);
		const orderImport = order?.content.indexOf(
			'import { isPositive } from "../../src/OrderService.js";',
		);
		const componentImport = order?.content.indexOf(
			'import { OrderService } from "../../src/OrderService.js";',
		);
		const fcImport = order?.content.indexOf('import fc from "fast-check";');
		expect(componentImport).toBeGreaterThan(-1);
		expect(fcImport).toBeGreaterThan(-1);
		expect(orderImport).toBeGreaterThan(componentImport ?? -1);
		expect(orderImport).toBeLessThan(fcImport ?? Number.MAX_SAFE_INTEGER);

		// Components whose clauses never reference a predicate import none.
		expect(account?.content).not.toContain("isPositive");
		expect(customer?.content).not.toContain("isPositive");
	});

	it("GAP-1 pin: an INSTANCE operation's property call is new <Component>().<op>(<positional>) — never a static call, never an options object", () => {
		const files = emitPbt();
		const order = orderFile(files);
		expect(order).toBeDefined();
		// The instance call with positional params (the committed example).
		expect(order?.content).toContain("new OrderService().addItem(sku, price);");
		// No static call on the instance method in the property surface.
		expect(order?.content).not.toContain("OrderService.addItem(sku");
		expect(order?.content).not.toContain("OrderService.addItem({");
		// No result binding on a void op, no toBeDefined anywhere in the
		// property surface.
		expect(order?.content).not.toContain(
			"const result = new OrderService().addItem",
		);
		expect(order?.content).not.toContain("expect(result).toBeDefined();");
	});

	it("GAP-3 pin: the property filters to the valid region — .filter(<oracle>) on the arbitrary chain", () => {
		const files = emitPbt();
		const account = accountFile(files);
		const order = orderFile(files);
		expect(account).toBeDefined();
		expect(order).toBeDefined();

		// Compound-bounded clause: the oracle filters the bounded arbitrary
		// (redundant with the bounds, but uniform — always emitted).
		expect(account?.content).toContain(
			"fc.property(amount.filter(AccountService_withdraw_pre0), (amount) => {",
		);
		// String `!= ""` clause: .filter on fc.string() guards sku; the sibling
		// predicateCall oracle guards price (the full valid region).
		expect(order?.content).toContain(
			"fc.property(sku.filter(OrderService_addItem_pre0), price.filter(OrderService_addItem_pre1), (sku, price) => {",
		);
		// The predicateCall clause's own filter uses the imported predicate.
		expect(order?.content).toContain("price.filter(OrderService_addItem_pre1)");
	});

	it("GAP-3 pin: the property ASSERTS the oracle — expect(<oracle>(<params>)).toBe(true) after the call", () => {
		const files = emitPbt();
		const account = accountFile(files);
		const order = orderFile(files);
		expect(account).toBeDefined();
		expect(order).toBeDefined();

		// Satisfies asserts its own clause on the callback params.
		expect(account?.content).toContain(
			"expect(AccountService_withdraw_pre0(amount)).toBe(true);",
		);
		expect(order?.content).toContain(
			"expect(OrderService_addItem_pre0(sku)).toBe(true);",
		);
		// The predicateCall clause asserts via the imported predicate.
		expect(order?.content).toContain(
			"expect(OrderService_addItem_pre1(price)).toBe(true);",
		);
	});

	it("invariant-preserving: the field-referencing oracle asserts on the bound instance — expect(<oracle>(instance.<field>)).toBe(true)", () => {
		const files = emitPbt();
		const account = accountFile(files);
		expect(account).toBeDefined();
		expect(account?.content).toContain(
			"expect(AccountService_inv0(instance.balance)).toBe(true);",
		);
		// The block binds the instance inside the callback and calls on it.
		expect(account?.content).toContain(
			"\t\t\tconst instance = new AccountService();",
		);
		expect(account?.content).toContain("\t\t\tinstance.withdraw(amount);");
	});

	it("rejects blocks embed NO dead oracle consts — the clause is never embedded unused; only the configured idiom asserts", () => {
		const files = emitPbt();
		const account = accountFile(files);
		expect(account).toBeDefined();
		// The rejects descriptor's clause code `(amount) => amount >= 10` is NOT
		// embedded anywhere (the satisfies block embeds the compound variant
		// `... && amount <= 100` — a different string).
		expect(account?.content).not.toContain(
			"const AccountService_withdraw_pre0 = (amount) => amount >= 10;",
		);
		// The rejects block's only assertion is the idiom.
		expect(account?.content).toContain(
			"expect(() => new AccountService().withdraw(amount)).toThrow();",
		);
	});

	it("places a §9.3 traceability comment above each property block (tab-indented, JSON-stringified clause ids)", () => {
		const files = emitPbt();
		const account = accountFile(files);
		const order = orderFile(files);
		expect(account).toBeDefined();
		expect(order).toBeDefined();

		// The per-block trace comment is tab-indented (inside the describe),
		// which distinguishes it from the file-header `// traces:` line.
		expect(account?.content).toContain(
			'\t// traces: "AccountService.withdraw.pre0"',
		);
		expect(account?.content).toContain('\t// traces: "AccountService.inv0"');
		expect(account?.content).toContain(
			'\t// traces: "AccountService.setStatus.pre0"',
		);
		expect(order?.content).toContain(
			'\t// traces: "OrderService.addItem.pre0"',
		);
		expect(order?.content).toContain(
			'\t// traces: "OrderService.addItem.pre1"',
		);
		// The trace comment sits immediately above its property block.
		expect(
			account?.content.indexOf('\t// traces: "AccountService.withdraw.pre0"'),
		).toBeLessThan(
			account?.content.indexOf(
				'it("AccountService.withdraw.property-satisfies-0"',
			) ?? -1,
		);
	});

	it("renders a rejects descriptor's property with the configured throws idiom — expect(() => call).toThrow() (ADR-0007)", () => {
		const files = emitPbt();
		const account = accountFile(files);
		expect(account).toBeDefined();
		expect(account?.content).toContain(
			"expect(() => new AccountService().withdraw(amount)).toThrow();",
		);
	});

	it("renders a rejects descriptor's property with the returns idiom — expect(call).toBeNull() (ADR-0007)", () => {
		const files = emitPbt();
		const customer = customerFile(files);
		expect(customer).toBeDefined();
		expect(customer?.content).toContain(
			"expect(new CustomerService().upgrade(newTier)).toBeNull();",
		);
		// The returns descriptor never falls back to throws.
		expect(customer?.content).not.toContain("toThrow");
		// The fast-check import is present in the returns descriptor's file too.
		expect(customer?.content).toContain('import fc from "fast-check";');
	});

	it("renders the full property block layout byte-for-byte — INSTANCE satisfies with positional params, filter line, oracle assertion (GAP 1 + GAP 3)", () => {
		const files = emitPbt();
		const account = accountFile(files);
		expect(account).toBeDefined();

		const block = [
			'\t// traces: "AccountService.withdraw.pre0"',
			'\tit("AccountService.withdraw.property-satisfies-0", () => {',
			"\t\tconst amount = fc.integer({ min: 10, max: 100 });",
			"\t\tconst AccountService_withdraw_pre0 = (amount) => amount >= 10 && amount <= 100;",
			"\t\tconst prop = fc.property(amount.filter(AccountService_withdraw_pre0), (amount) => {",
			"\t\t\tnew AccountService().withdraw(amount);",
			"\t\t\texpect(AccountService_withdraw_pre0(amount)).toBe(true);",
			"\t\t});",
			"\t\tfc.assert(prop, { seed: 123456789, numRuns: 100 });",
			"\t});",
			"",
		].join("\n");
		expect(account?.content).toContain(block);
	});

	it("renders the full property block layout byte-for-byte — STATIC satisfies with positional params (GAP 1)", () => {
		const files = emitPbt();
		const account = accountFile(files);
		expect(account).toBeDefined();

		const block = [
			'\t// traces: "AccountService.setStatus.pre0"',
			'\tit("AccountService.setStatus.property-satisfies-0", () => {',
			'\t\tconst newStatus = fc.constantFrom("ACTIVE", "FROZEN");',
			"\t\tconst notify = fc.boolean();",
			"\t\tconst reason = fc.string();",
			"\t\tconst tags = fc.constant([]);",
			"\t\tconst memo = fc.constant(0);",
			'\t\tconst AccountService_setStatus_pre0 = (newStatus) => newStatus === "ACTIVE" || newStatus === "FROZEN";',
			"\t\tconst prop = fc.property(newStatus.filter(AccountService_setStatus_pre0), notify, reason, tags, memo, (newStatus, notify, reason, tags, memo) => {",
			"\t\t\tAccountService.setStatus(newStatus, notify, reason, tags, memo);",
			"\t\t\texpect(AccountService_setStatus_pre0(newStatus)).toBe(true);",
			"\t\t});",
			"\t\tfc.assert(prop, { seed: -987654321, numRuns: 100 });",
			"\t});",
			"",
		].join("\n");
		expect(account?.content).toContain(block);
	});

	it("renders the committed example's blocks byte-for-byte — instance void call, predicate import oracle, sibling-guarded filters", () => {
		const files = emitPbt();
		const order = orderFile(files);
		expect(order).toBeDefined();

		// `sku != ""` satisfies block: filters sku AND the sibling isPositive
		// guard on price, asserts its own clause.
		const pre0Block = [
			'\t// traces: "OrderService.addItem.pre0"',
			'\tit("OrderService.addItem.property-satisfies-0", () => {',
			"\t\tconst sku = fc.string();",
			"\t\tconst price = fc.integer();",
			'\t\tconst OrderService_addItem_pre0 = (sku) => sku !== "";',
			"\t\tconst OrderService_addItem_pre1 = (price) => isPositive(price);",
			"\t\tconst prop = fc.property(sku.filter(OrderService_addItem_pre0), price.filter(OrderService_addItem_pre1), (sku, price) => {",
			"\t\t\tnew OrderService().addItem(sku, price);",
			"\t\t\texpect(OrderService_addItem_pre0(sku)).toBe(true);",
			"\t\t});",
			"\t\tfc.assert(prop, { seed: 101, numRuns: 100 });",
			"\t});",
			"",
		].join("\n");
		expect(order?.content).toContain(pre0Block);

		// `isPositive(price)` predicateCall satisfies block: same filters,
		// asserts its own clause via the imported predicate.
		const pre1Block = [
			'\t// traces: "OrderService.addItem.pre1"',
			'\tit("OrderService.addItem.property-satisfies-1", () => {',
			"\t\tconst sku = fc.string();",
			"\t\tconst price = fc.integer();",
			'\t\tconst OrderService_addItem_pre0 = (sku) => sku !== "";',
			"\t\tconst OrderService_addItem_pre1 = (price) => isPositive(price);",
			"\t\tconst prop = fc.property(sku.filter(OrderService_addItem_pre0), price.filter(OrderService_addItem_pre1), (sku, price) => {",
			"\t\t\tnew OrderService().addItem(sku, price);",
			"\t\t\texpect(OrderService_addItem_pre1(price)).toBe(true);",
			"\t\t});",
			"\t\tfc.assert(prop, { seed: 202, numRuns: 100 });",
			"\t});",
			"",
		].join("\n");
		expect(order?.content).toContain(pre1Block);
	});

	it("legacy backward-compat for the property path: no methods metadata → the block keeps the options-object static call (mirrors renderCall's meta === undefined branch)", () => {
		const files = emitSuite(pbtSuite(), "vitest", {
			propertyPlan: pbtPlan(),
			propertyNumRuns: 100,
			predicates: PBT_PREDICATES,
		});
		const account = accountFile(files);
		expect(account).toBeDefined();
		// The satisfies property still filters + asserts, but the CALL falls
		// back to the historical static options-object form.
		expect(account?.content).toContain(
			"\t\t\tAccountService.withdraw({ amount });",
		);
		expect(account?.content).toContain(
			"expect(AccountService_withdraw_pre0(amount)).toBe(true);",
		);
		// The instance call form never appears without metadata.
		expect(account?.content).not.toContain(
			"new AccountService().withdraw(amount);",
		);
	});

	it("renders property blocks after each operation's concrete cases, in plan order, across multiple descriptors", () => {
		const files = emitPbt();
		const account = accountFile(files);
		const content = account?.content ?? "";
		const orderContent = orderFile(files)?.content ?? "";

		// withdraw's concrete cases come before its property blocks.
		const boundary0 = content.indexOf(
			'it("AccountService.withdraw.boundary-0 — reject amount below the lower bound"',
		);
		const satisfies = content.indexOf(
			'it("AccountService.withdraw.property-satisfies-0"',
		);
		const invariant = content.indexOf(
			'it("AccountService.withdraw.property-invariant-preserving-0"',
		);
		const rejects = content.indexOf(
			'it("AccountService.withdraw.property-rejects-0"',
		);
		expect(boundary0).toBeGreaterThan(-1);
		expect(satisfies).toBeGreaterThan(-1);
		expect(invariant).toBeGreaterThan(-1);
		expect(rejects).toBeGreaterThan(-1);
		// Property blocks follow the concrete cases for the same operation...
		expect(satisfies).toBeGreaterThan(boundary0);
		// ...and render in plan.descriptors order (satisfies → invariant → rejects).
		expect(invariant).toBeGreaterThan(satisfies);
		expect(rejects).toBeGreaterThan(invariant);

		// setStatus's property block follows setStatus's concrete case.
		const setStatusBoundary = content.indexOf(
			'it("AccountService.setStatus.boundary-0 — accept an allowed status"',
		);
		const setStatusProp = content.indexOf(
			'it("AccountService.setStatus.property-satisfies-0"',
		);
		expect(setStatusBoundary).toBeGreaterThan(-1);
		expect(setStatusProp).toBeGreaterThan(setStatusBoundary);

		// The committed example: addItem's property blocks follow addItem's
		// concrete violation cases, pre0 before pre1 (plan order).
		const addItemViolation = orderContent.indexOf(
			'it("OrderService.addItem.precondition-violation-1 — violates OrderService.addItem.pre1 (predicate isPositive falsified via price)"',
		);
		const addItemPre0 = orderContent.indexOf(
			'it("OrderService.addItem.property-satisfies-0"',
		);
		const addItemPre1 = orderContent.indexOf(
			'it("OrderService.addItem.property-satisfies-1"',
		);
		expect(addItemViolation).toBeGreaterThan(-1);
		expect(addItemPre0).toBeGreaterThan(addItemViolation);
		expect(addItemPre1).toBeGreaterThan(addItemPre0);
	});

	it("determinism: same suite + same property plan → byte-identical emitted files (ADR-0002)", () => {
		const suite = pbtSuite();
		const plan = pbtPlan();

		const first = emitSuite(suite, "vitest", pbtOptions());
		const second = emitSuite(suite, "vitest", pbtOptions());
		expect(second).toEqual(first);
		expect(second.map((file) => file.content)).toEqual(
			first.map((file) => file.content),
		);
	});

	it("the property plan does not leak into the xunit/pytest emitters — they stay byte-identical to no-plan (vitest+fast-check first, ADR-0017)", () => {
		const suite = pbtSuite();
		const plan = pbtPlan();

		expect(emitSuite(suite, "xunit" as never, { propertyPlan: plan })).toEqual(
			emitSuite(suite, "xunit" as never),
		);
		expect(emitSuite(suite, "pytest" as never, { propertyPlan: plan })).toEqual(
			emitSuite(suite, "pytest" as never),
		);
		// The PBT surface is vitest-only — no fast-check, no fc.assert, and no
		// predicate IMPORT anywhere else (the concrete-case description text may
		// legitimately mention a predicate name — only an import line leaks).
		for (const framework of ["xunit", "pytest"] as const) {
			for (const file of emitSuite(suite, framework as never, {
				propertyPlan: plan,
				predicates: PBT_PREDICATES,
			})) {
				expect(file.content).not.toContain("fast-check");
				expect(file.content).not.toContain("fc.assert");
				expect(file.content).not.toContain("import { isPositive }");
			}
		}
	});
});

// ── Fixture type shape self-check (keeps the hand-built IR honest) ─────────
//
// These asserts freeze the fixture so a Phase-3/4 IR reshape fails HERE (the
// emitter test file) instead of silently testing a stale shape.

describe("emitters-pbt fixture integrity", () => {
	it("every property descriptor carries the fields the emitter renders (id, params, clauses, outcome, traces, seed)", () => {
		for (const descriptor of pbtPlan().descriptors) {
			expect(descriptor.id).toMatch(
				/^[A-Za-z]+(\.[A-Za-z]+)+\.property-(satisfies|invariant-preserving|rejects)-\d+$/,
			);
			expect(descriptor.component.length).toBeGreaterThan(0);
			expect(descriptor.operation.length).toBeGreaterThan(0);
			expect(descriptor.params.length).toBeGreaterThan(0);
			expect(descriptor.clauses.length).toBeGreaterThan(0);
			expect(descriptor.traces.length).toBeGreaterThan(0);
			expect(typeof descriptor.seed).toBe("number");
		}
	});

	it("covers every ArbitrarySpec kind the emitter must render (number bounds, number unbounded, enum, string, boolean, list default, optional default)", () => {
		const kinds: ArbitrarySpec[] = pbtPlan().descriptors.flatMap(
			(descriptor) => descriptor.params,
		);
		expect(
			kinds.some((spec) => spec.kind === "number" && spec.bounds !== undefined),
		).toBe(true);
		expect(
			kinds.some((spec) => spec.kind === "number" && spec.bounds === undefined),
		).toBe(true);
		expect(
			kinds.some(
				(spec) => spec.kind === "enum" && (spec.members?.length ?? 0) > 0,
			),
		).toBe(true);
		expect(
			kinds.some(
				(spec) => spec.kind === "string" && spec.default === undefined,
			),
		).toBe(true);
		expect(kinds.some((spec) => spec.kind === "boolean")).toBe(true);
		expect(
			kinds.some(
				(spec) => Array.isArray(spec.default) && spec.default.length === 0,
			),
		).toBe(true);
		expect(kinds.some((spec) => spec.default === 0)).toBe(true);
	});

	it("covers both ADR-0007 rejection idioms across the rejects descriptors", () => {
		const rejects = pbtPlan().descriptors.filter(
			(descriptor) => descriptor.outcome === "rejects",
		);
		expect(rejects.some((d) => d.rejectionIdiom === "throws")).toBe(true);
		expect(rejects.some((d) => d.rejectionIdiom === "returns")).toBe(true);
	});

	it("the OrderService descriptors model the committed example (instance op, positional params in declared order, predicateCall clause)", () => {
		const addItem = pbtPlan().descriptors.filter(
			(descriptor) => descriptor.operation === "addItem",
		);
		expect(addItem).toHaveLength(2);
		for (const descriptor of addItem) {
			expect(descriptor.params.map((spec) => spec.param)).toEqual([
				"sku",
				"price",
			]);
		}
		// The predicateCall clause's code references the registered predicate
		// by its bare name — the emitter MUST import it (GAP 2).
		expect(
			addItem.some((d) => d.clauses.some((c) => c.code.includes("isPositive"))),
		).toBe(true);
		// The string clause's codegen'd form uses strict !== (codegen.ts).
		expect(
			addItem.some((d) => d.clauses.some((c) => c.code.includes('sku !== ""'))),
		).toBe(true);
		// The methods metadata matches the manifest (instance, positional).
		expect(PBT_METHODS.OrderService?.addItem).toEqual({
			static: false,
			params: ["sku", "price"],
			returnType: "void",
		});
	});

	it("the concrete suite fixture carries reject + accept + invariant cases (a meaningful backward-compat baseline)", () => {
		const suite = pbtSuite();
		const all = [
			...suite.operations.flatMap((group) => group.cases),
			...suite.invariantCases,
		];
		expect(all.some((c) => c.expects.outcome === "reject")).toBe(true);
		expect(all.some((c) => c.expects.outcome === "accept")).toBe(true);
		expect(suite.invariantCases.length).toBeGreaterThan(0);
	});
});

// ── W1: real-runner execution gate (why B1 escaped the review) ───────────────
// The Center's final review found B1 precisely because emitters-pbt only
// STRING-pins the emitted layout — nothing ever EXECUTED a generated property
// under a real runner, so a `.filter((a, b) => ...)` broken layout could pass
// review. This gate closes that gap:
//
//   A) EMITS a SINGLE-param compound property block through the REAL pipeline
//      (planTestCases → planPropertyBlocks → emitSuite) and EXECUTES it under
//      the REAL vitest runner in a temp dir (the established emitters.test.ts
//      harness — vitest.mjs under process.execPath; a node_modules symlink to
//      the repo root resolves the generated file's `import fc from
//      "fast-check"`). The runnable layout must exit 0.
//
//   B) A RETAINED-unplannable multi-param descriptor (VERSAILLES-165) is never
//      emitted as a filter: the emitted file for a PROPERTY_UNPLANNABLE clause
//      carries NO fast-check surface, NO fc.property, NO broken multi-param
//      `.filter`. VERSAILLES-165 routes equality-mirrors (`p1 == p2`) and
//      coupled-bounded compounds (`a >= 0 and b >= 0 and a + b <= 100`) to
//      joint sampling, so THIS gate uses the equality-of-sums shape
//      (`a + b == 100`) — a multi-param oracle the planner still classifies
//      unplannable (a thin hyperslice, not a bounded region).
//
// Both pins re-use the fixture style of generator-planner-pbt.test.ts
// (in-memory, fully-loaded, isValid VersaillesContext built from real parsed
// ASTs) so the gate exercises the real generator, not a hand-built IR.

const EXEC_REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const EXEC_EMPTY_MANIFESTS: ManifestsFile = { manifests: {} };
const EXEC_EMPTY_PREDICATES: PredicatesFile = {
	predicates: {},
};

function execConfig(
	propertyBased: WorkspaceConfig["propertyBased"],
): WorkspaceConfig {
	return {
		sourceRoots: ["src/**/*.ts"],
		language: "typescript",
		testFramework: "vitest",
		generatedDir: ".versailles/generated",
		staleness: { blockOnStale: false },
		propertyBased,
	};
}

/** Parses every fixture expr with the real parser (loader-shaped context). */
function execParseAll(contracts: ContractsFile): Record<string, Node> {
	const parsed: Record<string, Node> = {};
	const walk = (clauses: ContractClause[], kind: ClauseKind): void => {
		for (const clause of clauses) {
			const result = parseExpression(clause.expr, kind, clause.id);
			if ("errors" in result) {
				throw new Error(
					`fixture parse failed for ${clause.id}: ${JSON.stringify(result.errors)}`,
				);
			}
			parsed[clause.id] = result.ast;
		}
	};
	for (const component of Object.values(contracts.contracts)) {
		walk(component.invariants ?? [], "invariants");
		for (const operation of Object.values(component.operations ?? {})) {
			walk(operation.preconditions ?? [], "preconditions");
			walk(operation.postconditions ?? [], "postconditions");
		}
	}
	return parsed;
}

function execContext(
	contracts: ContractsFile,
	propertyBased: WorkspaceConfig["propertyBased"],
): VersaillesContext {
	return {
		config: execConfig(propertyBased),
		contracts,
		manifests: EXEC_EMPTY_MANIFESTS,
		predicates: EXEC_EMPTY_PREDICATES,
		parsedContracts: execParseAll(contracts),
		parseErrors: [],
		validationErrors: [],
		validationWarnings: [],
		isValid: true,
	};
}

/** The runnable single-param compound: `x >= 0 and x <= 1000` → `(x) => ...`. */
function execSingleParamContext(): VersaillesContext {
	const contracts: ContractsFile = {
		contracts: {
			OrderService: {
				invariants: [],
				operations: {
					placeOrder: {
						id: "OrderService.placeOrder",
						params: [{ name: "x", type: "number" }],
						preconditions: [
							{
								id: "OrderService.placeOrder.pre0",
								expr: "x >= 0 and x <= 1000",
							},
						],
						postconditions: [],
						effects: [],
						sourceHash: "exec-placeorder-hash",
					},
				},
			},
		},
	};
	return execContext(contracts, { enabled: true, numRuns: 100 });
}

/**
 * The RETAINED-unplannable multi-param compound (VERSAILLES-165): an
 * equality-of-sums oracle `(a, b) => ...` (2 params). The planner classifies
 * multi-param guard oracles instead of blanket-unplannable — equality-mirrors
 * and bounded couplings route to joint sampling, but a sum compared by `==` is
 * a thin hyperslice of the joint space, not a bounded region, so it stays
 * PROPERTY_UNPLANNABLE. (The old coupled-bounded fixture
 * `a >= 0 and b >= 0 and a + b <= 100` is now PLANNED — its record + bounded
 * filter layout is pinned in tests/emitters-pbt-joint.test.ts.)
 */
function execMultiParamContext(): VersaillesContext {
	const contracts: ContractsFile = {
		contracts: {
			OrderService: {
				invariants: [],
				operations: {
					placeOrder: {
						id: "OrderService.placeOrder",
						params: [
							{ name: "a", type: "number" },
							{ name: "b", type: "number" },
						],
						preconditions: [
							{
								id: "OrderService.placeOrder.pre0",
								expr: "a + b == 100",
							},
						],
						postconditions: [],
						effects: [],
						sourceHash: "exec-placeorder-mp-hash",
					},
				},
			},
		},
	};
	return execContext(contracts, { enabled: true, numRuns: 100 });
}

/** Real OrderService source for the W1 runnability pin. */
const EXEC_ORDER_SOURCE = `export class OrderService {
	placeOrder(x: number): number {
		if (x < 0 || x > 1000) throw new Error("out of range");
		return x;
	}
}
`;

/** The REAL vitest runner (vitest.mjs under process.execPath — the established emitters.test.ts harness). */
function execVitestBin(): string {
	return join(EXEC_REPO_ROOT, "node_modules", "vitest", "vitest.mjs");
}

/**
 * The hardened W1 execution helper — spawns the REAL vitest runner in the
 * temp workspace (shared harness hardening with emitters-pbt-joint.test.ts:
 * the spawned runner can transiently die on startup under load — spawn
 * timeout / no summary — while the generated property itself is fine). A
 * GENUINE test failure always prints the "Test Files ... failed" summary, so:
 *   - exit 0 → success, return immediately;
 *   - a run with NO vitest summary (or killed by the 60s timeout) is a
 *     harness flake → retry (up to attempts);
 *   - a run that SUMMARIZED a failure is real → never retried.
 */
function execVitestRun(
	root: string,
	attempts = 3,
): { status: number | null; stdout: string; stderr: string } {
	let last: { status: number | null; stdout: string; stderr: string } = {
		status: null,
		stdout: "",
		stderr: "",
	};
	for (let attempt = 0; attempt < attempts; attempt++) {
		const run = spawnSync(process.execPath, [execVitestBin(), "run"], {
			cwd: root,
			encoding: "utf8",
			timeout: 60_000,
		});
		last = {
			status: run.status,
			stdout: run.stdout ?? "",
			stderr: run.stderr ?? "",
		};
		if (run.status === 0) {
			return last;
		}
		const summarized = /\d+ failed/.test(last.stdout);
		if (!summarized && attempt < attempts - 1) {
			continue;
		}
		return last;
	}
	return last;
}

describe("emitted PBT — the single-param compound property RUNS under the REAL vitest runner (W1 execution gate)", () => {
	it("executes an emitted single-param compound property — exit 0, no filter hang (Red today would be a broken/vacuous filter layout)", async () => {
		const ctx = execSingleParamContext();
		const suite = planTestCases(ctx);
		const plan = planPropertyBlocks(suite, ctx);

		// Planner pin: the single-param compound IS planned (no warning).
		expect(plan.warnings).toEqual([]);
		expect(plan.descriptors).toHaveLength(1);
		expect(plan.descriptors[0].clauses[0].code).toBe(
			"(x) => x >= 0 && x <= 1000",
		);

		const root = await mkdtemp(join(tmpdir(), "versailles-pbt-exec-"));
		try {
			// fast-check must resolve from the generated file's directory — the
			// node_modules symlink to the repo root (same resolution the
			// committed examples/order-service workspace gets from its own
			// node_modules).
			await symlink(
				join(EXEC_REPO_ROOT, "node_modules"),
				join(root, "node_modules"),
				"dir",
			);
			await writeFile(join(root, "order.ts"), `${EXEC_ORDER_SOURCE}\n`, "utf8");

			const files = emitSuite(suite, "vitest", {
				generatedDir: ".",
				modulePaths: { OrderService: "./order" },
				methods: {
					OrderService: {
						placeOrder: {
							static: false,
							params: ["x"],
							returnType: "number",
						},
					},
				},
				propertyPlan: plan,
				propertyNumRuns: 100,
			});
			const order = files.find((file) =>
				file.path.endsWith("OrderService.test.ts"),
			);
			expect(order).toBeDefined();

			// The string pin: the SINGLE-param filter layout — the runnable
			// form (a multi-param `.filter((a, b) => ...)` would be the B1 bug).
			expect(order?.content).toContain(
				"fc.property(x.filter(OrderService_placeOrder_pre0), (x) => {",
			);
			expect(order?.content).toContain(
				"expect(OrderService_placeOrder_pre0(x)).toBe(true);",
			);

			await writeFile(
				join(root, "OrderService.test.ts"),
				order?.content ?? "",
				"utf8",
			);

			// EXECUTE under the real vitest runner — the W1 gate that string
			// pins alone cannot provide. The bounded arbitrary + single-param
			// filter must run 100 seeded runs green.
			const run = execVitestRun(root);
			expect(
				run.status,
				`emitted single-param compound property did not run clean:\n${run.stdout}\n${run.stderr}`,
			).toBe(0);
			// The runner SUMMARY must independently show zero failures.
			expect(run.stdout).not.toMatch(/\d+ failed/);
		} finally {
			await rm(root, { recursive: true, force: true });
		}
	});

	it("the retained-unplannable multi-param descriptor is NEVER emitted as a filter — its emitted file carries no fc.property surface (W1)", async () => {
		const ctx = execMultiParamContext();
		const suite = planTestCases(ctx);
		const plan = planPropertyBlocks(suite, ctx);

		// Planner pin: the 2-param equality-of-sums oracle is
		// PROPERTY_UNPLANNABLE (VERSAILLES-165 — it is not an equality-mirror
		// and not a bounded coupling, so the joint-sampling router rejects it).
		const pre0Ast = ctx.parsedContracts["OrderService.placeOrder.pre0"];
		expect(pre0Ast).toBeDefined();
		expect(renderClausePredicate(pre0Ast)).toBe("(a, b) => a + b === 100");
		const warning = plan.warnings.find(
			(w) => w.field === "OrderService.placeOrder.pre0",
		);
		expect(warning).toBeDefined();
		expect(warning?.code).toBe("PROPERTY_UNPLANNABLE");
		expect(plan.descriptors).toEqual([]);

		// Emit pin: no descriptor ⇒ no fast-check surface, no fc.property, no
		// broken multi-param `.filter((a, b) => ...)` layout (the B1 bug shape).
		const files = emitSuite(suite, "vitest", {
			propertyPlan: plan,
			propertyNumRuns: 100,
		});
		const order = files.find((file) =>
			file.path.endsWith("OrderService.test.ts"),
		);
		expect(order).toBeDefined();
		expect(order?.content).not.toContain("fast-check");
		expect(order?.content).not.toContain("fc.property");
		expect(order?.content).not.toContain("a.filter(");
		expect(order?.content).not.toContain("a + b === 100");
	});
});

// ── Single-param-only reality pin for the emitters-pbt fixture ───────────────
// The pinned emitted layout filters each arbitrary with a per-param oracle
// (`.filter(<oracle>)` — fast-check's filter passes exactly ONE value), so
// every oracle this file's hand-built plan embeds as a filter/assert must be
// SINGLE-param. Under VERSAILLES-165 a multi-param guard oracle routes to a
// joint-sampling strategy (equality-mirror / FIELD-BOUND / record + bounded
// filter) whose layouts are pinned separately in tests/emitters-pbt-joint.test.ts
// — this fixture intentionally models the committed example (addItem etc.),
// which is entirely single-param. This integrity pin catches a future fixture
// that sneaks a multi-param oracle into a satisfies/invariant-preserving
// descriptor.

describe("emitters-pbt fixture integrity — single-param-only oracles (Center B1)", () => {
	it("every satisfies/invariant-preserving oracle in the pinned plan has exactly ONE callback param — rejects blocks are exempt (they never embed filters)", () => {
		for (const descriptor of pbtPlan().descriptors) {
			if (descriptor.outcome === "rejects") {
				continue;
			}
			for (const clause of descriptor.clauses) {
				const arrow = clause.code.indexOf(") => ");
				expect(arrow).toBeGreaterThan(-1);
				const head = clause.code.slice(1, arrow);
				const params =
					head.trim() === ""
						? []
						: head.split(", ").map((param) => param.trim());
				expect(
					params.length,
					`oracle ${clause.clauseId} must be single-param (the pinned per-param .filter layout embeds single-param guard oracles only; multi-param oracles route to the joint layouts pinned in emitters-pbt-joint.test.ts): ${clause.code}`,
				).toBe(1);
			}
		}
	});
});
