import { describe, expect, it } from "vitest";

import { emitSuite } from "../packages/engine/src/generator/index.js";
import type {
	ArbitrarySpec,
	EmitOptions,
	PlannedCase,
	PlannedSuite,
	PropertyClause,
	PropertyDescriptor,
	PropertyPlan,
} from "../packages/engine/src/generator/index.js";

/**
 * Seeded PBT emission — the vitest property-block emitter (ADR-0017 Phase 5,
 * build-spec §9.6 + deterministic-generation.contract.yaml `emit_case` /
 * `plan_property_blocks`). Pinned against the PBT IR shipped in Phase 3
 * (ir.ts: PropertyOutcome / ArbitrarySpec / PropertyClause / PropertyDescriptor
 * / PropertyPlan), the seed helper (seed.ts: derivePropertySeed), the strategy
 * selector (Phase 4), and the property-block planner (Phase 4: planPropertyBlocks
 * in planner.ts). The EMITTER does NOT render property blocks yet — every
 * enabled=true test in this file is Red until the implementer lands the render.
 *
 * ── The emitter seam (what these tests pin) ─────────────────────────────────
 *
 * The property plan reaches the emitter through the EXISTING emitSuite options
 * seam — the same thread that already carries generatedDir / modulePaths /
 * methods (Center W4). The generate pipeline (src/cli/handlers/generate.ts)
 * computes `planPropertyBlocks(suite, context)` and passes the plan plus the
 * configured run count into emitSuite:
 *
 * ```ts
 * // packages/engine/src/generator/ir.ts — EmitOptions gains two OPTIONAL fields:
 * export type EmitOptions = {
 *   generatedDir?: string;
 *   modulePaths?: Record<string, string>;
 *   methods?: ...;
 *   propertyPlan?: PropertyPlan;   // ← NEW: planPropertyBlocks(suite, context)
 *   propertyNumRuns?: number;      // ← NEW: config.propertyBased.numRuns (default 100)
 * };
 * ```
 *
 * Why this seam (not a separate emitPropertyBlocks call, not a signature
 * widening): emitSuite is already the only public emit seam, the plan is
 * additive IR like methods/modulePaths, and the enabled=false path is
 * byte-identical by construction — absent/empty propertyPlan renders nothing
 * new. `propertyNumRuns` carries `config.propertyBased.numRuns` (default 100,
 * build-spec §9.6) because PropertyPlan does NOT carry it (Phase 4 pinned the
 * plan shape { descriptors, strategies, warnings }); threading it as an option
 * mirrors how rejection idiom / methods / modulePaths flow today.
 *
 * Only the vitest emitter reads these fields (ADR-0017 "vitest + fast-check
 * first behind the ADR-0009 seam") — xunit/pytest ignore them and stay
 * byte-identical.
 *
 * ── The pinned emitted layout (exact bytes the implementer MUST produce) ────
 *
 * File header — the v1 concrete header is preserved byte-for-byte; when the
 * component has at least one property descriptor, the fast-check import is
 * added immediately after the component import:
 *
 * ```ts
 * // Auto-generated by the Versailles deterministic generator core.
 * // Do not edit — regenerate with `versailles generate`.
 * // traces: "AccountService.inv0", "AccountService.withdraw.pre0", ...
 * import { describe, expect, it } from "vitest";
 *
 * import { AccountService } from "../../src/AccountService.js";
 * import { fc } from "fast-check";
 * ```
 *
 * Property blocks render INSIDE the operation's describe, AFTER that
 * operation's concrete cases, in plan.descriptors order. One block per
 * descriptor, sharing the concrete case's traceability-comment convention
 * (§9.3 — a `// traces: <JSON-stringified ids>` line, tab-indented above the
 * it):
 *
 * ```ts
 * describe("withdraw", () => {
 *   // ...concrete cases unchanged...
 *
 *   // traces: "AccountService.withdraw.pre0"
 *   it("AccountService.withdraw.property-satisfies-0", () => {
 *     const amount = fc.integer({ min: 10, max: 100 });
 *     const prop = fc.property(amount, (amount) => {
 *       const AccountService_withdraw_pre0 = (amount) => amount >= 10 && amount <= 100;
 *       const result = AccountService.withdraw({ amount });
 *       expect(result).toBeDefined();
 *     });
 *     fc.assert(prop, { seed: 123456789, numRuns: 100 });
 *   });
 * });
 * ```
 *
 * Per-param arbitraries (ArbitrarySpec → fc call):
 *   kind "number" + bounds → `fc.integer({ min, max })`
 *   kind "number" (no bounds) → `fc.integer()`
 *   kind "enum"   → `fc.constantFrom(<members>)`   (members via renderValue)
 *   kind "string" → `fc.string()`
 *   kind "boolean"→ `fc.boolean()`
 *   default present (list<X>/optional<X>) → `fc.constant(<default>)` —
 *     e.g. `fc.constant([])` for a list default, `fc.constant(0)` for an
 *     optional<number> default (the deterministic default IS the constant).
 *
 * Clause predicates embed VERBATIM as executable JS inside the prop callback:
 * `const <sanitized-clause-id> = <PropertyClause.code>;` — the exact
 * arrow-function source from codegen.ts fills the right-hand side (sanitized
 * clause id via the shared sanitizeId convention, e.g.
 * "AccountService.withdraw.pre0" → AccountService_withdraw_pre0).
 *
 * Rejection idiom (ADR-0007) comes from the descriptor's `rejectionIdiom`
 * field, exactly like the concrete cases read case_.expects.rejectionIdiom:
 *   "throws"  → `expect(() => <Component>.<op>({ <params> })).toThrow();`
 *   "returns" → `expect(<Component>.<op>({ <params> })).toBeNull();`
 *
 * The call uses the legacy options-object form `<Component>.<op>({ <param>,
 * ... })` with the callback param names (the deterministic default; the
 * metadata-driven positional form is out of scope for the property path).
 *
 * fc.assert options render `{ seed: <seed literal>, numRuns: <propertyNumRuns> }`
 * with a space after the comma; seed via String(descriptor.seed) (int32, may be
 * negative), numRuns via String (default 100 when the option is absent).
 */

// ── Fixture: a concrete suite + a property plan (hand-built, mirroring what
// planTestCases + planPropertyBlocks produce for the same contract). ─────────

const ACCOUNT = "AccountService";
const CUSTOMER = "CustomerService";

/** A concrete PlannedSuite (the Phase-1/2 output shape, hand-built). */
function pbtSuite(): PlannedSuite {
	return {
		clauseIds: [
			`${ACCOUNT}.inv0`,
			`${ACCOUNT}.withdraw.pre0`,
			`${ACCOUNT}.withdraw.post0`,
			`${ACCOUNT}.setStatus.pre0`,
			`${CUSTOMER}.upgrade.pre0`,
		],
		operations: [
			{
				component: ACCOUNT,
				operation: "withdraw",
				cases: [
					{
						id: `${ACCOUNT}.withdraw.boundary-0`,
						kind: "boundary",
						description: "reject amount below the lower bound",
						inputs: { amount: 9 },
						expects: { outcome: "reject", rejectionIdiom: "throws" },
						traces: [`${ACCOUNT}.withdraw.pre0`],
					},
					{
						id: `${ACCOUNT}.withdraw.boundary-1`,
						kind: "boundary",
						description: "accept an in-range amount",
						inputs: { amount: 50 },
						expects: { outcome: "accept" },
						traces: [`${ACCOUNT}.withdraw.pre0`],
					},
				],
			},
			{
				component: ACCOUNT,
				operation: "setStatus",
				cases: [
					{
						id: `${ACCOUNT}.setStatus.boundary-0`,
						kind: "boundary",
						description: "accept an allowed status",
						inputs: { newStatus: "ACTIVE" },
						expects: { outcome: "accept" },
						traces: [`${ACCOUNT}.setStatus.pre0`],
					},
				],
			},
			{
				component: CUSTOMER,
				operation: "upgrade",
				cases: [
					{
						id: `${CUSTOMER}.upgrade.boundary-0`,
						kind: "boundary",
						description: "accept an allowed tier",
						inputs: { newTier: "GOLD" },
						expects: { outcome: "accept" },
						traces: [`${CUSTOMER}.upgrade.pre0`],
					},
				],
			},
		],
		invariantCases: [
			{
				id: `${ACCOUNT}.withdraw.invariant-0`,
				kind: "invariant",
				description: "balance stays non-negative after withdraw",
				inputs: { amount: 50, balance: 50 },
				expects: { outcome: "accept" },
				traces: [`${ACCOUNT}.inv0`],
			},
		],
	};
}

/**
 * The property plan the implementer's emitter must render. Order mirrors the
 * planner's deterministic per-operation traversal (preconditions satisfies →
 * invariants invariant-preserving → expected-rejection rejects, per operation
 * in component order): AccountService.withdraw clauses, then setStatus, then
 * CustomerService.upgrade.
 */
function pbtPlan(): PropertyPlan {
	return {
		descriptors: [
			{
				// Compound precondition `amount >= 10 and amount <= 100` → the
				// codegen'd oracle (codegen.ts: (amount) => amount >= 10 &&
				// amount <= 100) + compound-aware numeric bounds.
				id: `${ACCOUNT}.withdraw.property-satisfies-0`,
				component: ACCOUNT,
				operation: "withdraw",
				params: [
					{
						param: "amount",
						typeRef: "number",
						kind: "number",
						bounds: { min: 10, max: 100 },
					},
				],
				clauses: [
					{
						clauseId: `${ACCOUNT}.withdraw.pre0`,
						code: "(amount) => amount >= 10 && amount <= 100",
					},
				],
				outcome: "satisfies",
				traces: [`${ACCOUNT}.withdraw.pre0`],
				seed: 123456789,
			},
			{
				// Invariant-preserving: oracle is the codegen'd invariant. The
				// post-call assertion semantics (asserting the oracle against
				// post-call state) are the implementer's design space — this
				// pin fixes the embedding + uniform non-rejects layout.
				id: `${ACCOUNT}.withdraw.property-invariant-preserving-0`,
				component: ACCOUNT,
				operation: "withdraw",
				params: [
					{
						param: "amount",
						typeRef: "number",
						kind: "number",
						bounds: { min: 10, max: 100 },
					},
				],
				clauses: [
					{
						clauseId: `${ACCOUNT}.inv0`,
						code: "(balance) => balance >= 0",
					},
				],
				outcome: "invariant-preserving",
				traces: [`${ACCOUNT}.inv0`],
				seed: 555,
			},
			{
				// Expected-rejection with the DEFAULT idiom (throws).
				id: `${ACCOUNT}.withdraw.property-rejects-0`,
				component: ACCOUNT,
				operation: "withdraw",
				params: [
					{
						param: "amount",
						typeRef: "number",
						kind: "number",
						bounds: { min: 0, max: 9 },
					},
				],
				clauses: [
					{
						clauseId: `${ACCOUNT}.withdraw.pre0`,
						code: "(amount) => amount >= 10",
					},
				],
				outcome: "rejects",
				rejectionIdiom: "throws",
				traces: [`${ACCOUNT}.withdraw.pre0`],
				seed: 42,
			},
			{
				// Satisfies over enum + boolean + string + list + optional
				// params — every ArbitrarySpec kind in one block. Negative
				// int32 seed (derivePropertySeed round-trips through seed | 0).
				id: `${ACCOUNT}.setStatus.property-satisfies-0`,
				component: ACCOUNT,
				operation: "setStatus",
				params: [
					{
						param: "newStatus",
						typeRef: "enum<ACTIVE,FROZEN>",
						kind: "enum",
						members: ["ACTIVE", "FROZEN"],
					},
					{ param: "notify", typeRef: "boolean", kind: "boolean" },
					{ param: "reason", typeRef: "string", kind: "string" },
					{
						param: "tags",
						typeRef: "list<string>",
						kind: "string",
						default: [],
					},
					{
						param: "memo",
						typeRef: "optional<number>",
						kind: "number",
						default: 0,
					},
				],
				clauses: [
					{
						clauseId: `${ACCOUNT}.setStatus.pre0`,
						code: '(newStatus) => newStatus === "ACTIVE" || newStatus === "FROZEN"',
					},
				],
				outcome: "satisfies",
				traces: [`${ACCOUNT}.setStatus.pre0`],
				seed: -987654321,
			},
			{
				// Expected-rejection with the CONFIGURED returns idiom.
				id: `${CUSTOMER}.upgrade.property-rejects-0`,
				component: CUSTOMER,
				operation: "upgrade",
				params: [
					{
						param: "newTier",
						typeRef: "enum<GOLD,SILVER>",
						kind: "enum",
						members: ["GOLD", "SILVER"],
					},
				],
				clauses: [
					{
						clauseId: `${CUSTOMER}.upgrade.pre0`,
						code: "(newTier) => newTier !== null",
					},
				],
				outcome: "rejects",
				rejectionIdiom: "returns",
				traces: [`${CUSTOMER}.upgrade.pre0`],
				seed: 7,
			},
		],
		strategies: {},
		warnings: [],
	};
}

function accountFile(files: ReturnType<typeof emitSuite>) {
	return files.find((file) => file.path.endsWith("AccountService.test.ts"));
}

function customerFile(files: ReturnType<typeof emitSuite>) {
	return files.find((file) => file.path.endsWith("CustomerService.test.ts"));
}

describe("emitSuite vitest — property-block emitter (ADR-0017 §9.6, deterministic-generation.contract.yaml)", () => {
	it("enabled=false backward-compat pin: no propertyPlan (or empty plan) → byte-identical to today's concrete-case output — no fast-check import, no fc.assert blocks", () => {
		const suite = pbtSuite();
		// The v1 baseline from today's emitter (pure function of the suite).
		const baseline = emitSuite(suite, "vitest");
		expect(baseline.length).toBeGreaterThan(0);
		// No plan → byte-identical (the emitter ignores the absent plan).
		expect(emitSuite(suite, "vitest", {})).toEqual(baseline);
		// Empty plan → byte-identical (no descriptors ⇒ no property blocks).
		const emptyPlan: PropertyPlan = {
			descriptors: [],
			strategies: {},
			warnings: [],
		};
		expect(emitSuite(suite, "vitest", { propertyPlan: emptyPlan })).toEqual(
			baseline,
		);
		expect(
			emitSuite(suite, "vitest", {
				propertyPlan: emptyPlan,
				propertyNumRuns: 100,
			}),
		).toEqual(baseline);
		// The pinned invariant: disabled output has no PBT surface at all.
		for (const file of baseline) {
			expect(file.content).not.toContain("fast-check");
			expect(file.content).not.toContain("fc.assert");
			expect(file.content).not.toContain("fc.");
		}
	});

	it("pins the emit seam type: EmitOptions carries the property plan and numRuns", () => {
		// Typecheck-only pin (mirrors V1_EMITTER_FRAMEWORKS in
		// tests/emitters.test.ts): this const compiles only once EmitOptions
		// gains propertyPlan + propertyNumRuns (the ir.ts seam change).
		const options: EmitOptions = {
			propertyPlan: { descriptors: [], strategies: {}, warnings: [] },
			propertyNumRuns: 100,
		};
		expect(options.propertyNumRuns).toBe(100);
		expect(options.propertyPlan?.descriptors).toEqual([]);
	});

	it("enabled=true: renders the fast-check import and an fc.assert block for a compound descriptor", () => {
		const files = emitSuite(pbtSuite(), "vitest", {
			propertyPlan: pbtPlan(),
			propertyNumRuns: 100,
		});
		const account = accountFile(files);
		expect(account).toBeDefined();
		// The fast-check import appears in the header, after the component import.
		expect(account?.content).toContain('import { fc } from "fast-check";');
		// The compound satisfies descriptor renders an fc.assert block.
		expect(account?.content).toContain(
			'it("AccountService.withdraw.property-satisfies-0", () => {',
		);
		expect(account?.content).toContain(
			"fc.assert(prop, { seed: 123456789, numRuns: 100 });",
		);
		// The concrete cases remain present (additive, never replacing).
		expect(account?.content).toContain(
			'it("AccountService.withdraw.boundary-0 — reject amount below the lower bound"',
		);
	});

	it("renders the seed literal and numRuns exactly in the fc.assert options — default 100, configured override, negative int32 seed", () => {
		// Config override: propertyNumRuns 250 threads into every block.
		const files = emitSuite(pbtSuite(), "vitest", {
			propertyPlan: pbtPlan(),
			propertyNumRuns: 250,
		});
		const account = accountFile(files);
		expect(account?.content).toContain(
			"fc.assert(prop, { seed: 123456789, numRuns: 250 });",
		);
		expect(account?.content).toContain(
			"fc.assert(prop, { seed: 555, numRuns: 250 });",
		);
		expect(account?.content).toContain(
			"fc.assert(prop, { seed: 42, numRuns: 250 });",
		);
		expect(account?.content).toContain(
			"fc.assert(prop, { seed: -987654321, numRuns: 250 });",
		);

		// Default 100 when propertyNumRuns is absent (build-spec §9.6).
		const defaulted = emitSuite(pbtSuite(), "vitest", {
			propertyPlan: pbtPlan(),
		});
		const accountDefaulted = accountFile(defaulted);
		expect(accountDefaulted?.content).toContain(
			"fc.assert(prop, { seed: 123456789, numRuns: 100 });",
		);
	});

	it("renders per-kind arbitraries: fc.integer bounds, fc.constantFrom, fc.string, fc.boolean, fc.constant([]) list default, fc.constant(0) optional default", () => {
		const files = emitSuite(pbtSuite(), "vitest", {
			propertyPlan: pbtPlan(),
			propertyNumRuns: 100,
		});
		const account = accountFile(files);
		expect(account).toBeDefined();

		// number with bounds → fc.integer({ min, max })
		expect(account?.content).toContain(
			"const amount = fc.integer({ min: 10, max: 100 });",
		);
		// enum → fc.constantFrom over the members
		expect(account?.content).toContain(
			'const newStatus = fc.constantFrom("ACTIVE", "FROZEN");',
		);
		// boolean → fc.boolean()
		expect(account?.content).toContain("const notify = fc.boolean();");
		// string → fc.string()
		expect(account?.content).toContain("const reason = fc.string();");
		// list<X> default [] → the deterministic constant arbitrary
		expect(account?.content).toContain("const tags = fc.constant([]);");
		// optional<number> default 0 → the deterministic constant arbitrary
		expect(account?.content).toContain("const memo = fc.constant(0);");
	});

	it("embeds the codegen'd clause predicates as executable JS — the exact PropertyClause.code arrow-function source appears verbatim", () => {
		const files = emitSuite(pbtSuite(), "vitest", {
			propertyPlan: pbtPlan(),
			propertyNumRuns: 100,
		});
		const account = accountFile(files);
		expect(account).toBeDefined();

		// The exact arrow-function source from codegen.ts fills the const.
		expect(account?.content).toContain(
			"const AccountService_withdraw_pre0 = (amount) => amount >= 10 && amount <= 100;",
		);
		expect(account?.content).toContain(
			'const AccountService_setStatus_pre0 = (newStatus) => newStatus === "ACTIVE" || newStatus === "FROZEN";',
		);
		// The codegen'd source string itself appears verbatim (no mangling).
		expect(account?.content).toContain(
			"(amount) => amount >= 10 && amount <= 100",
		);
	});

	it("places a §9.3 traceability comment above each property block (tab-indented, JSON-stringified clause ids)", () => {
		const files = emitSuite(pbtSuite(), "vitest", {
			propertyPlan: pbtPlan(),
			propertyNumRuns: 100,
		});
		const account = accountFile(files);
		expect(account).toBeDefined();

		// The per-block trace comment is tab-indented (inside the describe),
		// which distinguishes it from the file-header `// traces:` line.
		expect(account?.content).toContain(
			'\t// traces: "AccountService.withdraw.pre0"',
		);
		expect(account?.content).toContain('\t// traces: "AccountService.inv0"');
		expect(account?.content).toContain(
			'\t// traces: "AccountService.setStatus.pre0"',
		);
		// The trace comment sits immediately above its property block.
		expect(
			account?.content.indexOf('\t// traces: "AccountService.withdraw.pre0"'),
		).toBeLessThan(
			account?.content.indexOf(
				'it("AccountService.withdraw.property-satisfies-0"',
			) ?? -1,
		);
	});

	it("renders a rejects descriptor's property with the configured throws idiom — expect(() => call).toThrow() (ADR-0007)", () => {
		const files = emitSuite(pbtSuite(), "vitest", {
			propertyPlan: pbtPlan(),
			propertyNumRuns: 100,
		});
		const account = accountFile(files);
		expect(account).toBeDefined();
		expect(account?.content).toContain(
			"expect(() => AccountService.withdraw({ amount })).toThrow();",
		);
	});

	it("renders a rejects descriptor's property with the returns idiom — expect(call).toBeNull() (ADR-0007)", () => {
		const files = emitSuite(pbtSuite(), "vitest", {
			propertyPlan: pbtPlan(),
			propertyNumRuns: 100,
		});
		const customer = customerFile(files);
		expect(customer).toBeDefined();
		expect(customer?.content).toContain(
			"expect(CustomerService.upgrade({ newTier })).toBeNull();",
		);
		// The returns descriptor never falls back to throws.
		expect(customer?.content).not.toContain("toThrow");
		// The fast-check import is present in the returns descriptor's file too.
		expect(customer?.content).toContain('import { fc } from "fast-check";');
	});

	it("renders the full property block layout byte-for-byte (the §9.6 contract shape)", () => {
		const files = emitSuite(pbtSuite(), "vitest", {
			propertyPlan: pbtPlan(),
			propertyNumRuns: 100,
		});
		const account = accountFile(files);
		expect(account).toBeDefined();

		const block = [
			'\t// traces: "AccountService.withdraw.pre0"',
			'\tit("AccountService.withdraw.property-satisfies-0", () => {',
			"\t\tconst amount = fc.integer({ min: 10, max: 100 });",
			"\t\tconst prop = fc.property(amount, (amount) => {",
			"\t\t\tconst AccountService_withdraw_pre0 = (amount) => amount >= 10 && amount <= 100;",
			"\t\t\tconst result = AccountService.withdraw({ amount });",
			"\t\t\texpect(result).toBeDefined();",
			"\t\t});",
			"\t\tfc.assert(prop, { seed: 123456789, numRuns: 100 });",
			"\t});",
			"",
		].join("\n");
		expect(account?.content).toContain(block);
	});

	it("renders property blocks after each operation's concrete cases, in plan order, across multiple descriptors", () => {
		const files = emitSuite(pbtSuite(), "vitest", {
			propertyPlan: pbtPlan(),
			propertyNumRuns: 100,
		});
		const account = accountFile(files);
		const content = account?.content ?? "";

		// withdraw's concrete cases come before its property blocks.
		const boundary0 = content.indexOf(
			'it("AccountService.withdraw.boundary-0 — reject amount below the lower bound"',
		);
		const satisfies = content.indexOf(
			'it("AccountService.withdraw.property-satisfies-0"',
		);
		const invariant = content.indexOf(
			'it("AccountService.withdraw.property-invariant-preserving-0"',
		);
		const rejects = content.indexOf(
			'it("AccountService.withdraw.property-rejects-0"',
		);
		expect(boundary0).toBeGreaterThan(-1);
		expect(satisfies).toBeGreaterThan(-1);
		expect(invariant).toBeGreaterThan(-1);
		expect(rejects).toBeGreaterThan(-1);
		// Property blocks follow the concrete cases for the same operation...
		expect(satisfies).toBeGreaterThan(boundary0);
		// ...and render in plan.descriptors order (satisfies → invariant → rejects).
		expect(invariant).toBeGreaterThan(satisfies);
		expect(rejects).toBeGreaterThan(invariant);

		// setStatus's property block follows setStatus's concrete case.
		const setStatusBoundary = content.indexOf(
			'it("AccountService.setStatus.boundary-0 — accept an allowed status"',
		);
		const setStatusProp = content.indexOf(
			'it("AccountService.setStatus.property-satisfies-0"',
		);
		expect(setStatusBoundary).toBeGreaterThan(-1);
		expect(setStatusProp).toBeGreaterThan(setStatusBoundary);
	});

	it("determinism: same suite + same property plan → byte-identical emitted files (ADR-0002)", () => {
		const suite = pbtSuite();
		const plan = pbtPlan();

		const first = emitSuite(suite, "vitest", {
			propertyPlan: plan,
			propertyNumRuns: 100,
		});
		const second = emitSuite(suite, "vitest", {
			propertyPlan: plan,
			propertyNumRuns: 100,
		});
		expect(second).toEqual(first);
		expect(second.map((file) => file.content)).toEqual(
			first.map((file) => file.content),
		);
	});

	it("the property plan does not leak into the xunit/pytest emitters — they stay byte-identical to no-plan (vitest+fast-check first, ADR-0017)", () => {
		const suite = pbtSuite();
		const plan = pbtPlan();

		expect(emitSuite(suite, "xunit" as never, { propertyPlan: plan })).toEqual(
			emitSuite(suite, "xunit" as never),
		);
		expect(emitSuite(suite, "pytest" as never, { propertyPlan: plan })).toEqual(
			emitSuite(suite, "pytest" as never),
		);
		// The PBT surface is vitest-only — no fast-check anywhere else.
		for (const framework of ["xunit", "pytest"] as const) {
			for (const file of emitSuite(suite, framework as never, {
				propertyPlan: plan,
			})) {
				expect(file.content).not.toContain("fast-check");
				expect(file.content).not.toContain("fc.assert");
			}
		}
	});
});

// ── Fixture type shape self-check (keeps the hand-built IR honest) ─────────
//
// These asserts freeze the fixture so a Phase-3/4 IR reshape fails HERE (the
// emitter test file) instead of silently testing a stale shape.

describe("emitters-pbt fixture integrity", () => {
	it("every property descriptor carries the fields the emitter renders (id, params, clauses, outcome, traces, seed)", () => {
		for (const descriptor of pbtPlan().descriptors) {
			expect(descriptor.id).toMatch(
				/^[A-Za-z]+(\.[A-Za-z]+)+\.property-(satisfies|invariant-preserving|rejects)-\d+$/,
			);
			expect(descriptor.component.length).toBeGreaterThan(0);
			expect(descriptor.operation.length).toBeGreaterThan(0);
			expect(descriptor.params.length).toBeGreaterThan(0);
			expect(descriptor.clauses.length).toBeGreaterThan(0);
			expect(descriptor.traces.length).toBeGreaterThan(0);
			expect(typeof descriptor.seed).toBe("number");
		}
	});

	it("covers every ArbitrarySpec kind the emitter must render (number, enum, string, boolean, list default, optional default)", () => {
		const kinds: ArbitrarySpec[] = pbtPlan().descriptors.flatMap(
			(descriptor) => descriptor.params,
		);
		expect(
			kinds.some((spec) => spec.kind === "number" && spec.bounds !== undefined),
		).toBe(true);
		expect(
			kinds.some(
				(spec) => spec.kind === "enum" && (spec.members?.length ?? 0) > 0,
			),
		).toBe(true);
		expect(
			kinds.some(
				(spec) => spec.kind === "string" && spec.default === undefined,
			),
		).toBe(true);
		expect(kinds.some((spec) => spec.kind === "boolean")).toBe(true);
		expect(
			kinds.some(
				(spec) => Array.isArray(spec.default) && spec.default.length === 0,
			),
		).toBe(true);
		expect(kinds.some((spec) => spec.default === 0)).toBe(true);
	});

	it("covers both ADR-0007 rejection idioms across the rejects descriptors", () => {
		const rejects = pbtPlan().descriptors.filter(
			(descriptor) => descriptor.outcome === "rejects",
		);
		expect(rejects.some((d) => d.rejectionIdiom === "throws")).toBe(true);
		expect(rejects.some((d) => d.rejectionIdiom === "returns")).toBe(true);
	});

	it("the concrete suite fixture carries reject + accept + invariant cases (a meaningful backward-compat baseline)", () => {
		const suite = pbtSuite();
		const all = [
			...suite.operations.flatMap((group) => group.cases),
			...suite.invariantCases,
		];
		expect(all.some((c) => c.expects.outcome === "reject")).toBe(true);
		expect(all.some((c) => c.expects.outcome === "accept")).toBe(true);
		expect(suite.invariantCases.length).toBeGreaterThan(0);
	});
});
