/**
 * The vitest emitter plugin (ADR-0008/0009) — the ONLY framework rendering in
 * the generator core. Renders the framework-agnostic IR into full `.test.ts`
 * files ready for idempotent full-file regeneration (build-spec §9.4).
 *
 * The emitter is a pure function of the suite: same suite in, byte-identical
 * file content out. Rejection assertions are rendered from the case's
 * configured idiom ("throws" → expect(() => op(inputs)).toThrow();
 * "returns" → expect(op(inputs)).toBeNull()) — never hardcoded (ADR-0007).
 *
 * Call rendering is shape-aware from manifest method metadata
 * (deterministic-generation.contract.yaml §9.4, VERSAILLES-20 F1): instance
 * methods render `new <Component>().<op>(<positional>)`, static methods render
 * `<Component>.<op>(<positional>)` with params in declared order, and
 * void-return accept cases carry no return-value assertion. Accept/invariant
 * cases on a void-returning INSTANCE operation WITH assertions bind the
 * component INSTANCE — `const instance = new <Component>(); instance.<op>(...);
 * expect(instance.<field>)...` — so assertions target instance state, never
 * the void return value (VERSAILLES-26). A STATIC void operation with
 * assertions renders the bare call `<Component>.<op>(...);` with no
 * instance.<field> assertion — the static call never touches a constructed
 * instance, so an instance assertion would be meaningless (VERSAILLES-26
 * follow-up, W1). Without the `methods` option
 * (legacy) the historical static options-object call
 * `<Component>.<op>({ ...inputs })` with a toBeDefined assertion is preserved
 * byte-identically.
 */
import type {
	ArbitrarySpec,
	AssertionDescriptor,
	EmitOptions,
	EmittedFile,
	OperationCaseGroup,
	PlannedCase,
	PlannedSuite,
	PropertyDescriptor,
	PropertyPlan,
} from "../ir.js";
import { sanitizeId } from "./shared.js";

/** Tool-owned generated output directory (config default, build-spec §9.4). */
const DEFAULT_GENERATED_DIR = ".versailles/generated";
/** Default module import specifier relative to a generated file. */
const DEFAULT_MODULE_PREFIX = "../../src/";
/**
 * Default run count for `fc.assert(prop, { seed, numRuns })` when
 * config.propertyBased.numRuns is absent (build-spec §9.6, ADR-0017).
 */
const DEFAULT_PROPERTY_NUM_RUNS = 100;

type ComponentGroup = {
	operations: OperationCaseGroup[];
	invariantCases: PlannedCase[];
};

/**
 * Valid JS identifier (Center W1): component / operation names and input keys
 * flow raw into import specifiers, describe titles, method calls and object
 * keys — the emitter refuses to render anything that could break out of the
 * generated surface.
 */
const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function assertIdentifier(name: string, what: string): void {
	if (!IDENTIFIER_RE.test(name)) {
		throw new Error(
			`Refusing to emit: ${what} "${name}" is not a valid JS identifier (must match /^[A-Za-z_$][A-Za-z0-9_$]*$/)`,
		);
	}
}

export function emitVitest(
	suite: PlannedSuite,
	options?: EmitOptions,
): EmittedFile[] {
	const generatedDir = options?.generatedDir ?? DEFAULT_GENERATED_DIR;
	const modulePaths = options?.modulePaths ?? {};
	const methods = options?.methods;
	const propertyPlan = options?.propertyPlan;
	const propertyNumRuns = options?.propertyNumRuns ?? DEFAULT_PROPERTY_NUM_RUNS;
	const groups = groupByComponent(suite);
	const files: EmittedFile[] = [];
	for (const component of Object.keys(groups)) {
		assertIdentifier(component, "component name");
		const content = renderComponentFile(
			component,
			groups[component],
			suite.clauseIds,
			modulePaths,
			methods,
			propertyPlan,
			propertyNumRuns,
		);
		files.push({ path: `${generatedDir}/${component}.test.ts`, content });
	}
	return files;
}

function groupByComponent(suite: PlannedSuite): Record<string, ComponentGroup> {
	const groups: Record<string, ComponentGroup> = {};
	for (const group of suite.operations) {
		const entry = groups[group.component] ?? {
			operations: [],
			invariantCases: [],
		};
		entry.operations.push(group);
		groups[group.component] = entry;
	}
	for (const case_ of suite.invariantCases) {
		const component = case_.id.split(".")[0];
		const entry = groups[component] ?? { operations: [], invariantCases: [] };
		entry.invariantCases.push(case_);
		groups[component] = entry;
	}
	return groups;
}

function renderComponentFile(
	component: string,
	group: ComponentGroup,
	clauseIds: string[],
	modulePaths: Record<string, string>,
	methods: EmitOptions["methods"],
	propertyPlan?: PropertyPlan,
	propertyNumRuns: number = DEFAULT_PROPERTY_NUM_RUNS,
): string {
	const lines: string[] = [];
	lines.push(
		"// Auto-generated by the Versailles deterministic generator core.",
	);
	lines.push("// Do not edit — regenerate with `versailles generate`.");
	// §9.3: the traceability comment references the contract clause ids the
	// generated surface covers (the full source clause set, so zero-coverage
	// gaps stay visible against the manifest). Clause ids are escaped with
	// JSON.stringify so a hostile id can never break out of the comment into
	// an executable line (Center W1).
	lines.push(
		`// traces: ${clauseIds.map((id) => JSON.stringify(id)).join(", ")}`,
	);
	lines.push('import { describe, expect, it } from "vitest";');
	lines.push("");
	// modulePaths override wins when present and non-empty; an absent (legacy)
	// or empty entry falls back to the deterministic default — an empty-string
	// import must never be emitted (deterministic-generation.contract.yaml).
	const override = modulePaths[component];
	const modulePath =
		typeof override === "string" && override.length > 0
			? override
			: `${DEFAULT_MODULE_PREFIX}${component}.js`;
	lines.push(`import { ${component} } from "${modulePath}";`);
	// ADR-0017: the fast-check import lands immediately after the component
	// import, only when the component has at least one property descriptor.
	// Absent/empty propertyPlan renders the v1 header byte-for-byte (the
	// enabled=false backward-compat pin).
	const componentDescriptors = (propertyPlan?.descriptors ?? []).filter(
		(descriptor) => descriptor.component === component,
	);
	if (componentDescriptors.length > 0) {
		lines.push('import { fc } from "fast-check";');
	}
	lines.push("");

	for (const operation of group.operations) {
		assertIdentifier(operation.operation, "operation name");
		const propertyDescriptors = componentDescriptors.filter(
			(descriptor) => descriptor.operation === operation.operation,
		);
		// V-27 empty-group pin + ADR-0017: an operation with zero concrete
		// cases but at least one property descriptor must still render its
		// describe — the property blocks are the only content inside.
		if (operation.cases.length > 0 || propertyDescriptors.length > 0) {
			lines.push(`describe("${operation.operation}", () => {`);
			for (const case_ of operation.cases) {
				lines.push(
					...renderCase(case_, component, operation.operation, methods),
				);
			}
			// Property blocks render AFTER the operation's concrete cases, in
			// plan.descriptors order (the planner already traverses operations
			// in component order, so a per-operation filter preserves it).
			for (const descriptor of propertyDescriptors) {
				lines.push(...renderPropertyBlock(descriptor, propertyNumRuns));
			}
			lines.push("});");
			lines.push("");
		}
	}

	if (group.invariantCases.length > 0) {
		lines.push(`describe("${component} invariants", () => {`);
		for (const case_ of group.invariantCases) {
			const operation = operationOf(case_);
			assertIdentifier(operation, "operation name");
			lines.push(...renderCase(case_, component, operation, methods));
		}
		lines.push("});");
		lines.push("");
	}

	return lines.join("\n");
}

/**
 * Matcher family per assertion op — renders a real vitest matcher on the
 * subject field instead of a bare toBeDefined() accept render (Center W2b).
 */
const MATCHER: Record<AssertionDescriptor["op"], string> = {
	">=": "toBeGreaterThanOrEqual",
	">": "toBeGreaterThan",
	"<=": "toBeLessThanOrEqual",
	"<": "toBeLessThan",
	"==": "toEqual",
	"!=": "not.toEqual",
};

/**
 * Renders a real vitest matcher on the subject field. The receiver is either
 * "result" (a non-void operation's return value) or "instance" (a bound
 * component instance for void-returning operations, VERSAILLES-26) — a void
 * call's return value is undefined and must never be the assertion subject.
 */
function renderAssertion(
	assertion: AssertionDescriptor,
	receiver: "result" | "instance",
): string {
	const matcher = MATCHER[assertion.op];
	return `expect(${receiver}.${assertion.subject}).${matcher}(${renderValue(assertion.literal)})`;
}

function renderCase(
	case_: PlannedCase,
	component: string,
	operation: string,
	methods: EmitOptions["methods"],
): string[] {
	const title = `${case_.id} — ${case_.description}`;
	const call = renderCall(case_, component, operation, methods);
	const meta = methods?.[component]?.[operation];
	// §9.4 shape awareness: a void-returning operation's accept case must not
	// assert the return value (expect(result).toBeDefined() fails on
	// undefined). Only metadata-driven renders skip it — the legacy default
	// (no methods metadata) keeps the historical toBeDefined assertion.
	const voidAccept =
		meta?.returnType === "void" && case_.expects.outcome === "accept";
	const lines: string[] = [];
	lines.push(`\tit(${JSON.stringify(title)}, () => {`);
	if (case_.expects.outcome === "reject") {
		const idiom = case_.expects.rejectionIdiom ?? "throws";
		switch (idiom) {
			case "throws":
				lines.push(`\t\texpect(() => ${call}).toThrow();`);
				break;
			case "returns":
				lines.push(`\t\texpect(${call}).toBeNull();`);
				break;
			default:
				throw new Error(
					`Unknown rejection idiom "${idiom}" for case "${case_.id}"`,
				);
		}
	} else {
		const assertions = case_.expects.assertions ?? [];
		if (voidAccept) {
			if (meta.static) {
				// W1 (VERSAILLES-26 follow-up,
				// deterministic-generation.contract.yaml): a STATIC void
				// operation's accept/invariant case renders the bare call —
				// `<Component>.<op>(...);` — with NO instance binding, NO
				// result binding, and NO assertions. The static call never
				// touches a constructed instance, so `const instance = new
				// <Component>(); <Component>.<op>(...); expect(instance.<field>)`
				// would assert state on an object the call cannot have
				// modified — a silently meaningless assertion. Instance void
				// ops keep the V-26 instance-state render below.
				lines.push(`\t\t${call};`);
			} else if (assertions.length > 0) {
				// VERSAILLES-26: a void-returning operation's return value is
				// undefined, so `const result = ...; expect(result.<field>)`
				// throws TypeError at runtime. The case binds the component
				// INSTANCE and asserts instance state — `const instance = new
				// <Component>(); instance.<op>(...); expect(instance.<field>)`
				// (§9.4). Only INSTANCE void ops reach this branch (the static
				// void carve-out above handles the static variant), so the
				// call always runs on the bound instance.
				lines.push(`\t\tconst instance = new ${component}();`);
				// B1: the assertion literal is derived by the planner from its
				// captured pre-call state, so the emitter must establish that
				// state on the bound instance before the call runs.
				const paramNames = new Set(meta.params);
				for (const key of Object.keys(case_.inputs)) {
					if (!paramNames.has(key)) {
						assertIdentifier(key, "pre-state input key");
						lines.push(
							`\t\tinstance.${key} = ${renderValue(case_.inputs[key])};`,
						);
					}
				}
				lines.push(
					`\t\tinstance.${operation}${renderPositionalArgs(case_, component, operation, methods)};`,
				);
				for (const assertion of assertions) {
					lines.push(`\t\t${renderAssertion(assertion, "instance")};`);
				}
			} else {
				// Bare call — no result binding, no return-value assertion.
				lines.push(`\t\t${call};`);
			}
		} else {
			lines.push(`\t\tconst result = ${call};`);
			lines.push("\t\texpect(result).toBeDefined();");
			for (const assertion of assertions) {
				lines.push(`\t\t${renderAssertion(assertion, "result")};`);
			}
		}
	}
	lines.push("\t});");
	lines.push("");
	return lines;
}

/**
 * Renders one seeded property block (ADR-0017, build-spec §9.6) — a §9.3
 * tab-indented traceability comment plus an `it` whose body builds the
 * per-param arbitraries, embeds the codegen'd clause oracles verbatim, runs
 * the operation with the legacy options-object call, and asserts the outcome.
 *
 * Pinned layout (tab-indented, space after commas):
 *
 * ```ts
 * 	// traces: "AccountService.withdraw.pre0"
 * 	it("AccountService.withdraw.property-satisfies-0", () => {
 * 		const amount = fc.integer({ min: 10, max: 100 });
 * 		const prop = fc.property(amount, (amount) => {
 * 			const AccountService_withdraw_pre0 = (amount) => amount >= 10 && amount <= 100;
 * 			const result = AccountService.withdraw({ amount });
 * 			expect(result).toBeDefined();
 * 		});
 * 		fc.assert(prop, { seed: 123456789, numRuns: 100 });
 * 	});
 * ```
 *
 * Rejects render the descriptor's configured rejection idiom (ADR-0007) —
 * "throws" → `expect(() => call).toThrow()`, "returns" → `expect(call).toBeNull()`
 * — never hardcoded. Satisfies and invariant-preserving share the uniform
 * non-rejects layout (`const result = call; expect(result).toBeDefined();`).
 */
function renderPropertyBlock(
	descriptor: PropertyDescriptor,
	propertyNumRuns: number,
): string[] {
	const lines: string[] = [];
	lines.push(
		`\t// traces: ${descriptor.traces.map((id) => JSON.stringify(id)).join(", ")}`,
	);
	lines.push(`\tit(${JSON.stringify(descriptor.id)}, () => {`);
	for (const spec of descriptor.params) {
		assertIdentifier(spec.param, "param name");
		lines.push(`\t\tconst ${spec.param} = ${renderArbitrary(spec)};`);
	}
	const params = descriptor.params.map((spec) => spec.param).join(", ");
	lines.push(`\t\tconst prop = fc.property(${params}, (${params}) => {`);
	for (const clause of descriptor.clauses) {
		lines.push(`\t\t\tconst ${sanitizeId(clause.clauseId)} = ${clause.code};`);
	}
	const call = `${descriptor.component}.${descriptor.operation}({ ${params} })`;
	if (descriptor.outcome === "rejects") {
		const idiom = descriptor.rejectionIdiom ?? "throws";
		switch (idiom) {
			case "throws":
				lines.push(`\t\t\texpect(() => ${call}).toThrow();`);
				break;
			case "returns":
				lines.push(`\t\t\texpect(${call}).toBeNull();`);
				break;
			default:
				throw new Error(
					`Unknown rejection idiom "${idiom}" for property "${descriptor.id}"`,
				);
		}
	} else {
		lines.push(`\t\t\tconst result = ${call};`);
		lines.push("\t\t\texpect(result).toBeDefined();");
	}
	lines.push("\t\t});");
	lines.push(
		`\t\tfc.assert(prop, { seed: ${String(descriptor.seed)}, numRuns: ${String(propertyNumRuns)} });`,
	);
	lines.push("\t});");
	lines.push("");
	return lines;
}

/**
 * Renders one per-param arbitrary (ArbitrarySpec → fast-check call). The
 * deterministic `default` (list<X> → `fc.constant([])`, optional<X> →
 * `fc.constant(<inner default>)`) wins over the kind; otherwise kind selects
 * the arbitrary family: number with bounds → `fc.integer({ min, max })`,
 * number without → `fc.integer()`, enum → `fc.constantFrom(<members>)`
 * (JSON-stringified, joined ", "), string → `fc.string()`, boolean →
 * `fc.boolean()`.
 */
function renderArbitrary(spec: ArbitrarySpec): string {
	if (spec.default !== undefined) {
		return `fc.constant(${renderValue(spec.default)})`;
	}
	switch (spec.kind) {
		case "number":
			if (spec.bounds !== undefined) {
				return `fc.integer({ min: ${spec.bounds.min}, max: ${spec.bounds.max} })`;
			}
			return "fc.integer()";
		case "enum": {
			const members = (spec.members ?? [])
				.map((member) => JSON.stringify(member))
				.join(", ");
			return `fc.constantFrom(${members})`;
		}
		case "string":
			return "fc.string()";
		case "boolean":
			return "fc.boolean()";
	}
}

/**
 * Shape-aware call rendering from manifest method metadata (VERSAILLES-20 F1,
 * deterministic-generation.contract.yaml §9.4):
 *
 * - instance method → `new <Component>().<op>(<positional args>)`
 * - static method  → `<Component>.<op>(<positional args>)`
 * - params pass POSITIONALLY in the metadata's declared order, looked up in
 *   the case inputs by name — a declared param missing from inputs renders
 *   the deterministic default `undefined`, and captured pre-call state (e.g.
 *   balance) never leaks into the call because only declared params are read.
 *
 * Legacy default (no methods metadata for the component+operation): today's
 * static options-object call `<Component>.<op>({ ...inputs })` is preserved
 * byte-identically, keeping existing suites (tests/generator.test.ts and the
 * backward-compat pin in tests/emitters.test.ts) green.
 */
function renderCall(
	case_: PlannedCase,
	component: string,
	operation: string,
	methods: EmitOptions["methods"],
): string {
	const meta = methods?.[component]?.[operation];
	if (meta === undefined) {
		return `${component}.${operation}(${renderObjectLiteral(case_.inputs)})`;
	}
	const callee = meta.static
		? `${component}.${operation}`
		: `new ${component}().${operation}`;
	return `${callee}${renderPositionalArgs(case_, component, operation, methods)}`;
}

/**
 * The positional argument list `(<args>)` from the declared metadata params,
 * in declared order (VERSAILLES-20 F1). Split out of renderCall so the
 * void-with-assertions path can invoke a bound instance
 * (`instance.<op>(<args>)`) while reusing the exact same argument computation
 * (VERSAILLES-26). Callers must guarantee method metadata is present (the
 * renderCall meta guard, or the voidAccept branch where meta is defined).
 */
function renderPositionalArgs(
	case_: PlannedCase,
	component: string,
	operation: string,
	methods: EmitOptions["methods"],
): string {
	const meta = methods?.[component]?.[operation];
	if (meta === undefined) {
		throw new Error(
			`Cannot render positional args for "${component}.${operation}" — no method metadata`,
		);
	}
	const args = meta.params.map((param) => {
		assertIdentifier(param, "param name");
		return renderValue(case_.inputs[param]);
	});
	return `(${args.join(", ")})`;
}

/**
 * The operation name is the second segment of "<component>.<operation>.<kind>-<n>".
 * With the id format pinned by Center B1 the segment is always present — a
 * malformed id is a hard error, never masked by a fallback.
 */
function operationOf(case_: PlannedCase): string {
	const parts = case_.id.split(".");
	if (parts.length < 2 || parts[1].length === 0) {
		throw new Error(
			`Cannot derive the operation name from case id "${case_.id}" — expected "<component>.<operation>.<kind>-<n>"`,
		);
	}
	return parts[1];
}

function renderObjectLiteral(inputs: Record<string, unknown>): string {
	const entries = Object.entries(inputs).map(([key, value]) => {
		assertIdentifier(key, "input key");
		return `${key}: ${renderValue(value)}`;
	});
	return `{ ${entries.join(", ")} }`;
}

function renderValue(value: unknown): string {
	if (value === null) {
		return "null";
	}
	if (typeof value === "string") {
		return JSON.stringify(value);
	}
	if (typeof value === "number" || typeof value === "boolean") {
		return String(value);
	}
	if (Array.isArray(value)) {
		return `[${value.map(renderValue).join(", ")}]`;
	}
	if (typeof value === "object") {
		return JSON.stringify(value);
	}
	return String(value);
}
