/**
 * The pytest emitter plugin (ADR-0008/0009) — renders the framework-agnostic
 * IR into full `test_*.py` files ready for idempotent full-file regeneration
 * (build-spec §9.4, ADR-0009: Python → pytest).
 *
 * The emitter is a pure function of the suite: same suite in, byte-identical
 * file content out (ADR-0002). Rejection assertions are rendered from the
 * case's configured idiom ("throws" → with pytest.raises(Exception): ...
 * "returns" → assert ... is None) — never hardcoded (ADR-0007). Accept cases
 * assign the call result and assert it with `assert result is not None` plus
 * real assert-based assertions on the subject field (Center W2). Partition
 * cases render @pytest.mark.parametrize with the input keys declared as
 * function parameters.
 */
import type {
	AssertionDescriptor,
	EmitOptions,
	EmittedFile,
	PlannedCase,
	PlannedSuite,
} from "../ir.js";
import {
	DEFAULT_GENERATED_DIR,
	assertIdentifier,
	groupByComponent,
	operationOf,
	sanitizeId,
} from "./shared.js";
import type { ComponentGroup } from "./shared.js";

/** Default module package prefix for a generated Python file. */
const DEFAULT_MODULE_PREFIX = "components.";

export function emitPytest(
	suite: PlannedSuite,
	options?: EmitOptions,
): EmittedFile[] {
	const generatedDir = options?.generatedDir ?? DEFAULT_GENERATED_DIR;
	const modulePaths = options?.modulePaths ?? {};
	const groups = groupByComponent(suite);
	const files: EmittedFile[] = [];
	for (const component of Object.keys(groups)) {
		assertIdentifier(component, "component name");
		const content = renderComponentFile(
			component,
			groups[component],
			suite.clauseIds,
			modulePaths,
		);
		files.push({ path: `${generatedDir}/test_${component}.py`, content });
	}
	return files;
}

function renderComponentFile(
	component: string,
	group: ComponentGroup,
	clauseIds: string[],
	modulePaths: Record<string, string>,
): string {
	const lines: string[] = [];
	lines.push(
		"# Auto-generated by the Versailles deterministic generator core.",
	);
	lines.push("# Do not edit — regenerate with `versailles generate`.");
	// §9.3: the traceability comment references the contract clause ids the
	// generated surface covers. Clause ids are escaped with JSON.stringify so
	// a hostile id can never break out of the comment into an executable line
	// (Center W1).
	lines.push(
		`# traces: ${clauseIds.map((id) => JSON.stringify(id)).join(", ")}`,
	);
	lines.push("import pytest");
	lines.push("");
	const modulePath =
		modulePaths[component] ?? `${DEFAULT_MODULE_PREFIX}${component}`;
	lines.push(`from ${modulePath} import ${component}`);
	lines.push("");

	for (const operation of group.operations) {
		assertIdentifier(operation.operation, "operation name");
		for (const case_ of operation.cases) {
			lines.push(...renderCase(case_, component, operation.operation));
			lines.push("");
		}
	}

	for (const case_ of group.invariantCases) {
		const operation = operationOf(case_);
		assertIdentifier(operation, "operation name");
		lines.push(...renderCase(case_, component, operation));
		lines.push("");
	}

	return lines.join("\n");
}

function renderCase(
	case_: PlannedCase,
	component: string,
	operation: string,
): string[] {
	const title = `${case_.id} — ${case_.description}`;
	const fnName = `test_${sanitizeId(case_.id)}`;
	const lines: string[] = [];
	lines.push(`# ${title}`);

	const isPartition = case_.kind === "partition";
	const entries = Object.entries(case_.inputs);
	if (isPartition) {
		for (const [key, value] of entries) {
			assertIdentifier(key, "input key");
			lines.push(`@pytest.mark.parametrize("${key}", [${renderValue(value)}])`);
		}
		const params = entries.map(([key]) => key).join(", ");
		lines.push(`def ${fnName}(${params}):`);
	} else {
		lines.push(`def ${fnName}():`);
	}

	const call = isPartition
		? `${component}.${operation}(${renderNamedDict(entries)})`
		: `${component}.${operation}(${renderDictLiteral(case_.inputs)})`;

	if (case_.expects.outcome === "reject") {
		const idiom = case_.expects.rejectionIdiom ?? "throws";
		switch (idiom) {
			case "throws":
				lines.push("    with pytest.raises(Exception):");
				lines.push(`        ${call}`);
				break;
			case "returns":
				lines.push(`    assert ${call} is None`);
				break;
			default:
				throw new Error(
					`Unknown rejection idiom "${idiom}" for case "${case_.id}"`,
				);
		}
	} else {
		const assertions = case_.expects.assertions ?? [];
		lines.push(`    result = ${call}`);
		lines.push("    assert result is not None");
		for (const assertion of assertions) {
			lines.push(`    ${renderAssertion(assertion)}`);
		}
	}
	return lines;
}

function renderAssertion(assertion: AssertionDescriptor): string {
	return `assert result.${assertion.subject} ${assertion.op} ${renderValue(assertion.literal)}`;
}

/**
 * Python dict literal from the case inputs (params + captured pre-state), e.g.
 * `{"amount": 55, "balance": 50}`.
 */
function renderDictLiteral(inputs: Record<string, unknown>): string {
	const entries = Object.entries(inputs).map(([key, value]) => {
		assertIdentifier(key, "input key");
		return `${JSON.stringify(key)}: ${renderValue(value)}`;
	});
	return `{${entries.join(", ")}}`;
}

/**
 * Python dict built from the named function parameters (partition cases), e.g.
 * `{"newStatus": newStatus}`.
 */
function renderNamedDict(entries: [string, unknown][]): string {
	const pairs = entries.map(([key]) => {
		assertIdentifier(key, "input key");
		return `${JSON.stringify(key)}: ${key}`;
	});
	return `{${pairs.join(", ")}}`;
}

/** Python literal for a parametrize value / dict member value. */
function renderValue(value: unknown): string {
	if (value === null) {
		return "None";
	}
	if (typeof value === "string") {
		return JSON.stringify(value);
	}
	if (typeof value === "number") {
		return String(value);
	}
	if (typeof value === "boolean") {
		return value ? "True" : "False";
	}
	if (Array.isArray(value)) {
		return `[${value.map(renderValue).join(", ")}]`;
	}
	if (typeof value === "object") {
		const entries = Object.entries(value as Record<string, unknown>).map(
			([key, nested]) => `${JSON.stringify(key)}: ${renderValue(nested)}`,
		);
		return `{${entries.join(", ")}}`;
	}
	return String(value);
}
