/**
 * The vitest emitter plugin (ADR-0008/0009) — the ONLY framework rendering in
 * the generator core. Renders the framework-agnostic IR into full `.test.ts`
 * files ready for idempotent full-file regeneration (build-spec §9.4).
 *
 * The emitter is a pure function of the suite: same suite in, byte-identical
 * file content out. Rejection assertions are rendered from the case's
 * configured idiom ("throws" → expect(() => op(inputs)).toThrow();
 * "returns" → expect(op(inputs)).toBeNull()) — never hardcoded (ADR-0007).
 *
 * Call rendering is shape-aware from manifest method metadata
 * (deterministic-generation.contract.yaml §9.4, VERSAILLES-20 F1): instance
 * methods render `new <Component>().<op>(<positional>)`, static methods render
 * `<Component>.<op>(<positional>)` with params in declared order, and
 * void-return accept cases carry no return-value assertion. Without the
 * `methods` option (legacy) the historical static options-object call
 * `<Component>.<op>({ ...inputs })` with a toBeDefined assertion is preserved
 * byte-identically.
 */
import type {
	AssertionDescriptor,
	EmitOptions,
	EmittedFile,
	OperationCaseGroup,
	PlannedCase,
	PlannedSuite,
} from "../ir.js";

/** Tool-owned generated output directory (config default, build-spec §9.4). */
const DEFAULT_GENERATED_DIR = ".versailles/generated";
/** Default module import specifier relative to a generated file. */
const DEFAULT_MODULE_PREFIX = "../../src/";

type ComponentGroup = {
	operations: OperationCaseGroup[];
	invariantCases: PlannedCase[];
};

/**
 * Valid JS identifier (Center W1): component / operation names and input keys
 * flow raw into import specifiers, describe titles, method calls and object
 * keys — the emitter refuses to render anything that could break out of the
 * generated surface.
 */
const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function assertIdentifier(name: string, what: string): void {
	if (!IDENTIFIER_RE.test(name)) {
		throw new Error(
			`Refusing to emit: ${what} "${name}" is not a valid JS identifier (must match /^[A-Za-z_$][A-Za-z0-9_$]*$/)`,
		);
	}
}

export function emitVitest(
	suite: PlannedSuite,
	options?: EmitOptions,
): EmittedFile[] {
	const generatedDir = options?.generatedDir ?? DEFAULT_GENERATED_DIR;
	const modulePaths = options?.modulePaths ?? {};
	const methods = options?.methods;
	const groups = groupByComponent(suite);
	const files: EmittedFile[] = [];
	for (const component of Object.keys(groups)) {
		assertIdentifier(component, "component name");
		const content = renderComponentFile(
			component,
			groups[component],
			suite.clauseIds,
			modulePaths,
			methods,
		);
		files.push({ path: `${generatedDir}/${component}.test.ts`, content });
	}
	return files;
}

function groupByComponent(suite: PlannedSuite): Record<string, ComponentGroup> {
	const groups: Record<string, ComponentGroup> = {};
	for (const group of suite.operations) {
		const entry = groups[group.component] ?? {
			operations: [],
			invariantCases: [],
		};
		entry.operations.push(group);
		groups[group.component] = entry;
	}
	for (const case_ of suite.invariantCases) {
		const component = case_.id.split(".")[0];
		const entry = groups[component] ?? { operations: [], invariantCases: [] };
		entry.invariantCases.push(case_);
		groups[component] = entry;
	}
	return groups;
}

function renderComponentFile(
	component: string,
	group: ComponentGroup,
	clauseIds: string[],
	modulePaths: Record<string, string>,
	methods: EmitOptions["methods"],
): string {
	const lines: string[] = [];
	lines.push(
		"// Auto-generated by the Versailles deterministic generator core.",
	);
	lines.push("// Do not edit — regenerate with `versailles generate`.");
	// §9.3: the traceability comment references the contract clause ids the
	// generated surface covers (the full source clause set, so zero-coverage
	// gaps stay visible against the manifest). Clause ids are escaped with
	// JSON.stringify so a hostile id can never break out of the comment into
	// an executable line (Center W1).
	lines.push(
		`// traces: ${clauseIds.map((id) => JSON.stringify(id)).join(", ")}`,
	);
	lines.push('import { describe, expect, it } from "vitest";');
	lines.push("");
	// modulePaths override wins when present and non-empty; an absent (legacy)
	// or empty entry falls back to the deterministic default — an empty-string
	// import must never be emitted (deterministic-generation.contract.yaml).
	const override = modulePaths[component];
	const modulePath =
		typeof override === "string" && override.length > 0
			? override
			: `${DEFAULT_MODULE_PREFIX}${component}.js`;
	lines.push(`import { ${component} } from "${modulePath}";`);
	lines.push("");

	for (const operation of group.operations) {
		assertIdentifier(operation.operation, "operation name");
		lines.push(`describe("${operation.operation}", () => {`);
		for (const case_ of operation.cases) {
			lines.push(...renderCase(case_, component, operation.operation, methods));
		}
		lines.push("});");
		lines.push("");
	}

	if (group.invariantCases.length > 0) {
		lines.push(`describe("${component} invariants", () => {`);
		for (const case_ of group.invariantCases) {
			const operation = operationOf(case_);
			assertIdentifier(operation, "operation name");
			lines.push(...renderCase(case_, component, operation, methods));
		}
		lines.push("});");
		lines.push("");
	}

	return lines.join("\n");
}

/**
 * Matcher family per assertion op — renders a real vitest matcher on the
 * subject field instead of a bare toBeDefined() accept render (Center W2b).
 */
const MATCHER: Record<AssertionDescriptor["op"], string> = {
	">=": "toBeGreaterThanOrEqual",
	">": "toBeGreaterThan",
	"<=": "toBeLessThanOrEqual",
	"<": "toBeLessThan",
	"==": "toEqual",
	"!=": "not.toEqual",
};

function renderAssertion(assertion: AssertionDescriptor): string {
	const matcher = MATCHER[assertion.op];
	return `expect(result.${assertion.subject}).${matcher}(${renderValue(assertion.literal)})`;
}

function renderCase(
	case_: PlannedCase,
	component: string,
	operation: string,
	methods: EmitOptions["methods"],
): string[] {
	const title = `${case_.id} — ${case_.description}`;
	const call = renderCall(case_, component, operation, methods);
	const meta = methods?.[component]?.[operation];
	// §9.4 shape awareness: a void-returning operation's accept case must not
	// assert the return value (expect(result).toBeDefined() fails on
	// undefined). Only metadata-driven renders skip it — the legacy default
	// (no methods metadata) keeps the historical toBeDefined assertion.
	const voidAccept =
		meta?.returnType === "void" && case_.expects.outcome === "accept";
	const lines: string[] = [];
	lines.push(`\tit(${JSON.stringify(title)}, () => {`);
	if (case_.expects.outcome === "reject") {
		const idiom = case_.expects.rejectionIdiom ?? "throws";
		switch (idiom) {
			case "throws":
				lines.push(`\t\texpect(() => ${call}).toThrow();`);
				break;
			case "returns":
				lines.push(`\t\texpect(${call}).toBeNull();`);
				break;
			default:
				throw new Error(
					`Unknown rejection idiom "${idiom}" for case "${case_.id}"`,
				);
		}
	} else {
		const assertions = case_.expects.assertions ?? [];
		if (voidAccept) {
			// Bare call — no result binding, no return-value assertion. Real
			// matcher assertions (which reference `result`) still render when
			// present, so an invariant on a void operation stays assertable.
			if (assertions.length > 0) {
				lines.push(`\t\tconst result = ${call};`);
				for (const assertion of assertions) {
					lines.push(`\t\t${renderAssertion(assertion)};`);
				}
			} else {
				lines.push(`\t\t${call};`);
			}
		} else {
			lines.push(`\t\tconst result = ${call};`);
			lines.push("\t\texpect(result).toBeDefined();");
			for (const assertion of assertions) {
				lines.push(`\t\t${renderAssertion(assertion)};`);
			}
		}
	}
	lines.push("\t});");
	lines.push("");
	return lines;
}

/**
 * Shape-aware call rendering from manifest method metadata (VERSAILLES-20 F1,
 * deterministic-generation.contract.yaml §9.4):
 *
 * - instance method → `new <Component>().<op>(<positional args>)`
 * - static method  → `<Component>.<op>(<positional args>)`
 * - params pass POSITIONALLY in the metadata's declared order, looked up in
 *   the case inputs by name — a declared param missing from inputs renders
 *   the deterministic default `undefined`, and captured pre-call state (e.g.
 *   balance) never leaks into the call because only declared params are read.
 *
 * Legacy default (no methods metadata for the component+operation): today's
 * static options-object call `<Component>.<op>({ ...inputs })` is preserved
 * byte-identically, keeping existing suites (tests/generator.test.ts and the
 * backward-compat pin in tests/emitters.test.ts) green.
 */
function renderCall(
	case_: PlannedCase,
	component: string,
	operation: string,
	methods: EmitOptions["methods"],
): string {
	const meta = methods?.[component]?.[operation];
	if (meta === undefined) {
		return `${component}.${operation}(${renderObjectLiteral(case_.inputs)})`;
	}
	const args = meta.params.map((param) => {
		assertIdentifier(param, "param name");
		return renderValue(case_.inputs[param]);
	});
	const callee = meta.static
		? `${component}.${operation}`
		: `new ${component}().${operation}`;
	return `${callee}(${args.join(", ")})`;
}

/**
 * The operation name is the second segment of "<component>.<operation>.<kind>-<n>".
 * With the id format pinned by Center B1 the segment is always present — a
 * malformed id is a hard error, never masked by a fallback.
 */
function operationOf(case_: PlannedCase): string {
	const parts = case_.id.split(".");
	if (parts.length < 2 || parts[1].length === 0) {
		throw new Error(
			`Cannot derive the operation name from case id "${case_.id}" — expected "<component>.<operation>.<kind>-<n>"`,
		);
	}
	return parts[1];
}

function renderObjectLiteral(inputs: Record<string, unknown>): string {
	const entries = Object.entries(inputs).map(([key, value]) => {
		assertIdentifier(key, "input key");
		return `${key}: ${renderValue(value)}`;
	});
	return `{ ${entries.join(", ")} }`;
}

function renderValue(value: unknown): string {
	if (value === null) {
		return "null";
	}
	if (typeof value === "string") {
		return JSON.stringify(value);
	}
	if (typeof value === "number" || typeof value === "boolean") {
		return String(value);
	}
	if (Array.isArray(value)) {
		return `[${value.map(renderValue).join(", ")}]`;
	}
	if (typeof value === "object") {
		return JSON.stringify(value);
	}
	return String(value);
}
