/**
 * The vitest emitter plugin (ADR-0008/0009) — the ONLY framework rendering in
 * the generator core. Renders the framework-agnostic IR into full `.test.ts`
 * files ready for idempotent full-file regeneration (build-spec §9.4).
 *
 * The emitter is a pure function of the suite: same suite in, byte-identical
 * file content out. Rejection assertions are rendered from the case's
 * configured idiom ("throws" → expect(() => op(inputs)).toThrow();
 * "returns" → expect(op(inputs)).toBeNull()) — never hardcoded (ADR-0007).
 */
import type {
	EmittedFile,
	OperationCaseGroup,
	PlannedCase,
	PlannedSuite,
} from "../ir.js";

/** Tool-owned generated output directory (config default, build-spec §9.4). */
const GENERATED_DIR = ".versailles/generated";

type ComponentGroup = {
	operations: OperationCaseGroup[];
	invariantCases: PlannedCase[];
};

export function emitVitest(suite: PlannedSuite): EmittedFile[] {
	const groups = groupByComponent(suite);
	const files: EmittedFile[] = [];
	for (const component of Object.keys(groups)) {
		const content = renderComponentFile(
			component,
			groups[component],
			suite.clauseIds,
		);
		files.push({ path: `${GENERATED_DIR}/${component}.test.ts`, content });
	}
	return files;
}

function groupByComponent(suite: PlannedSuite): Record<string, ComponentGroup> {
	const groups: Record<string, ComponentGroup> = {};
	for (const group of suite.operations) {
		const entry = groups[group.component] ?? {
			operations: [],
			invariantCases: [],
		};
		entry.operations.push(group);
		groups[group.component] = entry;
	}
	for (const case_ of suite.invariantCases) {
		const component = case_.id.split(".")[0];
		const entry = groups[component] ?? { operations: [], invariantCases: [] };
		entry.invariantCases.push(case_);
		groups[component] = entry;
	}
	return groups;
}

function renderComponentFile(
	component: string,
	group: ComponentGroup,
	clauseIds: string[],
): string {
	const lines: string[] = [];
	lines.push(
		"// Auto-generated by the Versailles deterministic generator core.",
	);
	lines.push("// Do not edit — regenerate with `versailles generate`.");
	// §9.3: the traceability comment references the contract clause ids the
	// generated surface covers (the full source clause set, so zero-coverage
	// gaps stay visible against the manifest).
	lines.push(`// traces: ${clauseIds.join(", ")}`);
	lines.push('import { describe, expect, it } from "vitest";');
	lines.push("");
	lines.push(`import { ${component} } from "../../src/${component}.js";`);
	lines.push("");

	for (const operation of group.operations) {
		lines.push(`describe("${operation.operation}", () => {`);
		for (const case_ of operation.cases) {
			lines.push(...renderCase(case_, component, operation.operation));
		}
		lines.push("});");
		lines.push("");
	}

	if (group.invariantCases.length > 0) {
		lines.push(`describe("${component} invariants", () => {`);
		for (const case_ of group.invariantCases) {
			lines.push(...renderCase(case_, component, operationOf(case_)));
		}
		lines.push("});");
		lines.push("");
	}

	return lines.join("\n");
}

function renderCase(
	case_: PlannedCase,
	component: string,
	operation: string,
): string[] {
	const title = `${case_.id} — ${case_.description}`;
	const inputLiteral = renderObjectLiteral(case_.inputs);
	const call = `${component}.${operation}(${inputLiteral})`;
	const lines: string[] = [];
	lines.push(`\tit(${JSON.stringify(title)}, () => {`);
	if (case_.expects.outcome === "reject") {
		const idiom = case_.expects.rejectionIdiom ?? "throws";
		if (idiom === "throws") {
			lines.push(`\t\texpect(() => ${call}).toThrow();`);
		} else {
			lines.push(`\t\texpect(${call}).toBeNull();`);
		}
	} else {
		lines.push(`\t\texpect(${call}).toBeDefined();`);
	}
	lines.push("\t});");
	lines.push("");
	return lines;
}

/** The operation name is the second segment of "<component>.<operation>.<kind>-<n>". */
function operationOf(case_: PlannedCase): string {
	const parts = case_.id.split(".");
	return parts.length >= 2 ? parts[1] : "operation";
}

function renderObjectLiteral(inputs: Record<string, unknown>): string {
	const entries = Object.entries(inputs).map(
		([key, value]) => `${key}: ${renderValue(value)}`,
	);
	return `{ ${entries.join(", ")} }`;
}

function renderValue(value: unknown): string {
	if (value === null) {
		return "null";
	}
	if (typeof value === "string") {
		return JSON.stringify(value);
	}
	if (typeof value === "number" || typeof value === "boolean") {
		return String(value);
	}
	if (Array.isArray(value)) {
		return `[${value.map(renderValue).join(", ")}]`;
	}
	if (typeof value === "object") {
		return JSON.stringify(value);
	}
	return String(value);
}
