/**
 * The xUnit emitter plugin (ADR-0008/0009) — renders the framework-agnostic
 * IR into full `*.Tests.cs` files ready for idempotent full-file regeneration
 * (build-spec §9.4, ADR-0009: C# → xUnit).
 *
 * The emitter is a pure function of the suite: same suite in, byte-identical
 * file content out (ADR-0002). Rejection assertions are rendered from the
 * case's configured idiom ("throws" → Assert.Throws<Exception>(() => ...);
 * "returns" → Assert.Null(...)) — never hardcoded (ADR-0007). Accept cases
 * assert the call result with Assert.NotNull plus real matcher assertions on
 * the subject field (Center W2). Partition cases render [Theory]/[InlineData]
 * with the input keys declared as method parameters.
 */
import type {
	AssertionDescriptor,
	EmitOptions,
	EmittedFile,
	PlannedCase,
	PlannedSuite,
} from "../ir.js";
import {
	DEFAULT_GENERATED_DIR,
	assertIdentifier,
	groupByComponent,
	operationOf,
	sanitizeId,
} from "./shared.js";
import type { ComponentGroup } from "./shared.js";

/** Default module namespace prefix for a generated C# file. */
const DEFAULT_MODULE_PREFIX = "Versailles.Components.";

/**
 * Assertion family per op — renders a real xUnit assertion on the subject
 * field instead of a bare accept render (Center W2, mirrors the vitest
 * MATCHER map).
 */
const ASSERT: Record<
	AssertionDescriptor["op"],
	(subject: string, literal: string) => string
> = {
	">=": (subject, literal) => `Assert.True(result.${subject} >= ${literal});`,
	">": (subject, literal) => `Assert.True(result.${subject} > ${literal});`,
	"<=": (subject, literal) => `Assert.True(result.${subject} <= ${literal});`,
	"<": (subject, literal) => `Assert.True(result.${subject} < ${literal});`,
	"==": (subject, literal) => `Assert.Equal(${literal}, result.${subject});`,
	"!=": (subject, literal) => `Assert.NotEqual(${literal}, result.${subject});`,
};

export function emitXunit(
	suite: PlannedSuite,
	options?: EmitOptions,
): EmittedFile[] {
	const generatedDir = options?.generatedDir ?? DEFAULT_GENERATED_DIR;
	const modulePaths = options?.modulePaths ?? {};
	const groups = groupByComponent(suite);
	const files: EmittedFile[] = [];
	for (const component of Object.keys(groups)) {
		assertIdentifier(component, "component name");
		const content = renderComponentFile(
			component,
			groups[component],
			suite.clauseIds,
			modulePaths,
		);
		files.push({ path: `${generatedDir}/${component}.Tests.cs`, content });
	}
	return files;
}

function renderComponentFile(
	component: string,
	group: ComponentGroup,
	clauseIds: string[],
	modulePaths: Record<string, string>,
): string {
	const lines: string[] = [];
	lines.push(
		"// Auto-generated by the Versailles deterministic generator core.",
	);
	lines.push("// Do not edit — regenerate with `versailles generate`.");
	// §9.3: the traceability comment references the contract clause ids the
	// generated surface covers. Clause ids are escaped with JSON.stringify so
	// a hostile id can never break out of the comment into an executable line
	// (Center W1).
	lines.push(
		`// traces: ${clauseIds.map((id) => JSON.stringify(id)).join(", ")}`,
	);
	lines.push("using System;");
	lines.push("using Xunit;");
	const modulePath =
		modulePaths[component] ?? `${DEFAULT_MODULE_PREFIX}${component}`;
	lines.push(`using ${modulePath};`);
	lines.push("");
	lines.push(`public class ${component}Tests`);
	lines.push("{");

	for (const operation of group.operations) {
		assertIdentifier(operation.operation, "operation name");
		for (const case_ of operation.cases) {
			lines.push(...renderCase(case_, component, operation.operation, "    "));
			lines.push("");
		}
	}

	for (const case_ of group.invariantCases) {
		const operation = operationOf(case_);
		assertIdentifier(operation, "operation name");
		lines.push(...renderCase(case_, component, operation, "    "));
		lines.push("");
	}

	lines.push("}");
	return lines.join("\n");
}

function renderCase(
	case_: PlannedCase,
	component: string,
	operation: string,
	indent: string,
): string[] {
	const title = `${case_.id} — ${case_.description}`;
	const methodName = sanitizeId(case_.id);
	const lines: string[] = [];
	lines.push(`${indent}// ${title}`);

	const isPartition = case_.kind === "partition";
	const entries = Object.entries(case_.inputs);
	if (isPartition) {
		lines.push(`${indent}[Theory]`);
		for (const [, value] of entries) {
			lines.push(`${indent}[InlineData(${renderValue(value)})]`);
		}
		const params = entries
			.map(([key, value]) => `${csharpType(value)} ${key}`)
			.join(", ");
		lines.push(`${indent}public void ${methodName}(${params})`);
	} else {
		lines.push(`${indent}[Fact]`);
		lines.push(`${indent}public void ${methodName}()`);
	}

	lines.push(`${indent}{`);
	const body = `${indent}    `;
	const call = isPartition
		? `${component}.${operation}(${renderNamedObject(entries)})`
		: `${component}.${operation}(${renderObjectLiteral(case_.inputs)})`;

	if (case_.expects.outcome === "reject") {
		const idiom = case_.expects.rejectionIdiom ?? "throws";
		switch (idiom) {
			case "throws":
				lines.push(`${body}Assert.Throws<Exception>(() => ${call});`);
				break;
			case "returns":
				lines.push(`${body}Assert.Null(${call});`);
				break;
			default:
				throw new Error(
					`Unknown rejection idiom "${idiom}" for case "${case_.id}"`,
				);
		}
	} else {
		const assertions = case_.expects.assertions ?? [];
		lines.push(`${body}var result = ${call};`);
		lines.push(`${body}Assert.NotNull(result);`);
		for (const assertion of assertions) {
			lines.push(`${body}${renderAssertion(assertion)}`);
		}
	}
	lines.push(`${indent}}`);
	return lines;
}

function renderAssertion(assertion: AssertionDescriptor): string {
	const render = ASSERT[assertion.op];
	return render(assertion.subject, renderValue(assertion.literal));
}

/**
 * C# anonymous object from the case inputs (params + captured pre-state), e.g.
 * `new { amount = 55, balance = 50 }`.
 */
function renderObjectLiteral(inputs: Record<string, unknown>): string {
	const entries = Object.entries(inputs).map(([key, value]) => {
		assertIdentifier(key, "input key");
		return `${key} = ${renderValue(value)}`;
	});
	return `new { ${entries.join(", ")} }`;
}

/**
 * C# anonymous object built from the named method parameters (partition
 * cases), e.g. `new { newStatus }`.
 */
function renderNamedObject(entries: [string, unknown][]): string {
	const names = entries.map(([key]) => {
		assertIdentifier(key, "input key");
		return key;
	});
	return `new { ${names.join(", ")} }`;
}

/** C# literal for an `[InlineData]` argument / object member value. */
function renderValue(value: unknown): string {
	if (value === null) {
		return "null";
	}
	if (typeof value === "string") {
		return JSON.stringify(value);
	}
	if (typeof value === "number" || typeof value === "boolean") {
		return String(value);
	}
	if (Array.isArray(value)) {
		return `new[] { ${value.map(renderValue).join(", ")} }`;
	}
	if (typeof value === "object") {
		const entries = Object.entries(value as Record<string, unknown>).map(
			([key, nested]) => `${key} = ${renderValue(nested)}`,
		);
		return `new { ${entries.join(", ")} }`;
	}
	return String(value);
}

/** C# parameter type inferred from the planned input value. */
function csharpType(value: unknown): string {
	if (value === null) {
		return "object";
	}
	if (typeof value === "string") {
		return "string";
	}
	if (typeof value === "number") {
		return "double";
	}
	if (typeof value === "boolean") {
		return "bool";
	}
	return "object";
}
